<?php

use Illuminate\Database\Seeder;

class CidadesTableMASeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades do Maranhão
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 2100055, 'estado_id' => 21, 'nome' => 'Açailândia']);
		DB::table('cidades')->insert(['id' => 2100105, 'estado_id' => 21, 'nome' => 'Afonso Cunha']);
		DB::table('cidades')->insert(['id' => 2100154, 'estado_id' => 21, 'nome' => 'Água Doce do Maranhão']);
		DB::table('cidades')->insert(['id' => 2100204, 'estado_id' => 21, 'nome' => 'Alcântara']);
		DB::table('cidades')->insert(['id' => 2100303, 'estado_id' => 21, 'nome' => 'Aldeias Altas']);
		DB::table('cidades')->insert(['id' => 2100402, 'estado_id' => 21, 'nome' => 'Altamira do Maranhão']);
		DB::table('cidades')->insert(['id' => 2100436, 'estado_id' => 21, 'nome' => 'Alto Alegre do Maranhão']);
		DB::table('cidades')->insert(['id' => 2100477, 'estado_id' => 21, 'nome' => 'Alto Alegre do Pindaré']);
		DB::table('cidades')->insert(['id' => 2100501, 'estado_id' => 21, 'nome' => 'Alto Parnaíba']);
		DB::table('cidades')->insert(['id' => 2100550, 'estado_id' => 21, 'nome' => 'Amapá do Maranhão']);
		DB::table('cidades')->insert(['id' => 2100600, 'estado_id' => 21, 'nome' => 'Amarante do Maranhão']);
		DB::table('cidades')->insert(['id' => 2100709, 'estado_id' => 21, 'nome' => 'Anajatuba']);
		DB::table('cidades')->insert(['id' => 2100808, 'estado_id' => 21, 'nome' => 'Anapurus']);
		DB::table('cidades')->insert(['id' => 2100832, 'estado_id' => 21, 'nome' => 'Apicum-Açu']);
		DB::table('cidades')->insert(['id' => 2100873, 'estado_id' => 21, 'nome' => 'Araguanã']);
		DB::table('cidades')->insert(['id' => 2100907, 'estado_id' => 21, 'nome' => 'Araioses']);
		DB::table('cidades')->insert(['id' => 2100956, 'estado_id' => 21, 'nome' => 'Arame']);
		DB::table('cidades')->insert(['id' => 2101004, 'estado_id' => 21, 'nome' => 'Arari']);
		DB::table('cidades')->insert(['id' => 2101103, 'estado_id' => 21, 'nome' => 'Axixá']);
		DB::table('cidades')->insert(['id' => 2101202, 'estado_id' => 21, 'nome' => 'Bacabal']);
		DB::table('cidades')->insert(['id' => 2101251, 'estado_id' => 21, 'nome' => 'Bacabeira']);
		DB::table('cidades')->insert(['id' => 2101301, 'estado_id' => 21, 'nome' => 'Bacuri']);
		DB::table('cidades')->insert(['id' => 2101350, 'estado_id' => 21, 'nome' => 'Bacurituba']);
		DB::table('cidades')->insert(['id' => 2101400, 'estado_id' => 21, 'nome' => 'Balsas']);
		DB::table('cidades')->insert(['id' => 2101509, 'estado_id' => 21, 'nome' => 'Barão de Grajaú']);
		DB::table('cidades')->insert(['id' => 2101608, 'estado_id' => 21, 'nome' => 'Barra do Corda']);
		DB::table('cidades')->insert(['id' => 2101707, 'estado_id' => 21, 'nome' => 'Barreirinhas']);
		DB::table('cidades')->insert(['id' => 2101731, 'estado_id' => 21, 'nome' => 'Belágua']);
		DB::table('cidades')->insert(['id' => 2101772, 'estado_id' => 21, 'nome' => 'Bela Vista do Maranhão']);
		DB::table('cidades')->insert(['id' => 2101806, 'estado_id' => 21, 'nome' => 'Benedito Leite']);
		DB::table('cidades')->insert(['id' => 2101905, 'estado_id' => 21, 'nome' => 'Bequimão']);
		DB::table('cidades')->insert(['id' => 2101939, 'estado_id' => 21, 'nome' => 'Bernardo do Mearim']);
		DB::table('cidades')->insert(['id' => 2101970, 'estado_id' => 21, 'nome' => 'Boa Vista do Gurupi']);
		DB::table('cidades')->insert(['id' => 2102002, 'estado_id' => 21, 'nome' => 'Bom Jardim']);
		DB::table('cidades')->insert(['id' => 2102036, 'estado_id' => 21, 'nome' => 'Bom Jesus das Selvas']);
		DB::table('cidades')->insert(['id' => 2102077, 'estado_id' => 21, 'nome' => 'Bom Lugar']);
		DB::table('cidades')->insert(['id' => 2102101, 'estado_id' => 21, 'nome' => 'Brejo']);
		DB::table('cidades')->insert(['id' => 2102150, 'estado_id' => 21, 'nome' => 'Brejo de Areia']);
		DB::table('cidades')->insert(['id' => 2102200, 'estado_id' => 21, 'nome' => 'Buriti']);
		DB::table('cidades')->insert(['id' => 2102309, 'estado_id' => 21, 'nome' => 'Buriti Bravo']);
		DB::table('cidades')->insert(['id' => 2102325, 'estado_id' => 21, 'nome' => 'Buriticupu']);
		DB::table('cidades')->insert(['id' => 2102358, 'estado_id' => 21, 'nome' => 'Buritirana']);
		DB::table('cidades')->insert(['id' => 2102374, 'estado_id' => 21, 'nome' => 'Cachoeira Grande']);
		DB::table('cidades')->insert(['id' => 2102408, 'estado_id' => 21, 'nome' => 'Cajapió']);
		DB::table('cidades')->insert(['id' => 2102507, 'estado_id' => 21, 'nome' => 'Cajari']);
		DB::table('cidades')->insert(['id' => 2102556, 'estado_id' => 21, 'nome' => 'Campestre do Maranhão']);
		DB::table('cidades')->insert(['id' => 2102606, 'estado_id' => 21, 'nome' => 'Cândido Mendes']);
		DB::table('cidades')->insert(['id' => 2102705, 'estado_id' => 21, 'nome' => 'Cantanhede']);
		DB::table('cidades')->insert(['id' => 2102754, 'estado_id' => 21, 'nome' => 'Capinzal do Norte']);
		DB::table('cidades')->insert(['id' => 2102804, 'estado_id' => 21, 'nome' => 'Carolina']);
		DB::table('cidades')->insert(['id' => 2102903, 'estado_id' => 21, 'nome' => 'Carutapera']);
		DB::table('cidades')->insert(['id' => 2103000, 'estado_id' => 21, 'nome' => 'Caxias']);
		DB::table('cidades')->insert(['id' => 2103109, 'estado_id' => 21, 'nome' => 'Cedral']);
		DB::table('cidades')->insert(['id' => 2103125, 'estado_id' => 21, 'nome' => 'Central do Maranhão']);
		DB::table('cidades')->insert(['id' => 2103158, 'estado_id' => 21, 'nome' => 'Centro do Guilherme']);
		DB::table('cidades')->insert(['id' => 2103174, 'estado_id' => 21, 'nome' => 'Centro Novo do Maranhão']);
		DB::table('cidades')->insert(['id' => 2103208, 'estado_id' => 21, 'nome' => 'Chapadinha']);
		DB::table('cidades')->insert(['id' => 2103257, 'estado_id' => 21, 'nome' => 'Cidelândia']);
		DB::table('cidades')->insert(['id' => 2103307, 'estado_id' => 21, 'nome' => 'Codó']);
		DB::table('cidades')->insert(['id' => 2103406, 'estado_id' => 21, 'nome' => 'Coelho Neto']);
		DB::table('cidades')->insert(['id' => 2103505, 'estado_id' => 21, 'nome' => 'Colinas']);
		DB::table('cidades')->insert(['id' => 2103554, 'estado_id' => 21, 'nome' => 'Conceição do Lago-Açu']);
		DB::table('cidades')->insert(['id' => 2103604, 'estado_id' => 21, 'nome' => 'Coroatá']);
		DB::table('cidades')->insert(['id' => 2103703, 'estado_id' => 21, 'nome' => 'Cururupu']);
		DB::table('cidades')->insert(['id' => 2103752, 'estado_id' => 21, 'nome' => 'Davinópolis']);
		DB::table('cidades')->insert(['id' => 2103802, 'estado_id' => 21, 'nome' => 'Dom Pedro']);
		DB::table('cidades')->insert(['id' => 2103901, 'estado_id' => 21, 'nome' => 'Duque Bacelar']);
		DB::table('cidades')->insert(['id' => 2104008, 'estado_id' => 21, 'nome' => 'Esperantinópolis']);
		DB::table('cidades')->insert(['id' => 2104057, 'estado_id' => 21, 'nome' => 'Estreito']);
		DB::table('cidades')->insert(['id' => 2104073, 'estado_id' => 21, 'nome' => 'Feira Nova do Maranhão']);
		DB::table('cidades')->insert(['id' => 2104081, 'estado_id' => 21, 'nome' => 'Fernando Falcão']);
		DB::table('cidades')->insert(['id' => 2104099, 'estado_id' => 21, 'nome' => 'Formosa da Serra Negra']);
		DB::table('cidades')->insert(['id' => 2104107, 'estado_id' => 21, 'nome' => 'Fortaleza dos Nogueiras']);
		DB::table('cidades')->insert(['id' => 2104206, 'estado_id' => 21, 'nome' => 'Fortuna']);
		DB::table('cidades')->insert(['id' => 2104305, 'estado_id' => 21, 'nome' => 'Godofredo Viana']);
		DB::table('cidades')->insert(['id' => 2104404, 'estado_id' => 21, 'nome' => 'Gonçalves Dias']);
		DB::table('cidades')->insert(['id' => 2104503, 'estado_id' => 21, 'nome' => 'Governador Archer']);
		DB::table('cidades')->insert(['id' => 2104552, 'estado_id' => 21, 'nome' => 'Governador Edison Lobão']);
		DB::table('cidades')->insert(['id' => 2104602, 'estado_id' => 21, 'nome' => 'Governador Eugênio Barros']);
		DB::table('cidades')->insert(['id' => 2104628, 'estado_id' => 21, 'nome' => 'Governador Luiz Rocha']);
		DB::table('cidades')->insert(['id' => 2104651, 'estado_id' => 21, 'nome' => 'Governador Newton Bello']);
		DB::table('cidades')->insert(['id' => 2104677, 'estado_id' => 21, 'nome' => 'Governador Nunes Freire']);
		DB::table('cidades')->insert(['id' => 2104701, 'estado_id' => 21, 'nome' => 'Graça Aranha']);
		DB::table('cidades')->insert(['id' => 2104800, 'estado_id' => 21, 'nome' => 'Grajaú']);
		DB::table('cidades')->insert(['id' => 2104909, 'estado_id' => 21, 'nome' => 'Guimarães']);
		DB::table('cidades')->insert(['id' => 2105005, 'estado_id' => 21, 'nome' => 'Humberto de Campos']);
		DB::table('cidades')->insert(['id' => 2105104, 'estado_id' => 21, 'nome' => 'Icatu']);
		DB::table('cidades')->insert(['id' => 2105153, 'estado_id' => 21, 'nome' => 'Igarapé do Meio']);
		DB::table('cidades')->insert(['id' => 2105203, 'estado_id' => 21, 'nome' => 'Igarapé Grande']);
		DB::table('cidades')->insert(['id' => 2105302, 'estado_id' => 21, 'nome' => 'Imperatriz']);
		DB::table('cidades')->insert(['id' => 2105351, 'estado_id' => 21, 'nome' => 'Itaipava do Grajaú']);
		DB::table('cidades')->insert(['id' => 2105401, 'estado_id' => 21, 'nome' => 'Itapecuru Mirim']);
		DB::table('cidades')->insert(['id' => 2105427, 'estado_id' => 21, 'nome' => 'Itinga do Maranhão']);
		DB::table('cidades')->insert(['id' => 2105450, 'estado_id' => 21, 'nome' => 'Jatobá']);
		DB::table('cidades')->insert(['id' => 2105476, 'estado_id' => 21, 'nome' => 'Jenipapo dos Vieiras']);
		DB::table('cidades')->insert(['id' => 2105500, 'estado_id' => 21, 'nome' => 'João Lisboa']);
		DB::table('cidades')->insert(['id' => 2105609, 'estado_id' => 21, 'nome' => 'Joselândia']);
		DB::table('cidades')->insert(['id' => 2105658, 'estado_id' => 21, 'nome' => 'Junco do Maranhão']);
		DB::table('cidades')->insert(['id' => 2105708, 'estado_id' => 21, 'nome' => 'Lago da Pedra']);
		DB::table('cidades')->insert(['id' => 2105807, 'estado_id' => 21, 'nome' => 'Lago do Junco']);
		DB::table('cidades')->insert(['id' => 2105906, 'estado_id' => 21, 'nome' => 'Lago Verde']);
		DB::table('cidades')->insert(['id' => 2105922, 'estado_id' => 21, 'nome' => 'Lagoa do Mato']);
		DB::table('cidades')->insert(['id' => 2105948, 'estado_id' => 21, 'nome' => 'Lago dos Rodrigues']);
		DB::table('cidades')->insert(['id' => 2105963, 'estado_id' => 21, 'nome' => 'Lagoa Grande do Maranhão']);
		DB::table('cidades')->insert(['id' => 2105989, 'estado_id' => 21, 'nome' => 'Lajeado Novo']);
		DB::table('cidades')->insert(['id' => 2106003, 'estado_id' => 21, 'nome' => 'Lima Campos']);
		DB::table('cidades')->insert(['id' => 2106102, 'estado_id' => 21, 'nome' => 'Loreto']);
		DB::table('cidades')->insert(['id' => 2106201, 'estado_id' => 21, 'nome' => 'Luís Domingues']);
		DB::table('cidades')->insert(['id' => 2106300, 'estado_id' => 21, 'nome' => 'Magalhães de Almeida']);
		DB::table('cidades')->insert(['id' => 2106326, 'estado_id' => 21, 'nome' => 'Maracaçumé']);
		DB::table('cidades')->insert(['id' => 2106359, 'estado_id' => 21, 'nome' => 'Marajá do Sena']);
		DB::table('cidades')->insert(['id' => 2106375, 'estado_id' => 21, 'nome' => 'Maranhãozinho']);
		DB::table('cidades')->insert(['id' => 2106409, 'estado_id' => 21, 'nome' => 'Mata Roma']);
		DB::table('cidades')->insert(['id' => 2106508, 'estado_id' => 21, 'nome' => 'Matinha']);
		DB::table('cidades')->insert(['id' => 2106607, 'estado_id' => 21, 'nome' => 'Matões']);
		DB::table('cidades')->insert(['id' => 2106631, 'estado_id' => 21, 'nome' => 'Matões do Norte']);
		DB::table('cidades')->insert(['id' => 2106672, 'estado_id' => 21, 'nome' => 'Milagres do Maranhão']);
		DB::table('cidades')->insert(['id' => 2106706, 'estado_id' => 21, 'nome' => 'Mirador']);
		DB::table('cidades')->insert(['id' => 2106755, 'estado_id' => 21, 'nome' => 'Miranda do Norte']);
		DB::table('cidades')->insert(['id' => 2106805, 'estado_id' => 21, 'nome' => 'Mirinzal']);
		DB::table('cidades')->insert(['id' => 2106904, 'estado_id' => 21, 'nome' => 'Monção']);
		DB::table('cidades')->insert(['id' => 2107001, 'estado_id' => 21, 'nome' => 'Montes Altos']);
		DB::table('cidades')->insert(['id' => 2107100, 'estado_id' => 21, 'nome' => 'Morros']);
		DB::table('cidades')->insert(['id' => 2107209, 'estado_id' => 21, 'nome' => 'Nina Rodrigues']);
		DB::table('cidades')->insert(['id' => 2107258, 'estado_id' => 21, 'nome' => 'Nova Colinas']);
		DB::table('cidades')->insert(['id' => 2107308, 'estado_id' => 21, 'nome' => 'Nova Iorque']);
		DB::table('cidades')->insert(['id' => 2107357, 'estado_id' => 21, 'nome' => 'Nova Olinda do Maranhão']);
		DB::table('cidades')->insert(['id' => 2107407, 'estado_id' => 21, 'nome' => 'Olho d\'Água das Cunhãs']);
		DB::table('cidades')->insert(['id' => 2107456, 'estado_id' => 21, 'nome' => 'Olinda Nova do Maranhão']);
		DB::table('cidades')->insert(['id' => 2107506, 'estado_id' => 21, 'nome' => 'Paço do Lumiar']);
		DB::table('cidades')->insert(['id' => 2107605, 'estado_id' => 21, 'nome' => 'Palmeirândia']);
		DB::table('cidades')->insert(['id' => 2107704, 'estado_id' => 21, 'nome' => 'Paraibano']);
		DB::table('cidades')->insert(['id' => 2107803, 'estado_id' => 21, 'nome' => 'Parnarama']);
		DB::table('cidades')->insert(['id' => 2107902, 'estado_id' => 21, 'nome' => 'Passagem Franca']);
		DB::table('cidades')->insert(['id' => 2108009, 'estado_id' => 21, 'nome' => 'Pastos Bons']);
		DB::table('cidades')->insert(['id' => 2108058, 'estado_id' => 21, 'nome' => 'Paulino Neves']);
		DB::table('cidades')->insert(['id' => 2108108, 'estado_id' => 21, 'nome' => 'Paulo Ramos']);
		DB::table('cidades')->insert(['id' => 2108207, 'estado_id' => 21, 'nome' => 'Pedreiras']);
		DB::table('cidades')->insert(['id' => 2108256, 'estado_id' => 21, 'nome' => 'Pedro do Rosário']);
		DB::table('cidades')->insert(['id' => 2108306, 'estado_id' => 21, 'nome' => 'Penalva']);
		DB::table('cidades')->insert(['id' => 2108405, 'estado_id' => 21, 'nome' => 'Peri Mirim']);
		DB::table('cidades')->insert(['id' => 2108454, 'estado_id' => 21, 'nome' => 'Peritoró']);
		DB::table('cidades')->insert(['id' => 2108504, 'estado_id' => 21, 'nome' => 'Pindaré-Mirim']);
		DB::table('cidades')->insert(['id' => 2108603, 'estado_id' => 21, 'nome' => 'Pinheiro']);
		DB::table('cidades')->insert(['id' => 2108702, 'estado_id' => 21, 'nome' => 'Pio XII']);
		DB::table('cidades')->insert(['id' => 2108801, 'estado_id' => 21, 'nome' => 'Pirapemas']);
		DB::table('cidades')->insert(['id' => 2108900, 'estado_id' => 21, 'nome' => 'Poção de Pedras']);
		DB::table('cidades')->insert(['id' => 2109007, 'estado_id' => 21, 'nome' => 'Porto Franco']);
		DB::table('cidades')->insert(['id' => 2109056, 'estado_id' => 21, 'nome' => 'Porto Rico do Maranhão']);
		DB::table('cidades')->insert(['id' => 2109106, 'estado_id' => 21, 'nome' => 'Presidente Dutra']);
		DB::table('cidades')->insert(['id' => 2109205, 'estado_id' => 21, 'nome' => 'Presidente Juscelino']);
		DB::table('cidades')->insert(['id' => 2109239, 'estado_id' => 21, 'nome' => 'Presidente Médici']);
		DB::table('cidades')->insert(['id' => 2109270, 'estado_id' => 21, 'nome' => 'Presidente Sarney']);
		DB::table('cidades')->insert(['id' => 2109304, 'estado_id' => 21, 'nome' => 'Presidente Vargas']);
		DB::table('cidades')->insert(['id' => 2109403, 'estado_id' => 21, 'nome' => 'Primeira Cruz']);
		DB::table('cidades')->insert(['id' => 2109452, 'estado_id' => 21, 'nome' => 'Raposa']);
		DB::table('cidades')->insert(['id' => 2109502, 'estado_id' => 21, 'nome' => 'Riachão']);
		DB::table('cidades')->insert(['id' => 2109551, 'estado_id' => 21, 'nome' => 'Ribamar Fiquene']);
		DB::table('cidades')->insert(['id' => 2109601, 'estado_id' => 21, 'nome' => 'Rosário']);
		DB::table('cidades')->insert(['id' => 2109700, 'estado_id' => 21, 'nome' => 'Sambaíba']);
		DB::table('cidades')->insert(['id' => 2109759, 'estado_id' => 21, 'nome' => 'Santa Filomena do Maranhão']);
		DB::table('cidades')->insert(['id' => 2109809, 'estado_id' => 21, 'nome' => 'Santa Helena']);
		DB::table('cidades')->insert(['id' => 2109908, 'estado_id' => 21, 'nome' => 'Santa Inês']);
		DB::table('cidades')->insert(['id' => 2110005, 'estado_id' => 21, 'nome' => 'Santa Luzia']);
		DB::table('cidades')->insert(['id' => 2110039, 'estado_id' => 21, 'nome' => 'Santa Luzia do Paruá']);
		DB::table('cidades')->insert(['id' => 2110104, 'estado_id' => 21, 'nome' => 'Santa Quitéria do Maranhão']);
		DB::table('cidades')->insert(['id' => 2110203, 'estado_id' => 21, 'nome' => 'Santa Rita']);
		DB::table('cidades')->insert(['id' => 2110237, 'estado_id' => 21, 'nome' => 'Santana do Maranhão']);
		DB::table('cidades')->insert(['id' => 2110278, 'estado_id' => 21, 'nome' => 'Santo Amaro do Maranhão']);
		DB::table('cidades')->insert(['id' => 2110302, 'estado_id' => 21, 'nome' => 'Santo Antônio dos Lopes']);
		DB::table('cidades')->insert(['id' => 2110401, 'estado_id' => 21, 'nome' => 'São Benedito do Rio Preto']);
		DB::table('cidades')->insert(['id' => 2110500, 'estado_id' => 21, 'nome' => 'São Bento']);
		DB::table('cidades')->insert(['id' => 2110609, 'estado_id' => 21, 'nome' => 'São Bernardo']);
		DB::table('cidades')->insert(['id' => 2110658, 'estado_id' => 21, 'nome' => 'São Domingos do Azeitão']);
		DB::table('cidades')->insert(['id' => 2110708, 'estado_id' => 21, 'nome' => 'São Domingos do Maranhão']);
		DB::table('cidades')->insert(['id' => 2110807, 'estado_id' => 21, 'nome' => 'São Félix de Balsas']);
		DB::table('cidades')->insert(['id' => 2110856, 'estado_id' => 21, 'nome' => 'São Francisco do Brejão']);
		DB::table('cidades')->insert(['id' => 2110906, 'estado_id' => 21, 'nome' => 'São Francisco do Maranhão']);
		DB::table('cidades')->insert(['id' => 2111003, 'estado_id' => 21, 'nome' => 'São João Batista']);
		DB::table('cidades')->insert(['id' => 2111029, 'estado_id' => 21, 'nome' => 'São João do Carú']);
		DB::table('cidades')->insert(['id' => 2111052, 'estado_id' => 21, 'nome' => 'São João do Paraíso']);
		DB::table('cidades')->insert(['id' => 2111078, 'estado_id' => 21, 'nome' => 'São João do Soter']);
		DB::table('cidades')->insert(['id' => 2111102, 'estado_id' => 21, 'nome' => 'São João dos Patos']);
		DB::table('cidades')->insert(['id' => 2111201, 'estado_id' => 21, 'nome' => 'São José de Ribamar']);
		DB::table('cidades')->insert(['id' => 2111250, 'estado_id' => 21, 'nome' => 'São José dos Basílios']);
		DB::table('cidades')->insert(['id' => 2111300, 'estado_id' => 21, 'nome' => 'São Luís']);
		DB::table('cidades')->insert(['id' => 2111409, 'estado_id' => 21, 'nome' => 'São Luís Gonzaga do Maranhão']);
		DB::table('cidades')->insert(['id' => 2111508, 'estado_id' => 21, 'nome' => 'São Mateus do Maranhão']);
		DB::table('cidades')->insert(['id' => 2111532, 'estado_id' => 21, 'nome' => 'São Pedro da Água Branca']);
		DB::table('cidades')->insert(['id' => 2111573, 'estado_id' => 21, 'nome' => 'São Pedro dos Crentes']);
		DB::table('cidades')->insert(['id' => 2111607, 'estado_id' => 21, 'nome' => 'São Raimundo das Mangabeiras']);
		DB::table('cidades')->insert(['id' => 2111631, 'estado_id' => 21, 'nome' => 'São Raimundo do Doca Bezerra']);
		DB::table('cidades')->insert(['id' => 2111672, 'estado_id' => 21, 'nome' => 'São Roberto']);
		DB::table('cidades')->insert(['id' => 2111706, 'estado_id' => 21, 'nome' => 'São Vicente Ferrer']);
		DB::table('cidades')->insert(['id' => 2111722, 'estado_id' => 21, 'nome' => 'Satubinha']);
		DB::table('cidades')->insert(['id' => 2111748, 'estado_id' => 21, 'nome' => 'Senador Alexandre Costa']);
		DB::table('cidades')->insert(['id' => 2111763, 'estado_id' => 21, 'nome' => 'Senador La Rocque']);
		DB::table('cidades')->insert(['id' => 2111789, 'estado_id' => 21, 'nome' => 'Serrano do Maranhão']);
		DB::table('cidades')->insert(['id' => 2111805, 'estado_id' => 21, 'nome' => 'Sítio Novo']);
		DB::table('cidades')->insert(['id' => 2111904, 'estado_id' => 21, 'nome' => 'Sucupira do Norte']);
		DB::table('cidades')->insert(['id' => 2111953, 'estado_id' => 21, 'nome' => 'Sucupira do Riachão']);
		DB::table('cidades')->insert(['id' => 2112001, 'estado_id' => 21, 'nome' => 'Tasso Fragoso']);
		DB::table('cidades')->insert(['id' => 2112100, 'estado_id' => 21, 'nome' => 'Timbiras']);
		DB::table('cidades')->insert(['id' => 2112209, 'estado_id' => 21, 'nome' => 'Timon']);
		DB::table('cidades')->insert(['id' => 2112233, 'estado_id' => 21, 'nome' => 'Trizidela do Vale']);
		DB::table('cidades')->insert(['id' => 2112274, 'estado_id' => 21, 'nome' => 'Tufilândia']);
		DB::table('cidades')->insert(['id' => 2112308, 'estado_id' => 21, 'nome' => 'Tuntum']);
		DB::table('cidades')->insert(['id' => 2112407, 'estado_id' => 21, 'nome' => 'Turiaçu']);
		DB::table('cidades')->insert(['id' => 2112456, 'estado_id' => 21, 'nome' => 'Turilândia']);
		DB::table('cidades')->insert(['id' => 2112506, 'estado_id' => 21, 'nome' => 'Tutóia']);
		DB::table('cidades')->insert(['id' => 2112605, 'estado_id' => 21, 'nome' => 'Urbano Santos']);
		DB::table('cidades')->insert(['id' => 2112704, 'estado_id' => 21, 'nome' => 'Vargem Grande']);
		DB::table('cidades')->insert(['id' => 2112803, 'estado_id' => 21, 'nome' => 'Viana']);
		DB::table('cidades')->insert(['id' => 2112852, 'estado_id' => 21, 'nome' => 'Vila Nova dos Martírios']);
		DB::table('cidades')->insert(['id' => 2112902, 'estado_id' => 21, 'nome' => 'Vitória do Mearim']);
		DB::table('cidades')->insert(['id' => 2113009, 'estado_id' => 21, 'nome' => 'Vitorino Freire']);
		DB::table('cidades')->insert(['id' => 2114007, 'estado_id' => 21, 'nome' => 'Zé Doca']);
    }
}
