<?php

use Illuminate\Database\Seeder;

class CidadesTableCESeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades do Ceará
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
		DB::table('cidades')->insert(['id' => 2300101, 'estado_id' => 23, 'nome' => 'Abaiara']);
		DB::table('cidades')->insert(['id' => 2300150, 'estado_id' => 23, 'nome' => 'Acarape']);
		DB::table('cidades')->insert(['id' => 2300200, 'estado_id' => 23, 'nome' => 'Acaraú']);
		DB::table('cidades')->insert(['id' => 2300309, 'estado_id' => 23, 'nome' => 'Acopiara']);
		DB::table('cidades')->insert(['id' => 2300408, 'estado_id' => 23, 'nome' => 'Aiuaba']);
		DB::table('cidades')->insert(['id' => 2300507, 'estado_id' => 23, 'nome' => 'Alcântaras']);
		DB::table('cidades')->insert(['id' => 2300606, 'estado_id' => 23, 'nome' => 'Altaneira']);
		DB::table('cidades')->insert(['id' => 2300705, 'estado_id' => 23, 'nome' => 'Alto Santo']);
		DB::table('cidades')->insert(['id' => 2300754, 'estado_id' => 23, 'nome' => 'Amontada']);
		DB::table('cidades')->insert(['id' => 2300804, 'estado_id' => 23, 'nome' => 'Antonina do Norte']);
		DB::table('cidades')->insert(['id' => 2300903, 'estado_id' => 23, 'nome' => 'Apuiarés']);
		DB::table('cidades')->insert(['id' => 2301000, 'estado_id' => 23, 'nome' => 'Aquiraz']);
		DB::table('cidades')->insert(['id' => 2301109, 'estado_id' => 23, 'nome' => 'Aracati']);
		DB::table('cidades')->insert(['id' => 2301208, 'estado_id' => 23, 'nome' => 'Aracoiaba']);
		DB::table('cidades')->insert(['id' => 2301257, 'estado_id' => 23, 'nome' => 'Ararendá']);
		DB::table('cidades')->insert(['id' => 2301307, 'estado_id' => 23, 'nome' => 'Araripe']);
		DB::table('cidades')->insert(['id' => 2301406, 'estado_id' => 23, 'nome' => 'Aratuba']);
		DB::table('cidades')->insert(['id' => 2301505, 'estado_id' => 23, 'nome' => 'Arneiroz']);
		DB::table('cidades')->insert(['id' => 2301604, 'estado_id' => 23, 'nome' => 'Assaré']);
		DB::table('cidades')->insert(['id' => 2301703, 'estado_id' => 23, 'nome' => 'Aurora']);
		DB::table('cidades')->insert(['id' => 2301802, 'estado_id' => 23, 'nome' => 'Baixio']);
		DB::table('cidades')->insert(['id' => 2301851, 'estado_id' => 23, 'nome' => 'Banabuiú']);
		DB::table('cidades')->insert(['id' => 2301901, 'estado_id' => 23, 'nome' => 'Barbalha']);
		DB::table('cidades')->insert(['id' => 2301950, 'estado_id' => 23, 'nome' => 'Barreira']);
		DB::table('cidades')->insert(['id' => 2302008, 'estado_id' => 23, 'nome' => 'Barro']);
		DB::table('cidades')->insert(['id' => 2302057, 'estado_id' => 23, 'nome' => 'Barroquinha']);
		DB::table('cidades')->insert(['id' => 2302107, 'estado_id' => 23, 'nome' => 'Baturité']);
		DB::table('cidades')->insert(['id' => 2302206, 'estado_id' => 23, 'nome' => 'Beberibe']);
		DB::table('cidades')->insert(['id' => 2302305, 'estado_id' => 23, 'nome' => 'Bela Cruz']);
		DB::table('cidades')->insert(['id' => 2302404, 'estado_id' => 23, 'nome' => 'Boa Viagem']);
		DB::table('cidades')->insert(['id' => 2302503, 'estado_id' => 23, 'nome' => 'Brejo Santo']);
		DB::table('cidades')->insert(['id' => 2302602, 'estado_id' => 23, 'nome' => 'Camocim']);
		DB::table('cidades')->insert(['id' => 2302701, 'estado_id' => 23, 'nome' => 'Campos Sales']);
		DB::table('cidades')->insert(['id' => 2302800, 'estado_id' => 23, 'nome' => 'Canindé']);
		DB::table('cidades')->insert(['id' => 2302909, 'estado_id' => 23, 'nome' => 'Capistrano']);
		DB::table('cidades')->insert(['id' => 2303006, 'estado_id' => 23, 'nome' => 'Caridade']);
		DB::table('cidades')->insert(['id' => 2303105, 'estado_id' => 23, 'nome' => 'Cariré']);
		DB::table('cidades')->insert(['id' => 2303204, 'estado_id' => 23, 'nome' => 'Caririaçu']);
		DB::table('cidades')->insert(['id' => 2303303, 'estado_id' => 23, 'nome' => 'Cariús']);
		DB::table('cidades')->insert(['id' => 2303402, 'estado_id' => 23, 'nome' => 'Carnaubal']);
		DB::table('cidades')->insert(['id' => 2303501, 'estado_id' => 23, 'nome' => 'Cascavel']);
		DB::table('cidades')->insert(['id' => 2303600, 'estado_id' => 23, 'nome' => 'Catarina']);
		DB::table('cidades')->insert(['id' => 2303659, 'estado_id' => 23, 'nome' => 'Catunda']);
		DB::table('cidades')->insert(['id' => 2303709, 'estado_id' => 23, 'nome' => 'Caucaia']);
		DB::table('cidades')->insert(['id' => 2303808, 'estado_id' => 23, 'nome' => 'Cedro']);
		DB::table('cidades')->insert(['id' => 2303907, 'estado_id' => 23, 'nome' => 'Chaval']);
		DB::table('cidades')->insert(['id' => 2303931, 'estado_id' => 23, 'nome' => 'Choró']);
		DB::table('cidades')->insert(['id' => 2303956, 'estado_id' => 23, 'nome' => 'Chorozinho']);
		DB::table('cidades')->insert(['id' => 2304004, 'estado_id' => 23, 'nome' => 'Coreaú']);
		DB::table('cidades')->insert(['id' => 2304103, 'estado_id' => 23, 'nome' => 'Crateús']);
		DB::table('cidades')->insert(['id' => 2304202, 'estado_id' => 23, 'nome' => 'Crato']);
		DB::table('cidades')->insert(['id' => 2304236, 'estado_id' => 23, 'nome' => 'Croatá']);
		DB::table('cidades')->insert(['id' => 2304251, 'estado_id' => 23, 'nome' => 'Cruz']);
		DB::table('cidades')->insert(['id' => 2304269, 'estado_id' => 23, 'nome' => 'Deputado Irapuan Pinheiro']);
		DB::table('cidades')->insert(['id' => 2304277, 'estado_id' => 23, 'nome' => 'Ererê']);
		DB::table('cidades')->insert(['id' => 2304285, 'estado_id' => 23, 'nome' => 'Eusébio']);
		DB::table('cidades')->insert(['id' => 2304301, 'estado_id' => 23, 'nome' => 'Farias Brito']);
		DB::table('cidades')->insert(['id' => 2304350, 'estado_id' => 23, 'nome' => 'Forquilha']);
		DB::table('cidades')->insert(['id' => 2304400, 'estado_id' => 23, 'nome' => 'Fortaleza']);
		DB::table('cidades')->insert(['id' => 2304459, 'estado_id' => 23, 'nome' => 'Fortim']);
		DB::table('cidades')->insert(['id' => 2304509, 'estado_id' => 23, 'nome' => 'Frecheirinha']);
		DB::table('cidades')->insert(['id' => 2304608, 'estado_id' => 23, 'nome' => 'General Sampaio']);
		DB::table('cidades')->insert(['id' => 2304657, 'estado_id' => 23, 'nome' => 'Graça']);
		DB::table('cidades')->insert(['id' => 2304707, 'estado_id' => 23, 'nome' => 'Granja']);
		DB::table('cidades')->insert(['id' => 2304806, 'estado_id' => 23, 'nome' => 'Granjeiro']);
		DB::table('cidades')->insert(['id' => 2304905, 'estado_id' => 23, 'nome' => 'Groaíras']);
		DB::table('cidades')->insert(['id' => 2304954, 'estado_id' => 23, 'nome' => 'Guaiúba']);
		DB::table('cidades')->insert(['id' => 2305001, 'estado_id' => 23, 'nome' => 'Guaraciaba do Norte']);
		DB::table('cidades')->insert(['id' => 2305100, 'estado_id' => 23, 'nome' => 'Guaramiranga']);
		DB::table('cidades')->insert(['id' => 2305209, 'estado_id' => 23, 'nome' => 'Hidrolândia']);
		DB::table('cidades')->insert(['id' => 2305233, 'estado_id' => 23, 'nome' => 'Horizonte']);
		DB::table('cidades')->insert(['id' => 2305266, 'estado_id' => 23, 'nome' => 'Ibaretama']);
		DB::table('cidades')->insert(['id' => 2305308, 'estado_id' => 23, 'nome' => 'Ibiapina']);
		DB::table('cidades')->insert(['id' => 2305332, 'estado_id' => 23, 'nome' => 'Ibicuitinga']);
		DB::table('cidades')->insert(['id' => 2305357, 'estado_id' => 23, 'nome' => 'Icapuí']);
		DB::table('cidades')->insert(['id' => 2305407, 'estado_id' => 23, 'nome' => 'Icó']);
		DB::table('cidades')->insert(['id' => 2305506, 'estado_id' => 23, 'nome' => 'Iguatu']);
		DB::table('cidades')->insert(['id' => 2305605, 'estado_id' => 23, 'nome' => 'Independência']);
		DB::table('cidades')->insert(['id' => 2305654, 'estado_id' => 23, 'nome' => 'Ipaporanga']);
		DB::table('cidades')->insert(['id' => 2305704, 'estado_id' => 23, 'nome' => 'Ipaumirim']);
		DB::table('cidades')->insert(['id' => 2305803, 'estado_id' => 23, 'nome' => 'Ipu']);
		DB::table('cidades')->insert(['id' => 2305902, 'estado_id' => 23, 'nome' => 'Ipueiras']);
		DB::table('cidades')->insert(['id' => 2306009, 'estado_id' => 23, 'nome' => 'Iracema']);
		DB::table('cidades')->insert(['id' => 2306108, 'estado_id' => 23, 'nome' => 'Irauçuba']);
		DB::table('cidades')->insert(['id' => 2306207, 'estado_id' => 23, 'nome' => 'Itaiçaba']);
		DB::table('cidades')->insert(['id' => 2306256, 'estado_id' => 23, 'nome' => 'Itaitinga']);
		DB::table('cidades')->insert(['id' => 2306306, 'estado_id' => 23, 'nome' => 'Itapagé']);
		DB::table('cidades')->insert(['id' => 2306405, 'estado_id' => 23, 'nome' => 'Itapipoca']);
		DB::table('cidades')->insert(['id' => 2306504, 'estado_id' => 23, 'nome' => 'Itapiúna']);
		DB::table('cidades')->insert(['id' => 2306553, 'estado_id' => 23, 'nome' => 'Itarema']);
		DB::table('cidades')->insert(['id' => 2306603, 'estado_id' => 23, 'nome' => 'Itatira']);
		DB::table('cidades')->insert(['id' => 2306702, 'estado_id' => 23, 'nome' => 'Jaguaretama']);
		DB::table('cidades')->insert(['id' => 2306801, 'estado_id' => 23, 'nome' => 'Jaguaribara']);
		DB::table('cidades')->insert(['id' => 2306900, 'estado_id' => 23, 'nome' => 'Jaguaribe']);
		DB::table('cidades')->insert(['id' => 2307007, 'estado_id' => 23, 'nome' => 'Jaguaruana']);
		DB::table('cidades')->insert(['id' => 2307106, 'estado_id' => 23, 'nome' => 'Jardim']);
		DB::table('cidades')->insert(['id' => 2307205, 'estado_id' => 23, 'nome' => 'Jati']);
		DB::table('cidades')->insert(['id' => 2307254, 'estado_id' => 23, 'nome' => 'Jijoca de Jericoacoara']);
		DB::table('cidades')->insert(['id' => 2307304, 'estado_id' => 23, 'nome' => 'Juazeiro do Norte']);
		DB::table('cidades')->insert(['id' => 2307403, 'estado_id' => 23, 'nome' => 'Jucás']);
		DB::table('cidades')->insert(['id' => 2307502, 'estado_id' => 23, 'nome' => 'Lavras da Mangabeira']);
		DB::table('cidades')->insert(['id' => 2307601, 'estado_id' => 23, 'nome' => 'Limoeiro do Norte']);
		DB::table('cidades')->insert(['id' => 2307635, 'estado_id' => 23, 'nome' => 'Madalena']);
		DB::table('cidades')->insert(['id' => 2307650, 'estado_id' => 23, 'nome' => 'Maracanaú']);
		DB::table('cidades')->insert(['id' => 2307700, 'estado_id' => 23, 'nome' => 'Maranguape']);
		DB::table('cidades')->insert(['id' => 2307809, 'estado_id' => 23, 'nome' => 'Marco']);
		DB::table('cidades')->insert(['id' => 2307908, 'estado_id' => 23, 'nome' => 'Martinópole']);
		DB::table('cidades')->insert(['id' => 2308005, 'estado_id' => 23, 'nome' => 'Massapê']);
		DB::table('cidades')->insert(['id' => 2308104, 'estado_id' => 23, 'nome' => 'Mauriti']);
		DB::table('cidades')->insert(['id' => 2308203, 'estado_id' => 23, 'nome' => 'Meruoca']);
		DB::table('cidades')->insert(['id' => 2308302, 'estado_id' => 23, 'nome' => 'Milagres']);
		DB::table('cidades')->insert(['id' => 2308351, 'estado_id' => 23, 'nome' => 'Milhã']);
		DB::table('cidades')->insert(['id' => 2308377, 'estado_id' => 23, 'nome' => 'Miraíma']);
		DB::table('cidades')->insert(['id' => 2308401, 'estado_id' => 23, 'nome' => 'Missão Velha']);
		DB::table('cidades')->insert(['id' => 2308500, 'estado_id' => 23, 'nome' => 'Mombaça']);
		DB::table('cidades')->insert(['id' => 2308609, 'estado_id' => 23, 'nome' => 'Monsenhor Tabosa']);
		DB::table('cidades')->insert(['id' => 2308708, 'estado_id' => 23, 'nome' => 'Morada Nova']);
		DB::table('cidades')->insert(['id' => 2308807, 'estado_id' => 23, 'nome' => 'Moraújo']);
		DB::table('cidades')->insert(['id' => 2308906, 'estado_id' => 23, 'nome' => 'Morrinhos']);
		DB::table('cidades')->insert(['id' => 2309003, 'estado_id' => 23, 'nome' => 'Mucambo']);
		DB::table('cidades')->insert(['id' => 2309102, 'estado_id' => 23, 'nome' => 'Mulungu']);
		DB::table('cidades')->insert(['id' => 2309201, 'estado_id' => 23, 'nome' => 'Nova Olinda']);
		DB::table('cidades')->insert(['id' => 2309300, 'estado_id' => 23, 'nome' => 'Nova Russas']);
		DB::table('cidades')->insert(['id' => 2309409, 'estado_id' => 23, 'nome' => 'Novo Oriente']);
		DB::table('cidades')->insert(['id' => 2309458, 'estado_id' => 23, 'nome' => 'Ocara']);
		DB::table('cidades')->insert(['id' => 2309508, 'estado_id' => 23, 'nome' => 'Orós']);
		DB::table('cidades')->insert(['id' => 2309607, 'estado_id' => 23, 'nome' => 'Pacajus']);
		DB::table('cidades')->insert(['id' => 2309706, 'estado_id' => 23, 'nome' => 'Pacatuba']);
		DB::table('cidades')->insert(['id' => 2309805, 'estado_id' => 23, 'nome' => 'Pacoti']);
		DB::table('cidades')->insert(['id' => 2309904, 'estado_id' => 23, 'nome' => 'Pacujá']);
		DB::table('cidades')->insert(['id' => 2310001, 'estado_id' => 23, 'nome' => 'Palhano']);
		DB::table('cidades')->insert(['id' => 2310100, 'estado_id' => 23, 'nome' => 'Palmácia']);
		DB::table('cidades')->insert(['id' => 2310209, 'estado_id' => 23, 'nome' => 'Paracuru']);
		DB::table('cidades')->insert(['id' => 2310258, 'estado_id' => 23, 'nome' => 'Paraipaba']);
		DB::table('cidades')->insert(['id' => 2310308, 'estado_id' => 23, 'nome' => 'Parambu']);
		DB::table('cidades')->insert(['id' => 2310407, 'estado_id' => 23, 'nome' => 'Paramoti']);
		DB::table('cidades')->insert(['id' => 2310506, 'estado_id' => 23, 'nome' => 'Pedra Branca']);
		DB::table('cidades')->insert(['id' => 2310605, 'estado_id' => 23, 'nome' => 'Penaforte']);
		DB::table('cidades')->insert(['id' => 2310704, 'estado_id' => 23, 'nome' => 'Pentecoste']);
		DB::table('cidades')->insert(['id' => 2310803, 'estado_id' => 23, 'nome' => 'Pereiro']);
		DB::table('cidades')->insert(['id' => 2310852, 'estado_id' => 23, 'nome' => 'Pindoretama']);
		DB::table('cidades')->insert(['id' => 2310902, 'estado_id' => 23, 'nome' => 'Piquet Carneiro']);
		DB::table('cidades')->insert(['id' => 2310951, 'estado_id' => 23, 'nome' => 'Pires Ferreira']);
		DB::table('cidades')->insert(['id' => 2311009, 'estado_id' => 23, 'nome' => 'Poranga']);
		DB::table('cidades')->insert(['id' => 2311108, 'estado_id' => 23, 'nome' => 'Porteiras']);
		DB::table('cidades')->insert(['id' => 2311207, 'estado_id' => 23, 'nome' => 'Potengi']);
		DB::table('cidades')->insert(['id' => 2311231, 'estado_id' => 23, 'nome' => 'Potiretama']);
		DB::table('cidades')->insert(['id' => 2311264, 'estado_id' => 23, 'nome' => 'Quiterianópolis']);
		DB::table('cidades')->insert(['id' => 2311306, 'estado_id' => 23, 'nome' => 'Quixadá']);
		DB::table('cidades')->insert(['id' => 2311355, 'estado_id' => 23, 'nome' => 'Quixelô']);
		DB::table('cidades')->insert(['id' => 2311405, 'estado_id' => 23, 'nome' => 'Quixeramobim']);
		DB::table('cidades')->insert(['id' => 2311504, 'estado_id' => 23, 'nome' => 'Quixeré']);
		DB::table('cidades')->insert(['id' => 2311603, 'estado_id' => 23, 'nome' => 'Redenção']);
		DB::table('cidades')->insert(['id' => 2311702, 'estado_id' => 23, 'nome' => 'Reriutaba']);
		DB::table('cidades')->insert(['id' => 2311801, 'estado_id' => 23, 'nome' => 'Russas']);
		DB::table('cidades')->insert(['id' => 2311900, 'estado_id' => 23, 'nome' => 'Saboeiro']);
		DB::table('cidades')->insert(['id' => 2311959, 'estado_id' => 23, 'nome' => 'Salitre']);
		DB::table('cidades')->insert(['id' => 2312007, 'estado_id' => 23, 'nome' => 'Santana do Acaraú']);
		DB::table('cidades')->insert(['id' => 2312106, 'estado_id' => 23, 'nome' => 'Santana do Cariri']);
		DB::table('cidades')->insert(['id' => 2312205, 'estado_id' => 23, 'nome' => 'Santa Quitéria']);
		DB::table('cidades')->insert(['id' => 2312304, 'estado_id' => 23, 'nome' => 'São Benedito']);
		DB::table('cidades')->insert(['id' => 2312403, 'estado_id' => 23, 'nome' => 'São Gonçalo do Amarante']);
		DB::table('cidades')->insert(['id' => 2312502, 'estado_id' => 23, 'nome' => 'São João do Jaguaribe']);
		DB::table('cidades')->insert(['id' => 2312601, 'estado_id' => 23, 'nome' => 'São Luís do Curu']);
		DB::table('cidades')->insert(['id' => 2312700, 'estado_id' => 23, 'nome' => 'Senador Pompeu']);
		DB::table('cidades')->insert(['id' => 2312809, 'estado_id' => 23, 'nome' => 'Senador Sá']);
		DB::table('cidades')->insert(['id' => 2312908, 'estado_id' => 23, 'nome' => 'Sobral']);
		DB::table('cidades')->insert(['id' => 2313005, 'estado_id' => 23, 'nome' => 'Solonópole']);
		DB::table('cidades')->insert(['id' => 2313104, 'estado_id' => 23, 'nome' => 'Tabuleiro do Norte']);
		DB::table('cidades')->insert(['id' => 2313203, 'estado_id' => 23, 'nome' => 'Tamboril']);
		DB::table('cidades')->insert(['id' => 2313252, 'estado_id' => 23, 'nome' => 'Tarrafas']);
		DB::table('cidades')->insert(['id' => 2313302, 'estado_id' => 23, 'nome' => 'Tauá']);
		DB::table('cidades')->insert(['id' => 2313351, 'estado_id' => 23, 'nome' => 'Tejuçuoca']);
		DB::table('cidades')->insert(['id' => 2313401, 'estado_id' => 23, 'nome' => 'Tianguá']);
		DB::table('cidades')->insert(['id' => 2313500, 'estado_id' => 23, 'nome' => 'Trairi']);
		DB::table('cidades')->insert(['id' => 2313559, 'estado_id' => 23, 'nome' => 'Tururu']);
		DB::table('cidades')->insert(['id' => 2313609, 'estado_id' => 23, 'nome' => 'Ubajara']);
		DB::table('cidades')->insert(['id' => 2313708, 'estado_id' => 23, 'nome' => 'Umari']);
		DB::table('cidades')->insert(['id' => 2313757, 'estado_id' => 23, 'nome' => 'Umirim']);
		DB::table('cidades')->insert(['id' => 2313807, 'estado_id' => 23, 'nome' => 'Uruburetama']);
		DB::table('cidades')->insert(['id' => 2313906, 'estado_id' => 23, 'nome' => 'Uruoca']);
		DB::table('cidades')->insert(['id' => 2313955, 'estado_id' => 23, 'nome' => 'Varjota']);
		DB::table('cidades')->insert(['id' => 2314003, 'estado_id' => 23, 'nome' => 'Várzea Alegre']);
		DB::table('cidades')->insert(['id' => 2314102, 'estado_id' => 23, 'nome' => 'Viçosa do Ceará']);
    }
}
