<?php

use Illuminate\Database\Seeder;

class CidadesTableRSSeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades do Rio Grande do Sul
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 4300034, 'estado_id' => 43, 'nome' => 'Aceguá']);
		DB::table('cidades')->insert(['id' => 4300059, 'estado_id' => 43, 'nome' => 'Água Santa']);
		DB::table('cidades')->insert(['id' => 4300109, 'estado_id' => 43, 'nome' => 'Agudo']);
		DB::table('cidades')->insert(['id' => 4300208, 'estado_id' => 43, 'nome' => 'Ajuricaba']);
		DB::table('cidades')->insert(['id' => 4300307, 'estado_id' => 43, 'nome' => 'Alecrim']);
		DB::table('cidades')->insert(['id' => 4300406, 'estado_id' => 43, 'nome' => 'Alegrete']);
		DB::table('cidades')->insert(['id' => 4300455, 'estado_id' => 43, 'nome' => 'Alegria']);
		DB::table('cidades')->insert(['id' => 4300471, 'estado_id' => 43, 'nome' => 'Almirante Tamandaré do Sul']);
		DB::table('cidades')->insert(['id' => 4300505, 'estado_id' => 43, 'nome' => 'Alpestre']);
		DB::table('cidades')->insert(['id' => 4300554, 'estado_id' => 43, 'nome' => 'Alto Alegre']);
		DB::table('cidades')->insert(['id' => 4300570, 'estado_id' => 43, 'nome' => 'Alto Feliz']);
		DB::table('cidades')->insert(['id' => 4300604, 'estado_id' => 43, 'nome' => 'Alvorada']);
		DB::table('cidades')->insert(['id' => 4300638, 'estado_id' => 43, 'nome' => 'Amaral Ferrador']);
		DB::table('cidades')->insert(['id' => 4300646, 'estado_id' => 43, 'nome' => 'Ametista do Sul']);
		DB::table('cidades')->insert(['id' => 4300661, 'estado_id' => 43, 'nome' => 'André da Rocha']);
		DB::table('cidades')->insert(['id' => 4300703, 'estado_id' => 43, 'nome' => 'Anta Gorda']);
		DB::table('cidades')->insert(['id' => 4300802, 'estado_id' => 43, 'nome' => 'Antônio Prado']);
		DB::table('cidades')->insert(['id' => 4300851, 'estado_id' => 43, 'nome' => 'Arambaré']);
		DB::table('cidades')->insert(['id' => 4300877, 'estado_id' => 43, 'nome' => 'Araricá']);
		DB::table('cidades')->insert(['id' => 4300901, 'estado_id' => 43, 'nome' => 'Aratiba']);
		DB::table('cidades')->insert(['id' => 4301008, 'estado_id' => 43, 'nome' => 'Arroio do Meio']);
		DB::table('cidades')->insert(['id' => 4301057, 'estado_id' => 43, 'nome' => 'Arroio do Sal']);
		DB::table('cidades')->insert(['id' => 4301073, 'estado_id' => 43, 'nome' => 'Arroio do Padre']);
		DB::table('cidades')->insert(['id' => 4301107, 'estado_id' => 43, 'nome' => 'Arroio dos Ratos']);
		DB::table('cidades')->insert(['id' => 4301206, 'estado_id' => 43, 'nome' => 'Arroio do Tigre']);
		DB::table('cidades')->insert(['id' => 4301305, 'estado_id' => 43, 'nome' => 'Arroio Grande']);
		DB::table('cidades')->insert(['id' => 4301404, 'estado_id' => 43, 'nome' => 'Arvorezinha']);
		DB::table('cidades')->insert(['id' => 4301503, 'estado_id' => 43, 'nome' => 'Augusto Pestana']);
		DB::table('cidades')->insert(['id' => 4301552, 'estado_id' => 43, 'nome' => 'Áurea']);
		DB::table('cidades')->insert(['id' => 4301602, 'estado_id' => 43, 'nome' => 'Bagé']);
		DB::table('cidades')->insert(['id' => 4301636, 'estado_id' => 43, 'nome' => 'Balneário Pinhal']);
		DB::table('cidades')->insert(['id' => 4301651, 'estado_id' => 43, 'nome' => 'Barão']);
		DB::table('cidades')->insert(['id' => 4301701, 'estado_id' => 43, 'nome' => 'Barão de Cotegipe']);
		DB::table('cidades')->insert(['id' => 4301750, 'estado_id' => 43, 'nome' => 'Barão do Triunfo']);
		DB::table('cidades')->insert(['id' => 4301800, 'estado_id' => 43, 'nome' => 'Barracão']);
		DB::table('cidades')->insert(['id' => 4301859, 'estado_id' => 43, 'nome' => 'Barra do Guarita']);
		DB::table('cidades')->insert(['id' => 4301875, 'estado_id' => 43, 'nome' => 'Barra do Quaraí']);
		DB::table('cidades')->insert(['id' => 4301909, 'estado_id' => 43, 'nome' => 'Barra do Ribeiro']);
		DB::table('cidades')->insert(['id' => 4301925, 'estado_id' => 43, 'nome' => 'Barra do Rio Azul']);
		DB::table('cidades')->insert(['id' => 4301958, 'estado_id' => 43, 'nome' => 'Barra Funda']);
		DB::table('cidades')->insert(['id' => 4302006, 'estado_id' => 43, 'nome' => 'Barros Cassal']);
		DB::table('cidades')->insert(['id' => 4302055, 'estado_id' => 43, 'nome' => 'Benjamin Constant do Sul']);
		DB::table('cidades')->insert(['id' => 4302105, 'estado_id' => 43, 'nome' => 'Bento Gonçalves']);
		DB::table('cidades')->insert(['id' => 4302154, 'estado_id' => 43, 'nome' => 'Boa Vista das Missões']);
		DB::table('cidades')->insert(['id' => 4302204, 'estado_id' => 43, 'nome' => 'Boa Vista do Buricá']);
		DB::table('cidades')->insert(['id' => 4302220, 'estado_id' => 43, 'nome' => 'Boa Vista do Cadeado']);
		DB::table('cidades')->insert(['id' => 4302238, 'estado_id' => 43, 'nome' => 'Boa Vista do Incra']);
		DB::table('cidades')->insert(['id' => 4302253, 'estado_id' => 43, 'nome' => 'Boa Vista do Sul']);
		DB::table('cidades')->insert(['id' => 4302303, 'estado_id' => 43, 'nome' => 'Bom Jesus']);
		DB::table('cidades')->insert(['id' => 4302352, 'estado_id' => 43, 'nome' => 'Bom Princípio']);
		DB::table('cidades')->insert(['id' => 4302378, 'estado_id' => 43, 'nome' => 'Bom Progresso']);
		DB::table('cidades')->insert(['id' => 4302402, 'estado_id' => 43, 'nome' => 'Bom Retiro do Sul']);
		DB::table('cidades')->insert(['id' => 4302451, 'estado_id' => 43, 'nome' => 'Boqueirão do Leão']);
		DB::table('cidades')->insert(['id' => 4302501, 'estado_id' => 43, 'nome' => 'Bossoroca']);
		DB::table('cidades')->insert(['id' => 4302584, 'estado_id' => 43, 'nome' => 'Bozano']);
		DB::table('cidades')->insert(['id' => 4302600, 'estado_id' => 43, 'nome' => 'Braga']);
		DB::table('cidades')->insert(['id' => 4302659, 'estado_id' => 43, 'nome' => 'Brochier']);
		DB::table('cidades')->insert(['id' => 4302709, 'estado_id' => 43, 'nome' => 'Butiá']);
		DB::table('cidades')->insert(['id' => 4302808, 'estado_id' => 43, 'nome' => 'Caçapava do Sul']);
		DB::table('cidades')->insert(['id' => 4302907, 'estado_id' => 43, 'nome' => 'Cacequi']);
		DB::table('cidades')->insert(['id' => 4303004, 'estado_id' => 43, 'nome' => 'Cachoeira do Sul']);
		DB::table('cidades')->insert(['id' => 4303103, 'estado_id' => 43, 'nome' => 'Cachoeirinha']);
		DB::table('cidades')->insert(['id' => 4303202, 'estado_id' => 43, 'nome' => 'Cacique Doble']);
		DB::table('cidades')->insert(['id' => 4303301, 'estado_id' => 43, 'nome' => 'Caibaté']);
		DB::table('cidades')->insert(['id' => 4303400, 'estado_id' => 43, 'nome' => 'Caiçara']);
		DB::table('cidades')->insert(['id' => 4303509, 'estado_id' => 43, 'nome' => 'Camaquã']);
		DB::table('cidades')->insert(['id' => 4303558, 'estado_id' => 43, 'nome' => 'Camargo']);
		DB::table('cidades')->insert(['id' => 4303608, 'estado_id' => 43, 'nome' => 'Cambará do Sul']);
		DB::table('cidades')->insert(['id' => 4303673, 'estado_id' => 43, 'nome' => 'Campestre da Serra']);
		DB::table('cidades')->insert(['id' => 4303707, 'estado_id' => 43, 'nome' => 'Campina das Missões']);
		DB::table('cidades')->insert(['id' => 4303806, 'estado_id' => 43, 'nome' => 'Campinas do Sul']);
		DB::table('cidades')->insert(['id' => 4303905, 'estado_id' => 43, 'nome' => 'Campo Bom']);
		DB::table('cidades')->insert(['id' => 4304002, 'estado_id' => 43, 'nome' => 'Campo Novo']);
		DB::table('cidades')->insert(['id' => 4304101, 'estado_id' => 43, 'nome' => 'Campos Borges']);
		DB::table('cidades')->insert(['id' => 4304200, 'estado_id' => 43, 'nome' => 'Candelária']);
		DB::table('cidades')->insert(['id' => 4304309, 'estado_id' => 43, 'nome' => 'Cândido Godói']);
		DB::table('cidades')->insert(['id' => 4304358, 'estado_id' => 43, 'nome' => 'Candiota']);
		DB::table('cidades')->insert(['id' => 4304408, 'estado_id' => 43, 'nome' => 'Canela']);
		DB::table('cidades')->insert(['id' => 4304507, 'estado_id' => 43, 'nome' => 'Canguçu']);
		DB::table('cidades')->insert(['id' => 4304606, 'estado_id' => 43, 'nome' => 'Canoas']);
		DB::table('cidades')->insert(['id' => 4304614, 'estado_id' => 43, 'nome' => 'Canudos do Vale']);
		DB::table('cidades')->insert(['id' => 4304622, 'estado_id' => 43, 'nome' => 'Capão Bonito do Sul']);
		DB::table('cidades')->insert(['id' => 4304630, 'estado_id' => 43, 'nome' => 'Capão da Canoa']);
		DB::table('cidades')->insert(['id' => 4304655, 'estado_id' => 43, 'nome' => 'Capão do Cipó']);
		DB::table('cidades')->insert(['id' => 4304663, 'estado_id' => 43, 'nome' => 'Capão do Leão']);
		DB::table('cidades')->insert(['id' => 4304671, 'estado_id' => 43, 'nome' => 'Capivari do Sul']);
		DB::table('cidades')->insert(['id' => 4304689, 'estado_id' => 43, 'nome' => 'Capela de Santana']);
		DB::table('cidades')->insert(['id' => 4304697, 'estado_id' => 43, 'nome' => 'Capitão']);
		DB::table('cidades')->insert(['id' => 4304705, 'estado_id' => 43, 'nome' => 'Carazinho']);
		DB::table('cidades')->insert(['id' => 4304713, 'estado_id' => 43, 'nome' => 'Caraá']);
		DB::table('cidades')->insert(['id' => 4304804, 'estado_id' => 43, 'nome' => 'Carlos Barbosa']);
		DB::table('cidades')->insert(['id' => 4304853, 'estado_id' => 43, 'nome' => 'Carlos Gomes']);
		DB::table('cidades')->insert(['id' => 4304903, 'estado_id' => 43, 'nome' => 'Casca']);
		DB::table('cidades')->insert(['id' => 4304952, 'estado_id' => 43, 'nome' => 'Caseiros']);
		DB::table('cidades')->insert(['id' => 4305009, 'estado_id' => 43, 'nome' => 'Catuípe']);
		DB::table('cidades')->insert(['id' => 4305108, 'estado_id' => 43, 'nome' => 'Caxias do Sul']);
		DB::table('cidades')->insert(['id' => 4305116, 'estado_id' => 43, 'nome' => 'Centenário']);
		DB::table('cidades')->insert(['id' => 4305124, 'estado_id' => 43, 'nome' => 'Cerrito']);
		DB::table('cidades')->insert(['id' => 4305132, 'estado_id' => 43, 'nome' => 'Cerro Branco']);
		DB::table('cidades')->insert(['id' => 4305157, 'estado_id' => 43, 'nome' => 'Cerro Grande']);
		DB::table('cidades')->insert(['id' => 4305173, 'estado_id' => 43, 'nome' => 'Cerro Grande do Sul']);
		DB::table('cidades')->insert(['id' => 4305207, 'estado_id' => 43, 'nome' => 'Cerro Largo']);
		DB::table('cidades')->insert(['id' => 4305306, 'estado_id' => 43, 'nome' => 'Chapada']);
		DB::table('cidades')->insert(['id' => 4305355, 'estado_id' => 43, 'nome' => 'Charqueadas']);
		DB::table('cidades')->insert(['id' => 4305371, 'estado_id' => 43, 'nome' => 'Charrua']);
		DB::table('cidades')->insert(['id' => 4305405, 'estado_id' => 43, 'nome' => 'Chiapetta']);
		DB::table('cidades')->insert(['id' => 4305439, 'estado_id' => 43, 'nome' => 'Chuí']);
		DB::table('cidades')->insert(['id' => 4305447, 'estado_id' => 43, 'nome' => 'Chuvisca']);
		DB::table('cidades')->insert(['id' => 4305454, 'estado_id' => 43, 'nome' => 'Cidreira']);
		DB::table('cidades')->insert(['id' => 4305504, 'estado_id' => 43, 'nome' => 'Ciríaco']);
		DB::table('cidades')->insert(['id' => 4305587, 'estado_id' => 43, 'nome' => 'Colinas']);
		DB::table('cidades')->insert(['id' => 4305603, 'estado_id' => 43, 'nome' => 'Colorado']);
		DB::table('cidades')->insert(['id' => 4305702, 'estado_id' => 43, 'nome' => 'Condor']);
		DB::table('cidades')->insert(['id' => 4305801, 'estado_id' => 43, 'nome' => 'Constantina']);
		DB::table('cidades')->insert(['id' => 4305835, 'estado_id' => 43, 'nome' => 'Coqueiro Baixo']);
		DB::table('cidades')->insert(['id' => 4305850, 'estado_id' => 43, 'nome' => 'Coqueiros do Sul']);
		DB::table('cidades')->insert(['id' => 4305871, 'estado_id' => 43, 'nome' => 'Coronel Barros']);
		DB::table('cidades')->insert(['id' => 4305900, 'estado_id' => 43, 'nome' => 'Coronel Bicaco']);
		DB::table('cidades')->insert(['id' => 4305934, 'estado_id' => 43, 'nome' => 'Coronel Pilar']);
		DB::table('cidades')->insert(['id' => 4305959, 'estado_id' => 43, 'nome' => 'Cotiporã']);
		DB::table('cidades')->insert(['id' => 4305975, 'estado_id' => 43, 'nome' => 'Coxilha']);
		DB::table('cidades')->insert(['id' => 4306007, 'estado_id' => 43, 'nome' => 'Crissiumal']);
		DB::table('cidades')->insert(['id' => 4306056, 'estado_id' => 43, 'nome' => 'Cristal']);
		DB::table('cidades')->insert(['id' => 4306072, 'estado_id' => 43, 'nome' => 'Cristal do Sul']);
		DB::table('cidades')->insert(['id' => 4306106, 'estado_id' => 43, 'nome' => 'Cruz Alta']);
		DB::table('cidades')->insert(['id' => 4306130, 'estado_id' => 43, 'nome' => 'Cruzaltense']);
		DB::table('cidades')->insert(['id' => 4306205, 'estado_id' => 43, 'nome' => 'Cruzeiro do Sul']);
		DB::table('cidades')->insert(['id' => 4306304, 'estado_id' => 43, 'nome' => 'David Canabarro']);
		DB::table('cidades')->insert(['id' => 4306320, 'estado_id' => 43, 'nome' => 'Derrubadas']);
		DB::table('cidades')->insert(['id' => 4306353, 'estado_id' => 43, 'nome' => 'Dezesseis de Novembro']);
		DB::table('cidades')->insert(['id' => 4306379, 'estado_id' => 43, 'nome' => 'Dilermando de Aguiar']);
		DB::table('cidades')->insert(['id' => 4306403, 'estado_id' => 43, 'nome' => 'Dois Irmãos']);
		DB::table('cidades')->insert(['id' => 4306429, 'estado_id' => 43, 'nome' => 'Dois Irmãos das Missões']);
		DB::table('cidades')->insert(['id' => 4306452, 'estado_id' => 43, 'nome' => 'Dois Lajeados']);
		DB::table('cidades')->insert(['id' => 4306502, 'estado_id' => 43, 'nome' => 'Dom Feliciano']);
		DB::table('cidades')->insert(['id' => 4306551, 'estado_id' => 43, 'nome' => 'Dom Pedro de Alcântara']);
		DB::table('cidades')->insert(['id' => 4306601, 'estado_id' => 43, 'nome' => 'Dom Pedrito']);
		DB::table('cidades')->insert(['id' => 4306700, 'estado_id' => 43, 'nome' => 'Dona Francisca']);
		DB::table('cidades')->insert(['id' => 4306734, 'estado_id' => 43, 'nome' => 'Doutor Maurício Cardoso']);
		DB::table('cidades')->insert(['id' => 4306759, 'estado_id' => 43, 'nome' => 'Doutor Ricardo']);
		DB::table('cidades')->insert(['id' => 4306767, 'estado_id' => 43, 'nome' => 'Eldorado do Sul']);
		DB::table('cidades')->insert(['id' => 4306809, 'estado_id' => 43, 'nome' => 'Encantado']);
		DB::table('cidades')->insert(['id' => 4306908, 'estado_id' => 43, 'nome' => 'Encruzilhada do Sul']);
		DB::table('cidades')->insert(['id' => 4306924, 'estado_id' => 43, 'nome' => 'Engenho Velho']);
		DB::table('cidades')->insert(['id' => 4306932, 'estado_id' => 43, 'nome' => 'Entre-Ijuís']);
		DB::table('cidades')->insert(['id' => 4306957, 'estado_id' => 43, 'nome' => 'Entre Rios do Sul']);
		DB::table('cidades')->insert(['id' => 4306973, 'estado_id' => 43, 'nome' => 'Erebango']);
		DB::table('cidades')->insert(['id' => 4307005, 'estado_id' => 43, 'nome' => 'Erechim']);
		DB::table('cidades')->insert(['id' => 4307054, 'estado_id' => 43, 'nome' => 'Ernestina']);
		DB::table('cidades')->insert(['id' => 4307104, 'estado_id' => 43, 'nome' => 'Herval']);
		DB::table('cidades')->insert(['id' => 4307203, 'estado_id' => 43, 'nome' => 'Erval Grande']);
		DB::table('cidades')->insert(['id' => 4307302, 'estado_id' => 43, 'nome' => 'Erval Seco']);
		DB::table('cidades')->insert(['id' => 4307401, 'estado_id' => 43, 'nome' => 'Esmeralda']);
		DB::table('cidades')->insert(['id' => 4307450, 'estado_id' => 43, 'nome' => 'Esperança do Sul']);
		DB::table('cidades')->insert(['id' => 4307500, 'estado_id' => 43, 'nome' => 'Espumoso']);
		DB::table('cidades')->insert(['id' => 4307559, 'estado_id' => 43, 'nome' => 'Estação']);
		DB::table('cidades')->insert(['id' => 4307609, 'estado_id' => 43, 'nome' => 'Estância Velha']);
		DB::table('cidades')->insert(['id' => 4307708, 'estado_id' => 43, 'nome' => 'Esteio']);
		DB::table('cidades')->insert(['id' => 4307807, 'estado_id' => 43, 'nome' => 'Estrela']);
		DB::table('cidades')->insert(['id' => 4307815, 'estado_id' => 43, 'nome' => 'Estrela Velha']);
		DB::table('cidades')->insert(['id' => 4307831, 'estado_id' => 43, 'nome' => 'Eugênio de Castro']);
		DB::table('cidades')->insert(['id' => 4307864, 'estado_id' => 43, 'nome' => 'Fagundes Varela']);
		DB::table('cidades')->insert(['id' => 4307906, 'estado_id' => 43, 'nome' => 'Farroupilha']);
		DB::table('cidades')->insert(['id' => 4308003, 'estado_id' => 43, 'nome' => 'Faxinal do Soturno']);
		DB::table('cidades')->insert(['id' => 4308052, 'estado_id' => 43, 'nome' => 'Faxinalzinho']);
		DB::table('cidades')->insert(['id' => 4308078, 'estado_id' => 43, 'nome' => 'Fazenda Vilanova']);
		DB::table('cidades')->insert(['id' => 4308102, 'estado_id' => 43, 'nome' => 'Feliz']);
		DB::table('cidades')->insert(['id' => 4308201, 'estado_id' => 43, 'nome' => 'Flores da Cunha']);
		DB::table('cidades')->insert(['id' => 4308250, 'estado_id' => 43, 'nome' => 'Floriano Peixoto']);
		DB::table('cidades')->insert(['id' => 4308300, 'estado_id' => 43, 'nome' => 'Fontoura Xavier']);
		DB::table('cidades')->insert(['id' => 4308409, 'estado_id' => 43, 'nome' => 'Formigueiro']);
		DB::table('cidades')->insert(['id' => 4308433, 'estado_id' => 43, 'nome' => 'Forquetinha']);
		DB::table('cidades')->insert(['id' => 4308458, 'estado_id' => 43, 'nome' => 'Fortaleza dos Valos']);
		DB::table('cidades')->insert(['id' => 4308508, 'estado_id' => 43, 'nome' => 'Frederico Westphalen']);
		DB::table('cidades')->insert(['id' => 4308607, 'estado_id' => 43, 'nome' => 'Garibaldi']);
		DB::table('cidades')->insert(['id' => 4308656, 'estado_id' => 43, 'nome' => 'Garruchos']);
		DB::table('cidades')->insert(['id' => 4308706, 'estado_id' => 43, 'nome' => 'Gaurama']);
		DB::table('cidades')->insert(['id' => 4308805, 'estado_id' => 43, 'nome' => 'General Câmara']);
		DB::table('cidades')->insert(['id' => 4308854, 'estado_id' => 43, 'nome' => 'Gentil']);
		DB::table('cidades')->insert(['id' => 4308904, 'estado_id' => 43, 'nome' => 'Getúlio Vargas']);
		DB::table('cidades')->insert(['id' => 4309001, 'estado_id' => 43, 'nome' => 'Giruá']);
		DB::table('cidades')->insert(['id' => 4309050, 'estado_id' => 43, 'nome' => 'Glorinha']);
		DB::table('cidades')->insert(['id' => 4309100, 'estado_id' => 43, 'nome' => 'Gramado']);
		DB::table('cidades')->insert(['id' => 4309126, 'estado_id' => 43, 'nome' => 'Gramado dos Loureiros']);
		DB::table('cidades')->insert(['id' => 4309159, 'estado_id' => 43, 'nome' => 'Gramado Xavier']);
		DB::table('cidades')->insert(['id' => 4309209, 'estado_id' => 43, 'nome' => 'Gravataí']);
		DB::table('cidades')->insert(['id' => 4309258, 'estado_id' => 43, 'nome' => 'Guabiju']);
		DB::table('cidades')->insert(['id' => 4309308, 'estado_id' => 43, 'nome' => 'Guaíba']);
		DB::table('cidades')->insert(['id' => 4309407, 'estado_id' => 43, 'nome' => 'Guaporé']);
		DB::table('cidades')->insert(['id' => 4309506, 'estado_id' => 43, 'nome' => 'Guarani das Missões']);
		DB::table('cidades')->insert(['id' => 4309555, 'estado_id' => 43, 'nome' => 'Harmonia']);
		DB::table('cidades')->insert(['id' => 4309571, 'estado_id' => 43, 'nome' => 'Herveiras']);
		DB::table('cidades')->insert(['id' => 4309605, 'estado_id' => 43, 'nome' => 'Horizontina']);
		DB::table('cidades')->insert(['id' => 4309654, 'estado_id' => 43, 'nome' => 'Hulha Negra']);
		DB::table('cidades')->insert(['id' => 4309704, 'estado_id' => 43, 'nome' => 'Humaitá']);
		DB::table('cidades')->insert(['id' => 4309753, 'estado_id' => 43, 'nome' => 'Ibarama']);
		DB::table('cidades')->insert(['id' => 4309803, 'estado_id' => 43, 'nome' => 'Ibiaçá']);
		DB::table('cidades')->insert(['id' => 4309902, 'estado_id' => 43, 'nome' => 'Ibiraiaras']);
		DB::table('cidades')->insert(['id' => 4309951, 'estado_id' => 43, 'nome' => 'Ibirapuitã']);
		DB::table('cidades')->insert(['id' => 4310009, 'estado_id' => 43, 'nome' => 'Ibirubá']);
		DB::table('cidades')->insert(['id' => 4310108, 'estado_id' => 43, 'nome' => 'Igrejinha']);
		DB::table('cidades')->insert(['id' => 4310207, 'estado_id' => 43, 'nome' => 'Ijuí']);
		DB::table('cidades')->insert(['id' => 4310306, 'estado_id' => 43, 'nome' => 'Ilópolis']);
		DB::table('cidades')->insert(['id' => 4310330, 'estado_id' => 43, 'nome' => 'Imbé']);
		DB::table('cidades')->insert(['id' => 4310363, 'estado_id' => 43, 'nome' => 'Imigrante']);
		DB::table('cidades')->insert(['id' => 4310405, 'estado_id' => 43, 'nome' => 'Independência']);
		DB::table('cidades')->insert(['id' => 4310413, 'estado_id' => 43, 'nome' => 'Inhacorá']);
		DB::table('cidades')->insert(['id' => 4310439, 'estado_id' => 43, 'nome' => 'Ipê']);
		DB::table('cidades')->insert(['id' => 4310462, 'estado_id' => 43, 'nome' => 'Ipiranga do Sul']);
		DB::table('cidades')->insert(['id' => 4310504, 'estado_id' => 43, 'nome' => 'Iraí']);
		DB::table('cidades')->insert(['id' => 4310538, 'estado_id' => 43, 'nome' => 'Itaara']);
		DB::table('cidades')->insert(['id' => 4310553, 'estado_id' => 43, 'nome' => 'Itacurubi']);
		DB::table('cidades')->insert(['id' => 4310579, 'estado_id' => 43, 'nome' => 'Itapuca']);
		DB::table('cidades')->insert(['id' => 4310603, 'estado_id' => 43, 'nome' => 'Itaqui']);
		DB::table('cidades')->insert(['id' => 4310652, 'estado_id' => 43, 'nome' => 'Itati']);
		DB::table('cidades')->insert(['id' => 4310702, 'estado_id' => 43, 'nome' => 'Itatiba do Sul']);
		DB::table('cidades')->insert(['id' => 4310751, 'estado_id' => 43, 'nome' => 'Ivorá']);
		DB::table('cidades')->insert(['id' => 4310801, 'estado_id' => 43, 'nome' => 'Ivoti']);
		DB::table('cidades')->insert(['id' => 4310850, 'estado_id' => 43, 'nome' => 'Jaboticaba']);
		DB::table('cidades')->insert(['id' => 4310876, 'estado_id' => 43, 'nome' => 'Jacuizinho']);
		DB::table('cidades')->insert(['id' => 4310900, 'estado_id' => 43, 'nome' => 'Jacutinga']);
		DB::table('cidades')->insert(['id' => 4311007, 'estado_id' => 43, 'nome' => 'Jaguarão']);
		DB::table('cidades')->insert(['id' => 4311106, 'estado_id' => 43, 'nome' => 'Jaguari']);
		DB::table('cidades')->insert(['id' => 4311122, 'estado_id' => 43, 'nome' => 'Jaquirana']);
		DB::table('cidades')->insert(['id' => 4311130, 'estado_id' => 43, 'nome' => 'Jari']);
		DB::table('cidades')->insert(['id' => 4311155, 'estado_id' => 43, 'nome' => 'Jóia']);
		DB::table('cidades')->insert(['id' => 4311205, 'estado_id' => 43, 'nome' => 'Júlio de Castilhos']);
		DB::table('cidades')->insert(['id' => 4311239, 'estado_id' => 43, 'nome' => 'Lagoa Bonita do Sul']);
		DB::table('cidades')->insert(['id' => 4311254, 'estado_id' => 43, 'nome' => 'Lagoão']);
		DB::table('cidades')->insert(['id' => 4311270, 'estado_id' => 43, 'nome' => 'Lagoa dos Três Cantos']);
		DB::table('cidades')->insert(['id' => 4311304, 'estado_id' => 43, 'nome' => 'Lagoa Vermelha']);
		DB::table('cidades')->insert(['id' => 4311403, 'estado_id' => 43, 'nome' => 'Lajeado']);
		DB::table('cidades')->insert(['id' => 4311429, 'estado_id' => 43, 'nome' => 'Lajeado do Bugre']);
		DB::table('cidades')->insert(['id' => 4311502, 'estado_id' => 43, 'nome' => 'Lavras do Sul']);
		DB::table('cidades')->insert(['id' => 4311601, 'estado_id' => 43, 'nome' => 'Liberato Salzano']);
		DB::table('cidades')->insert(['id' => 4311627, 'estado_id' => 43, 'nome' => 'Lindolfo Collor']);
		DB::table('cidades')->insert(['id' => 4311643, 'estado_id' => 43, 'nome' => 'Linha Nova']);
		DB::table('cidades')->insert(['id' => 4311700, 'estado_id' => 43, 'nome' => 'Machadinho']);
		DB::table('cidades')->insert(['id' => 4311718, 'estado_id' => 43, 'nome' => 'Maçambara']);
		DB::table('cidades')->insert(['id' => 4311734, 'estado_id' => 43, 'nome' => 'Mampituba']);
		DB::table('cidades')->insert(['id' => 4311759, 'estado_id' => 43, 'nome' => 'Manoel Viana']);
		DB::table('cidades')->insert(['id' => 4311775, 'estado_id' => 43, 'nome' => 'Maquiné']);
		DB::table('cidades')->insert(['id' => 4311791, 'estado_id' => 43, 'nome' => 'Maratá']);
		DB::table('cidades')->insert(['id' => 4311809, 'estado_id' => 43, 'nome' => 'Marau']);
		DB::table('cidades')->insert(['id' => 4311908, 'estado_id' => 43, 'nome' => 'Marcelino Ramos']);
		DB::table('cidades')->insert(['id' => 4311981, 'estado_id' => 43, 'nome' => 'Mariana Pimentel']);
		DB::table('cidades')->insert(['id' => 4312005, 'estado_id' => 43, 'nome' => 'Mariano Moro']);
		DB::table('cidades')->insert(['id' => 4312054, 'estado_id' => 43, 'nome' => 'Marques de Souza']);
		DB::table('cidades')->insert(['id' => 4312104, 'estado_id' => 43, 'nome' => 'Mata']);
		DB::table('cidades')->insert(['id' => 4312138, 'estado_id' => 43, 'nome' => 'Mato Castelhano']);
		DB::table('cidades')->insert(['id' => 4312153, 'estado_id' => 43, 'nome' => 'Mato Leitão']);
		DB::table('cidades')->insert(['id' => 4312179, 'estado_id' => 43, 'nome' => 'Mato Queimado']);
		DB::table('cidades')->insert(['id' => 4312203, 'estado_id' => 43, 'nome' => 'Maximiliano de Almeida']);
		DB::table('cidades')->insert(['id' => 4312252, 'estado_id' => 43, 'nome' => 'Minas do Leão']);
		DB::table('cidades')->insert(['id' => 4312302, 'estado_id' => 43, 'nome' => 'Miraguaí']);
		DB::table('cidades')->insert(['id' => 4312351, 'estado_id' => 43, 'nome' => 'Montauri']);
		DB::table('cidades')->insert(['id' => 4312377, 'estado_id' => 43, 'nome' => 'Monte Alegre dos Campos']);
		DB::table('cidades')->insert(['id' => 4312385, 'estado_id' => 43, 'nome' => 'Monte Belo do Sul']);
		DB::table('cidades')->insert(['id' => 4312401, 'estado_id' => 43, 'nome' => 'Montenegro']);
		DB::table('cidades')->insert(['id' => 4312427, 'estado_id' => 43, 'nome' => 'Mormaço']);
		DB::table('cidades')->insert(['id' => 4312443, 'estado_id' => 43, 'nome' => 'Morrinhos do Sul']);
		DB::table('cidades')->insert(['id' => 4312450, 'estado_id' => 43, 'nome' => 'Morro Redondo']);
		DB::table('cidades')->insert(['id' => 4312476, 'estado_id' => 43, 'nome' => 'Morro Reuter']);
		DB::table('cidades')->insert(['id' => 4312500, 'estado_id' => 43, 'nome' => 'Mostardas']);
		DB::table('cidades')->insert(['id' => 4312609, 'estado_id' => 43, 'nome' => 'Muçum']);
		DB::table('cidades')->insert(['id' => 4312617, 'estado_id' => 43, 'nome' => 'Muitos Capões']);
		DB::table('cidades')->insert(['id' => 4312625, 'estado_id' => 43, 'nome' => 'Muliterno']);
		DB::table('cidades')->insert(['id' => 4312658, 'estado_id' => 43, 'nome' => 'Não-Me-Toque']);
		DB::table('cidades')->insert(['id' => 4312674, 'estado_id' => 43, 'nome' => 'Nicolau Vergueiro']);
		DB::table('cidades')->insert(['id' => 4312708, 'estado_id' => 43, 'nome' => 'Nonoai']);
		DB::table('cidades')->insert(['id' => 4312757, 'estado_id' => 43, 'nome' => 'Nova Alvorada']);
		DB::table('cidades')->insert(['id' => 4312807, 'estado_id' => 43, 'nome' => 'Nova Araçá']);
		DB::table('cidades')->insert(['id' => 4312906, 'estado_id' => 43, 'nome' => 'Nova Bassano']);
		DB::table('cidades')->insert(['id' => 4312955, 'estado_id' => 43, 'nome' => 'Nova Boa Vista']);
		DB::table('cidades')->insert(['id' => 4313003, 'estado_id' => 43, 'nome' => 'Nova Bréscia']);
		DB::table('cidades')->insert(['id' => 4313011, 'estado_id' => 43, 'nome' => 'Nova Candelária']);
		DB::table('cidades')->insert(['id' => 4313037, 'estado_id' => 43, 'nome' => 'Nova Esperança do Sul']);
		DB::table('cidades')->insert(['id' => 4313060, 'estado_id' => 43, 'nome' => 'Nova Hartz']);
		DB::table('cidades')->insert(['id' => 4313086, 'estado_id' => 43, 'nome' => 'Nova Pádua']);
		DB::table('cidades')->insert(['id' => 4313102, 'estado_id' => 43, 'nome' => 'Nova Palma']);
		DB::table('cidades')->insert(['id' => 4313201, 'estado_id' => 43, 'nome' => 'Nova Petrópolis']);
		DB::table('cidades')->insert(['id' => 4313300, 'estado_id' => 43, 'nome' => 'Nova Prata']);
		DB::table('cidades')->insert(['id' => 4313334, 'estado_id' => 43, 'nome' => 'Nova Ramada']);
		DB::table('cidades')->insert(['id' => 4313359, 'estado_id' => 43, 'nome' => 'Nova Roma do Sul']);
		DB::table('cidades')->insert(['id' => 4313375, 'estado_id' => 43, 'nome' => 'Nova Santa Rita']);
		DB::table('cidades')->insert(['id' => 4313391, 'estado_id' => 43, 'nome' => 'Novo Cabrais']);
		DB::table('cidades')->insert(['id' => 4313409, 'estado_id' => 43, 'nome' => 'Novo Hamburgo']);
		DB::table('cidades')->insert(['id' => 4313425, 'estado_id' => 43, 'nome' => 'Novo Machado']);
		DB::table('cidades')->insert(['id' => 4313441, 'estado_id' => 43, 'nome' => 'Novo Tiradentes']);
		DB::table('cidades')->insert(['id' => 4313466, 'estado_id' => 43, 'nome' => 'Novo Xingu']);
		DB::table('cidades')->insert(['id' => 4313490, 'estado_id' => 43, 'nome' => 'Novo Barreiro']);
		DB::table('cidades')->insert(['id' => 4313508, 'estado_id' => 43, 'nome' => 'Osório']);
		DB::table('cidades')->insert(['id' => 4313607, 'estado_id' => 43, 'nome' => 'Paim Filho']);
		DB::table('cidades')->insert(['id' => 4313656, 'estado_id' => 43, 'nome' => 'Palmares do Sul']);
		DB::table('cidades')->insert(['id' => 4313706, 'estado_id' => 43, 'nome' => 'Palmeira das Missões']);
		DB::table('cidades')->insert(['id' => 4313805, 'estado_id' => 43, 'nome' => 'Palmitinho']);
		DB::table('cidades')->insert(['id' => 4313904, 'estado_id' => 43, 'nome' => 'Panambi']);
		DB::table('cidades')->insert(['id' => 4313953, 'estado_id' => 43, 'nome' => 'Pantano Grande']);
		DB::table('cidades')->insert(['id' => 4314001, 'estado_id' => 43, 'nome' => 'Paraí']);
		DB::table('cidades')->insert(['id' => 4314027, 'estado_id' => 43, 'nome' => 'Paraíso do Sul']);
		DB::table('cidades')->insert(['id' => 4314035, 'estado_id' => 43, 'nome' => 'Pareci Novo']);
		DB::table('cidades')->insert(['id' => 4314050, 'estado_id' => 43, 'nome' => 'Parobé']);
		DB::table('cidades')->insert(['id' => 4314068, 'estado_id' => 43, 'nome' => 'Passa Sete']);
		DB::table('cidades')->insert(['id' => 4314076, 'estado_id' => 43, 'nome' => 'Passo do Sobrado']);
		DB::table('cidades')->insert(['id' => 4314100, 'estado_id' => 43, 'nome' => 'Passo Fundo']);
		DB::table('cidades')->insert(['id' => 4314134, 'estado_id' => 43, 'nome' => 'Paulo Bento']);
		DB::table('cidades')->insert(['id' => 4314159, 'estado_id' => 43, 'nome' => 'Paverama']);
		DB::table('cidades')->insert(['id' => 4314175, 'estado_id' => 43, 'nome' => 'Pedras Altas']);
		DB::table('cidades')->insert(['id' => 4314209, 'estado_id' => 43, 'nome' => 'Pedro Osório']);
		DB::table('cidades')->insert(['id' => 4314308, 'estado_id' => 43, 'nome' => 'Pejuçara']);
		DB::table('cidades')->insert(['id' => 4314407, 'estado_id' => 43, 'nome' => 'Pelotas']);
		DB::table('cidades')->insert(['id' => 4314423, 'estado_id' => 43, 'nome' => 'Picada Café']);
		DB::table('cidades')->insert(['id' => 4314456, 'estado_id' => 43, 'nome' => 'Pinhal']);
		DB::table('cidades')->insert(['id' => 4314464, 'estado_id' => 43, 'nome' => 'Pinhal da Serra']);
		DB::table('cidades')->insert(['id' => 4314472, 'estado_id' => 43, 'nome' => 'Pinhal Grande']);
		DB::table('cidades')->insert(['id' => 4314498, 'estado_id' => 43, 'nome' => 'Pinheirinho do Vale']);
		DB::table('cidades')->insert(['id' => 4314506, 'estado_id' => 43, 'nome' => 'Pinheiro Machado']);
		DB::table('cidades')->insert(['id' => 4314555, 'estado_id' => 43, 'nome' => 'Pirapó']);
		DB::table('cidades')->insert(['id' => 4314605, 'estado_id' => 43, 'nome' => 'Piratini']);
		DB::table('cidades')->insert(['id' => 4314704, 'estado_id' => 43, 'nome' => 'Planalto']);
		DB::table('cidades')->insert(['id' => 4314753, 'estado_id' => 43, 'nome' => 'Poço das Antas']);
		DB::table('cidades')->insert(['id' => 4314779, 'estado_id' => 43, 'nome' => 'Pontão']);
		DB::table('cidades')->insert(['id' => 4314787, 'estado_id' => 43, 'nome' => 'Ponte Preta']);
		DB::table('cidades')->insert(['id' => 4314803, 'estado_id' => 43, 'nome' => 'Portão']);
		DB::table('cidades')->insert(['id' => 4314902, 'estado_id' => 43, 'nome' => 'Porto Alegre']);
		DB::table('cidades')->insert(['id' => 4315008, 'estado_id' => 43, 'nome' => 'Porto Lucena']);
		DB::table('cidades')->insert(['id' => 4315057, 'estado_id' => 43, 'nome' => 'Porto Mauá']);
		DB::table('cidades')->insert(['id' => 4315073, 'estado_id' => 43, 'nome' => 'Porto Vera Cruz']);
		DB::table('cidades')->insert(['id' => 4315107, 'estado_id' => 43, 'nome' => 'Porto Xavier']);
		DB::table('cidades')->insert(['id' => 4315131, 'estado_id' => 43, 'nome' => 'Pouso Novo']);
		DB::table('cidades')->insert(['id' => 4315149, 'estado_id' => 43, 'nome' => 'Presidente Lucena']);
		DB::table('cidades')->insert(['id' => 4315156, 'estado_id' => 43, 'nome' => 'Progresso']);
		DB::table('cidades')->insert(['id' => 4315172, 'estado_id' => 43, 'nome' => 'Protásio Alves']);
		DB::table('cidades')->insert(['id' => 4315206, 'estado_id' => 43, 'nome' => 'Putinga']);
		DB::table('cidades')->insert(['id' => 4315305, 'estado_id' => 43, 'nome' => 'Quaraí']);
		DB::table('cidades')->insert(['id' => 4315313, 'estado_id' => 43, 'nome' => 'Quatro Irmãos']);
		DB::table('cidades')->insert(['id' => 4315321, 'estado_id' => 43, 'nome' => 'Quevedos']);
		DB::table('cidades')->insert(['id' => 4315354, 'estado_id' => 43, 'nome' => 'Quinze de Novembro']);
		DB::table('cidades')->insert(['id' => 4315404, 'estado_id' => 43, 'nome' => 'Redentora']);
		DB::table('cidades')->insert(['id' => 4315453, 'estado_id' => 43, 'nome' => 'Relvado']);
		DB::table('cidades')->insert(['id' => 4315503, 'estado_id' => 43, 'nome' => 'Restinga Seca']);
		DB::table('cidades')->insert(['id' => 4315552, 'estado_id' => 43, 'nome' => 'Rio dos Índios']);
		DB::table('cidades')->insert(['id' => 4315602, 'estado_id' => 43, 'nome' => 'Rio Grande']);
		DB::table('cidades')->insert(['id' => 4315701, 'estado_id' => 43, 'nome' => 'Rio Pardo']);
		DB::table('cidades')->insert(['id' => 4315750, 'estado_id' => 43, 'nome' => 'Riozinho']);
		DB::table('cidades')->insert(['id' => 4315800, 'estado_id' => 43, 'nome' => 'Roca Sales']);
		DB::table('cidades')->insert(['id' => 4315909, 'estado_id' => 43, 'nome' => 'Rodeio Bonito']);
		DB::table('cidades')->insert(['id' => 4315958, 'estado_id' => 43, 'nome' => 'Rolador']);
		DB::table('cidades')->insert(['id' => 4316006, 'estado_id' => 43, 'nome' => 'Rolante']);
		DB::table('cidades')->insert(['id' => 4316105, 'estado_id' => 43, 'nome' => 'Ronda Alta']);
		DB::table('cidades')->insert(['id' => 4316204, 'estado_id' => 43, 'nome' => 'Rondinha']);
		DB::table('cidades')->insert(['id' => 4316303, 'estado_id' => 43, 'nome' => 'Roque Gonzales']);
		DB::table('cidades')->insert(['id' => 4316402, 'estado_id' => 43, 'nome' => 'Rosário do Sul']);
		DB::table('cidades')->insert(['id' => 4316428, 'estado_id' => 43, 'nome' => 'Sagrada Família']);
		DB::table('cidades')->insert(['id' => 4316436, 'estado_id' => 43, 'nome' => 'Saldanha Marinho']);
		DB::table('cidades')->insert(['id' => 4316451, 'estado_id' => 43, 'nome' => 'Salto do Jacuí']);
		DB::table('cidades')->insert(['id' => 4316477, 'estado_id' => 43, 'nome' => 'Salvador das Missões']);
		DB::table('cidades')->insert(['id' => 4316501, 'estado_id' => 43, 'nome' => 'Salvador do Sul']);
		DB::table('cidades')->insert(['id' => 4316600, 'estado_id' => 43, 'nome' => 'Sananduva']);
		DB::table('cidades')->insert(['id' => 4316709, 'estado_id' => 43, 'nome' => 'Santa Bárbara do Sul']);
		DB::table('cidades')->insert(['id' => 4316733, 'estado_id' => 43, 'nome' => 'Santa Cecília do Sul']);
		DB::table('cidades')->insert(['id' => 4316758, 'estado_id' => 43, 'nome' => 'Santa Clara do Sul']);
		DB::table('cidades')->insert(['id' => 4316808, 'estado_id' => 43, 'nome' => 'Santa Cruz do Sul']);
		DB::table('cidades')->insert(['id' => 4316907, 'estado_id' => 43, 'nome' => 'Santa Maria']);
		DB::table('cidades')->insert(['id' => 4316956, 'estado_id' => 43, 'nome' => 'Santa Maria do Herval']);
		DB::table('cidades')->insert(['id' => 4316972, 'estado_id' => 43, 'nome' => 'Santa Margarida do Sul']);
		DB::table('cidades')->insert(['id' => 4317004, 'estado_id' => 43, 'nome' => 'Santana da Boa Vista']);
		DB::table('cidades')->insert(['id' => 4317103, 'estado_id' => 43, 'nome' => 'Santana do Livramento']);
		DB::table('cidades')->insert(['id' => 4317202, 'estado_id' => 43, 'nome' => 'Santa Rosa']);
		DB::table('cidades')->insert(['id' => 4317251, 'estado_id' => 43, 'nome' => 'Santa Tereza']);
		DB::table('cidades')->insert(['id' => 4317301, 'estado_id' => 43, 'nome' => 'Santa Vitória do Palmar']);
		DB::table('cidades')->insert(['id' => 4317400, 'estado_id' => 43, 'nome' => 'Santiago']);
		DB::table('cidades')->insert(['id' => 4317509, 'estado_id' => 43, 'nome' => 'Santo Ângelo']);
		DB::table('cidades')->insert(['id' => 4317558, 'estado_id' => 43, 'nome' => 'Santo Antônio do Palma']);
		DB::table('cidades')->insert(['id' => 4317608, 'estado_id' => 43, 'nome' => 'Santo Antônio da Patrulha']);
		DB::table('cidades')->insert(['id' => 4317707, 'estado_id' => 43, 'nome' => 'Santo Antônio das Missões']);
		DB::table('cidades')->insert(['id' => 4317756, 'estado_id' => 43, 'nome' => 'Santo Antônio do Planalto']);
		DB::table('cidades')->insert(['id' => 4317806, 'estado_id' => 43, 'nome' => 'Santo Augusto']);
		DB::table('cidades')->insert(['id' => 4317905, 'estado_id' => 43, 'nome' => 'Santo Cristo']);
		DB::table('cidades')->insert(['id' => 4317954, 'estado_id' => 43, 'nome' => 'Santo Expedito do Sul']);
		DB::table('cidades')->insert(['id' => 4318002, 'estado_id' => 43, 'nome' => 'São Borja']);
		DB::table('cidades')->insert(['id' => 4318051, 'estado_id' => 43, 'nome' => 'São Domingos do Sul']);
		DB::table('cidades')->insert(['id' => 4318101, 'estado_id' => 43, 'nome' => 'São Francisco de Assis']);
		DB::table('cidades')->insert(['id' => 4318200, 'estado_id' => 43, 'nome' => 'São Francisco de Paula']);
		DB::table('cidades')->insert(['id' => 4318309, 'estado_id' => 43, 'nome' => 'São Gabriel']);
		DB::table('cidades')->insert(['id' => 4318408, 'estado_id' => 43, 'nome' => 'São Jerônimo']);
		DB::table('cidades')->insert(['id' => 4318424, 'estado_id' => 43, 'nome' => 'São João da Urtiga']);
		DB::table('cidades')->insert(['id' => 4318432, 'estado_id' => 43, 'nome' => 'São João do Polêsine']);
		DB::table('cidades')->insert(['id' => 4318440, 'estado_id' => 43, 'nome' => 'São Jorge']);
		DB::table('cidades')->insert(['id' => 4318457, 'estado_id' => 43, 'nome' => 'São José das Missões']);
		DB::table('cidades')->insert(['id' => 4318465, 'estado_id' => 43, 'nome' => 'São José do Herval']);
		DB::table('cidades')->insert(['id' => 4318481, 'estado_id' => 43, 'nome' => 'São José do Hortêncio']);
		DB::table('cidades')->insert(['id' => 4318499, 'estado_id' => 43, 'nome' => 'São José do Inhacorá']);
		DB::table('cidades')->insert(['id' => 4318507, 'estado_id' => 43, 'nome' => 'São José do Norte']);
		DB::table('cidades')->insert(['id' => 4318606, 'estado_id' => 43, 'nome' => 'São José do Ouro']);
		DB::table('cidades')->insert(['id' => 4318614, 'estado_id' => 43, 'nome' => 'São José do Sul']);
		DB::table('cidades')->insert(['id' => 4318622, 'estado_id' => 43, 'nome' => 'São José dos Ausentes']);
		DB::table('cidades')->insert(['id' => 4318705, 'estado_id' => 43, 'nome' => 'São Leopoldo']);
		DB::table('cidades')->insert(['id' => 4318804, 'estado_id' => 43, 'nome' => 'São Lourenço do Sul']);
		DB::table('cidades')->insert(['id' => 4318903, 'estado_id' => 43, 'nome' => 'São Luiz Gonzaga']);
		DB::table('cidades')->insert(['id' => 4319000, 'estado_id' => 43, 'nome' => 'São Marcos']);
		DB::table('cidades')->insert(['id' => 4319109, 'estado_id' => 43, 'nome' => 'São Martinho']);
		DB::table('cidades')->insert(['id' => 4319125, 'estado_id' => 43, 'nome' => 'São Martinho da Serra']);
		DB::table('cidades')->insert(['id' => 4319158, 'estado_id' => 43, 'nome' => 'São Miguel das Missões']);
		DB::table('cidades')->insert(['id' => 4319208, 'estado_id' => 43, 'nome' => 'São Nicolau']);
		DB::table('cidades')->insert(['id' => 4319307, 'estado_id' => 43, 'nome' => 'São Paulo das Missões']);
		DB::table('cidades')->insert(['id' => 4319356, 'estado_id' => 43, 'nome' => 'São Pedro da Serra']);
		DB::table('cidades')->insert(['id' => 4319364, 'estado_id' => 43, 'nome' => 'São Pedro das Missões']);
		DB::table('cidades')->insert(['id' => 4319372, 'estado_id' => 43, 'nome' => 'São Pedro do Butiá']);
		DB::table('cidades')->insert(['id' => 4319406, 'estado_id' => 43, 'nome' => 'São Pedro do Sul']);
		DB::table('cidades')->insert(['id' => 4319505, 'estado_id' => 43, 'nome' => 'São Sebastião do Caí']);
		DB::table('cidades')->insert(['id' => 4319604, 'estado_id' => 43, 'nome' => 'São Sepé']);
		DB::table('cidades')->insert(['id' => 4319703, 'estado_id' => 43, 'nome' => 'São Valentim']);
		DB::table('cidades')->insert(['id' => 4319711, 'estado_id' => 43, 'nome' => 'São Valentim do Sul']);
		DB::table('cidades')->insert(['id' => 4319737, 'estado_id' => 43, 'nome' => 'São Valério do Sul']);
		DB::table('cidades')->insert(['id' => 4319752, 'estado_id' => 43, 'nome' => 'São Vendelino']);
		DB::table('cidades')->insert(['id' => 4319802, 'estado_id' => 43, 'nome' => 'São Vicente do Sul']);
		DB::table('cidades')->insert(['id' => 4319901, 'estado_id' => 43, 'nome' => 'Sapiranga']);
		DB::table('cidades')->insert(['id' => 4320008, 'estado_id' => 43, 'nome' => 'Sapucaia do Sul']);
		DB::table('cidades')->insert(['id' => 4320107, 'estado_id' => 43, 'nome' => 'Sarandi']);
		DB::table('cidades')->insert(['id' => 4320206, 'estado_id' => 43, 'nome' => 'Seberi']);
		DB::table('cidades')->insert(['id' => 4320230, 'estado_id' => 43, 'nome' => 'Sede Nova']);
		DB::table('cidades')->insert(['id' => 4320263, 'estado_id' => 43, 'nome' => 'Segredo']);
		DB::table('cidades')->insert(['id' => 4320305, 'estado_id' => 43, 'nome' => 'Selbach']);
		DB::table('cidades')->insert(['id' => 4320321, 'estado_id' => 43, 'nome' => 'Senador Salgado Filho']);
		DB::table('cidades')->insert(['id' => 4320354, 'estado_id' => 43, 'nome' => 'Sentinela do Sul']);
		DB::table('cidades')->insert(['id' => 4320404, 'estado_id' => 43, 'nome' => 'Serafina Corrêa']);
		DB::table('cidades')->insert(['id' => 4320453, 'estado_id' => 43, 'nome' => 'Sério']);
		DB::table('cidades')->insert(['id' => 4320503, 'estado_id' => 43, 'nome' => 'Sertão']);
		DB::table('cidades')->insert(['id' => 4320552, 'estado_id' => 43, 'nome' => 'Sertão Santana']);
		DB::table('cidades')->insert(['id' => 4320578, 'estado_id' => 43, 'nome' => 'Sete de Setembro']);
		DB::table('cidades')->insert(['id' => 4320602, 'estado_id' => 43, 'nome' => 'Severiano de Almeida']);
		DB::table('cidades')->insert(['id' => 4320651, 'estado_id' => 43, 'nome' => 'Silveira Martins']);
		DB::table('cidades')->insert(['id' => 4320677, 'estado_id' => 43, 'nome' => 'Sinimbu']);
		DB::table('cidades')->insert(['id' => 4320701, 'estado_id' => 43, 'nome' => 'Sobradinho']);
		DB::table('cidades')->insert(['id' => 4320800, 'estado_id' => 43, 'nome' => 'Soledade']);
		DB::table('cidades')->insert(['id' => 4320859, 'estado_id' => 43, 'nome' => 'Tabaí']);
		DB::table('cidades')->insert(['id' => 4320909, 'estado_id' => 43, 'nome' => 'Tapejara']);
		DB::table('cidades')->insert(['id' => 4321006, 'estado_id' => 43, 'nome' => 'Tapera']);
		DB::table('cidades')->insert(['id' => 4321105, 'estado_id' => 43, 'nome' => 'Tapes']);
		DB::table('cidades')->insert(['id' => 4321204, 'estado_id' => 43, 'nome' => 'Taquara']);
		DB::table('cidades')->insert(['id' => 4321303, 'estado_id' => 43, 'nome' => 'Taquari']);
		DB::table('cidades')->insert(['id' => 4321329, 'estado_id' => 43, 'nome' => 'Taquaruçu do Sul']);
		DB::table('cidades')->insert(['id' => 4321352, 'estado_id' => 43, 'nome' => 'Tavares']);
		DB::table('cidades')->insert(['id' => 4321402, 'estado_id' => 43, 'nome' => 'Tenente Portela']);
		DB::table('cidades')->insert(['id' => 4321436, 'estado_id' => 43, 'nome' => 'Terra de Areia']);
		DB::table('cidades')->insert(['id' => 4321451, 'estado_id' => 43, 'nome' => 'Teutônia']);
		DB::table('cidades')->insert(['id' => 4321469, 'estado_id' => 43, 'nome' => 'Tio Hugo']);
		DB::table('cidades')->insert(['id' => 4321477, 'estado_id' => 43, 'nome' => 'Tiradentes do Sul']);
		DB::table('cidades')->insert(['id' => 4321493, 'estado_id' => 43, 'nome' => 'Toropi']);
		DB::table('cidades')->insert(['id' => 4321501, 'estado_id' => 43, 'nome' => 'Torres']);
		DB::table('cidades')->insert(['id' => 4321600, 'estado_id' => 43, 'nome' => 'Tramandaí']);
		DB::table('cidades')->insert(['id' => 4321626, 'estado_id' => 43, 'nome' => 'Travesseiro']);
		DB::table('cidades')->insert(['id' => 4321634, 'estado_id' => 43, 'nome' => 'Três Arroios']);
		DB::table('cidades')->insert(['id' => 4321667, 'estado_id' => 43, 'nome' => 'Três Cachoeiras']);
		DB::table('cidades')->insert(['id' => 4321709, 'estado_id' => 43, 'nome' => 'Três Coroas']);
		DB::table('cidades')->insert(['id' => 4321808, 'estado_id' => 43, 'nome' => 'Três de Maio']);
		DB::table('cidades')->insert(['id' => 4321832, 'estado_id' => 43, 'nome' => 'Três Forquilhas']);
		DB::table('cidades')->insert(['id' => 4321857, 'estado_id' => 43, 'nome' => 'Três Palmeiras']);
		DB::table('cidades')->insert(['id' => 4321907, 'estado_id' => 43, 'nome' => 'Três Passos']);
		DB::table('cidades')->insert(['id' => 4321956, 'estado_id' => 43, 'nome' => 'Trindade do Sul']);
		DB::table('cidades')->insert(['id' => 4322004, 'estado_id' => 43, 'nome' => 'Triunfo']);
		DB::table('cidades')->insert(['id' => 4322103, 'estado_id' => 43, 'nome' => 'Tucunduva']);
		DB::table('cidades')->insert(['id' => 4322152, 'estado_id' => 43, 'nome' => 'Tunas']);
		DB::table('cidades')->insert(['id' => 4322186, 'estado_id' => 43, 'nome' => 'Tupanci do Sul']);
		DB::table('cidades')->insert(['id' => 4322202, 'estado_id' => 43, 'nome' => 'Tupanciretã']);
		DB::table('cidades')->insert(['id' => 4322251, 'estado_id' => 43, 'nome' => 'Tupandi']);
		DB::table('cidades')->insert(['id' => 4322301, 'estado_id' => 43, 'nome' => 'Tuparendi']);
		DB::table('cidades')->insert(['id' => 4322327, 'estado_id' => 43, 'nome' => 'Turuçu']);
		DB::table('cidades')->insert(['id' => 4322343, 'estado_id' => 43, 'nome' => 'Ubiretama']);
		DB::table('cidades')->insert(['id' => 4322350, 'estado_id' => 43, 'nome' => 'União da Serra']);
		DB::table('cidades')->insert(['id' => 4322376, 'estado_id' => 43, 'nome' => 'Unistalda']);
		DB::table('cidades')->insert(['id' => 4322400, 'estado_id' => 43, 'nome' => 'Uruguaiana']);
		DB::table('cidades')->insert(['id' => 4322509, 'estado_id' => 43, 'nome' => 'Vacaria']);
		DB::table('cidades')->insert(['id' => 4322525, 'estado_id' => 43, 'nome' => 'Vale Verde']);
		DB::table('cidades')->insert(['id' => 4322533, 'estado_id' => 43, 'nome' => 'Vale do Sol']);
		DB::table('cidades')->insert(['id' => 4322541, 'estado_id' => 43, 'nome' => 'Vale Real']);
		DB::table('cidades')->insert(['id' => 4322558, 'estado_id' => 43, 'nome' => 'Vanini']);
		DB::table('cidades')->insert(['id' => 4322608, 'estado_id' => 43, 'nome' => 'Venâncio Aires']);
		DB::table('cidades')->insert(['id' => 4322707, 'estado_id' => 43, 'nome' => 'Vera Cruz']);
		DB::table('cidades')->insert(['id' => 4322806, 'estado_id' => 43, 'nome' => 'Veranópolis']);
		DB::table('cidades')->insert(['id' => 4322855, 'estado_id' => 43, 'nome' => 'Vespasiano Correa']);
		DB::table('cidades')->insert(['id' => 4322905, 'estado_id' => 43, 'nome' => 'Viadutos']);
		DB::table('cidades')->insert(['id' => 4323002, 'estado_id' => 43, 'nome' => 'Viamão']);
		DB::table('cidades')->insert(['id' => 4323101, 'estado_id' => 43, 'nome' => 'Vicente Dutra']);
		DB::table('cidades')->insert(['id' => 4323200, 'estado_id' => 43, 'nome' => 'Victor Graeff']);
		DB::table('cidades')->insert(['id' => 4323309, 'estado_id' => 43, 'nome' => 'Vila Flores']);
		DB::table('cidades')->insert(['id' => 4323358, 'estado_id' => 43, 'nome' => 'Vila Lângaro']);
		DB::table('cidades')->insert(['id' => 4323408, 'estado_id' => 43, 'nome' => 'Vila Maria']);
		DB::table('cidades')->insert(['id' => 4323457, 'estado_id' => 43, 'nome' => 'Vila Nova do Sul']);
		DB::table('cidades')->insert(['id' => 4323507, 'estado_id' => 43, 'nome' => 'Vista Alegre']);
		DB::table('cidades')->insert(['id' => 4323606, 'estado_id' => 43, 'nome' => 'Vista Alegre do Prata']);
		DB::table('cidades')->insert(['id' => 4323705, 'estado_id' => 43, 'nome' => 'Vista Gaúcha']);
		DB::table('cidades')->insert(['id' => 4323754, 'estado_id' => 43, 'nome' => 'Vitória das Missões']);
		DB::table('cidades')->insert(['id' => 4323770, 'estado_id' => 43, 'nome' => 'Westfalia']);
		DB::table('cidades')->insert(['id' => 4323804, 'estado_id' => 43, 'nome' => 'Xangri-lá']);
    }
}
