<?php

use Illuminate\Database\Seeder;

class CidadesTableBASeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades da Bahia
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 2900108, 'estado_id' => 29, 'nome' => 'Abaíra']);
		DB::table('cidades')->insert(['id' => 2900207, 'estado_id' => 29, 'nome' => 'Abaré']);
		DB::table('cidades')->insert(['id' => 2900306, 'estado_id' => 29, 'nome' => 'Acajutiba']);
		DB::table('cidades')->insert(['id' => 2900355, 'estado_id' => 29, 'nome' => 'Adustina']);
		DB::table('cidades')->insert(['id' => 2900405, 'estado_id' => 29, 'nome' => 'Água Fria']);
		DB::table('cidades')->insert(['id' => 2900504, 'estado_id' => 29, 'nome' => 'Érico Cardoso']);
		DB::table('cidades')->insert(['id' => 2900603, 'estado_id' => 29, 'nome' => 'Aiquara']);
		DB::table('cidades')->insert(['id' => 2900702, 'estado_id' => 29, 'nome' => 'Alagoinhas']);
		DB::table('cidades')->insert(['id' => 2900801, 'estado_id' => 29, 'nome' => 'Alcobaça']);
		DB::table('cidades')->insert(['id' => 2900900, 'estado_id' => 29, 'nome' => 'Almadina']);
		DB::table('cidades')->insert(['id' => 2901007, 'estado_id' => 29, 'nome' => 'Amargosa']);
		DB::table('cidades')->insert(['id' => 2901106, 'estado_id' => 29, 'nome' => 'Amélia Rodrigues']);
		DB::table('cidades')->insert(['id' => 2901155, 'estado_id' => 29, 'nome' => 'América Dourada']);
		DB::table('cidades')->insert(['id' => 2901205, 'estado_id' => 29, 'nome' => 'Anagé']);
		DB::table('cidades')->insert(['id' => 2901304, 'estado_id' => 29, 'nome' => 'Andaraí']);
		DB::table('cidades')->insert(['id' => 2901353, 'estado_id' => 29, 'nome' => 'Andorinha']);
		DB::table('cidades')->insert(['id' => 2901403, 'estado_id' => 29, 'nome' => 'Angical']);
		DB::table('cidades')->insert(['id' => 2901502, 'estado_id' => 29, 'nome' => 'Anguera']);
		DB::table('cidades')->insert(['id' => 2901601, 'estado_id' => 29, 'nome' => 'Antas']);
		DB::table('cidades')->insert(['id' => 2901700, 'estado_id' => 29, 'nome' => 'Antônio Cardoso']);
		DB::table('cidades')->insert(['id' => 2901809, 'estado_id' => 29, 'nome' => 'Antônio Gonçalves']);
		DB::table('cidades')->insert(['id' => 2901908, 'estado_id' => 29, 'nome' => 'Aporá']);
		DB::table('cidades')->insert(['id' => 2901957, 'estado_id' => 29, 'nome' => 'Apuarema']);
		DB::table('cidades')->insert(['id' => 2902005, 'estado_id' => 29, 'nome' => 'Aracatu']);
		DB::table('cidades')->insert(['id' => 2902054, 'estado_id' => 29, 'nome' => 'Araças']);
		DB::table('cidades')->insert(['id' => 2902104, 'estado_id' => 29, 'nome' => 'Araci']);
		DB::table('cidades')->insert(['id' => 2902203, 'estado_id' => 29, 'nome' => 'Aramari']);
		DB::table('cidades')->insert(['id' => 2902252, 'estado_id' => 29, 'nome' => 'Arataca']);
		DB::table('cidades')->insert(['id' => 2902302, 'estado_id' => 29, 'nome' => 'Aratuípe']);
		DB::table('cidades')->insert(['id' => 2902401, 'estado_id' => 29, 'nome' => 'Aurelino Leal']);
		DB::table('cidades')->insert(['id' => 2902500, 'estado_id' => 29, 'nome' => 'Baianópolis']);
		DB::table('cidades')->insert(['id' => 2902609, 'estado_id' => 29, 'nome' => 'Baixa Grande']);
		DB::table('cidades')->insert(['id' => 2902658, 'estado_id' => 29, 'nome' => 'Banzaê']);
		DB::table('cidades')->insert(['id' => 2902708, 'estado_id' => 29, 'nome' => 'Barra']);
		DB::table('cidades')->insert(['id' => 2902807, 'estado_id' => 29, 'nome' => 'Barra da Estiva']);
		DB::table('cidades')->insert(['id' => 2902906, 'estado_id' => 29, 'nome' => 'Barra do Choça']);
		DB::table('cidades')->insert(['id' => 2903003, 'estado_id' => 29, 'nome' => 'Barra do Mendes']);
		DB::table('cidades')->insert(['id' => 2903102, 'estado_id' => 29, 'nome' => 'Barra do Rocha']);
		DB::table('cidades')->insert(['id' => 2903201, 'estado_id' => 29, 'nome' => 'Barreiras']);
		DB::table('cidades')->insert(['id' => 2903235, 'estado_id' => 29, 'nome' => 'Barro Alto']);
		DB::table('cidades')->insert(['id' => 2903276, 'estado_id' => 29, 'nome' => 'Barrocas']);
		DB::table('cidades')->insert(['id' => 2903300, 'estado_id' => 29, 'nome' => 'Barro Preto']);
		DB::table('cidades')->insert(['id' => 2903409, 'estado_id' => 29, 'nome' => 'Belmonte']);
		DB::table('cidades')->insert(['id' => 2903508, 'estado_id' => 29, 'nome' => 'Belo Campo']);
		DB::table('cidades')->insert(['id' => 2903607, 'estado_id' => 29, 'nome' => 'Biritinga']);
		DB::table('cidades')->insert(['id' => 2903706, 'estado_id' => 29, 'nome' => 'Boa Nova']);
		DB::table('cidades')->insert(['id' => 2903805, 'estado_id' => 29, 'nome' => 'Boa Vista do Tupim']);
		DB::table('cidades')->insert(['id' => 2903904, 'estado_id' => 29, 'nome' => 'Bom Jesus da Lapa']);
		DB::table('cidades')->insert(['id' => 2903953, 'estado_id' => 29, 'nome' => 'Bom Jesus da Serra']);
		DB::table('cidades')->insert(['id' => 2904001, 'estado_id' => 29, 'nome' => 'Boninal']);
		DB::table('cidades')->insert(['id' => 2904050, 'estado_id' => 29, 'nome' => 'Bonito']);
		DB::table('cidades')->insert(['id' => 2904100, 'estado_id' => 29, 'nome' => 'Boquira']);
		DB::table('cidades')->insert(['id' => 2904209, 'estado_id' => 29, 'nome' => 'Botuporã']);
		DB::table('cidades')->insert(['id' => 2904308, 'estado_id' => 29, 'nome' => 'Brejões']);
		DB::table('cidades')->insert(['id' => 2904407, 'estado_id' => 29, 'nome' => 'Brejolândia']);
		DB::table('cidades')->insert(['id' => 2904506, 'estado_id' => 29, 'nome' => 'Brotas de Macaúbas']);
		DB::table('cidades')->insert(['id' => 2904605, 'estado_id' => 29, 'nome' => 'Brumado']);
		DB::table('cidades')->insert(['id' => 2904704, 'estado_id' => 29, 'nome' => 'Buerarema']);
		DB::table('cidades')->insert(['id' => 2904753, 'estado_id' => 29, 'nome' => 'Buritirama']);
		DB::table('cidades')->insert(['id' => 2904803, 'estado_id' => 29, 'nome' => 'Caatiba']);
		DB::table('cidades')->insert(['id' => 2904852, 'estado_id' => 29, 'nome' => 'Cabaceiras do Paraguaçu']);
		DB::table('cidades')->insert(['id' => 2904902, 'estado_id' => 29, 'nome' => 'Cachoeira']);
		DB::table('cidades')->insert(['id' => 2905008, 'estado_id' => 29, 'nome' => 'Caculé']);
		DB::table('cidades')->insert(['id' => 2905107, 'estado_id' => 29, 'nome' => 'Caém']);
		DB::table('cidades')->insert(['id' => 2905156, 'estado_id' => 29, 'nome' => 'Caetanos']);
		DB::table('cidades')->insert(['id' => 2905206, 'estado_id' => 29, 'nome' => 'Caetité']);
		DB::table('cidades')->insert(['id' => 2905305, 'estado_id' => 29, 'nome' => 'Cafarnaum']);
		DB::table('cidades')->insert(['id' => 2905404, 'estado_id' => 29, 'nome' => 'Cairu']);
		DB::table('cidades')->insert(['id' => 2905503, 'estado_id' => 29, 'nome' => 'Caldeirão Grande']);
		DB::table('cidades')->insert(['id' => 2905602, 'estado_id' => 29, 'nome' => 'Camacan']);
		DB::table('cidades')->insert(['id' => 2905701, 'estado_id' => 29, 'nome' => 'Camaçari']);
		DB::table('cidades')->insert(['id' => 2905800, 'estado_id' => 29, 'nome' => 'Camamu']);
		DB::table('cidades')->insert(['id' => 2905909, 'estado_id' => 29, 'nome' => 'Campo Alegre de Lourdes']);
		DB::table('cidades')->insert(['id' => 2906006, 'estado_id' => 29, 'nome' => 'Campo Formoso']);
		DB::table('cidades')->insert(['id' => 2906105, 'estado_id' => 29, 'nome' => 'Canápolis']);
		DB::table('cidades')->insert(['id' => 2906204, 'estado_id' => 29, 'nome' => 'Canarana']);
		DB::table('cidades')->insert(['id' => 2906303, 'estado_id' => 29, 'nome' => 'Canavieiras']);
		DB::table('cidades')->insert(['id' => 2906402, 'estado_id' => 29, 'nome' => 'Candeal']);
		DB::table('cidades')->insert(['id' => 2906501, 'estado_id' => 29, 'nome' => 'Candeias']);
		DB::table('cidades')->insert(['id' => 2906600, 'estado_id' => 29, 'nome' => 'Candiba']);
		DB::table('cidades')->insert(['id' => 2906709, 'estado_id' => 29, 'nome' => 'Cândido Sales']);
		DB::table('cidades')->insert(['id' => 2906808, 'estado_id' => 29, 'nome' => 'Cansanção']);
		DB::table('cidades')->insert(['id' => 2906824, 'estado_id' => 29, 'nome' => 'Canudos']);
		DB::table('cidades')->insert(['id' => 2906857, 'estado_id' => 29, 'nome' => 'Capela do Alto Alegre']);
		DB::table('cidades')->insert(['id' => 2906873, 'estado_id' => 29, 'nome' => 'Capim Grosso']);
		DB::table('cidades')->insert(['id' => 2906899, 'estado_id' => 29, 'nome' => 'Caraíbas']);
		DB::table('cidades')->insert(['id' => 2906907, 'estado_id' => 29, 'nome' => 'Caravelas']);
		DB::table('cidades')->insert(['id' => 2907004, 'estado_id' => 29, 'nome' => 'Cardeal da Silva']);
		DB::table('cidades')->insert(['id' => 2907103, 'estado_id' => 29, 'nome' => 'Carinhanha']);
		DB::table('cidades')->insert(['id' => 2907202, 'estado_id' => 29, 'nome' => 'Casa Nova']);
		DB::table('cidades')->insert(['id' => 2907301, 'estado_id' => 29, 'nome' => 'Castro Alves']);
		DB::table('cidades')->insert(['id' => 2907400, 'estado_id' => 29, 'nome' => 'Catolândia']);
		DB::table('cidades')->insert(['id' => 2907509, 'estado_id' => 29, 'nome' => 'Catu']);
		DB::table('cidades')->insert(['id' => 2907558, 'estado_id' => 29, 'nome' => 'Caturama']);
		DB::table('cidades')->insert(['id' => 2907608, 'estado_id' => 29, 'nome' => 'Central']);
		DB::table('cidades')->insert(['id' => 2907707, 'estado_id' => 29, 'nome' => 'Chorrochó']);
		DB::table('cidades')->insert(['id' => 2907806, 'estado_id' => 29, 'nome' => 'Cícero Dantas']);
		DB::table('cidades')->insert(['id' => 2907905, 'estado_id' => 29, 'nome' => 'Cipó']);
		DB::table('cidades')->insert(['id' => 2908002, 'estado_id' => 29, 'nome' => 'Coaraci']);
		DB::table('cidades')->insert(['id' => 2908101, 'estado_id' => 29, 'nome' => 'Cocos']);
		DB::table('cidades')->insert(['id' => 2908200, 'estado_id' => 29, 'nome' => 'Conceição da Feira']);
		DB::table('cidades')->insert(['id' => 2908309, 'estado_id' => 29, 'nome' => 'Conceição do Almeida']);
		DB::table('cidades')->insert(['id' => 2908408, 'estado_id' => 29, 'nome' => 'Conceição do Coité']);
		DB::table('cidades')->insert(['id' => 2908507, 'estado_id' => 29, 'nome' => 'Conceição do Jacuípe']);
		DB::table('cidades')->insert(['id' => 2908606, 'estado_id' => 29, 'nome' => 'Conde']);
		DB::table('cidades')->insert(['id' => 2908705, 'estado_id' => 29, 'nome' => 'Condeúba']);
		DB::table('cidades')->insert(['id' => 2908804, 'estado_id' => 29, 'nome' => 'Contendas do Sincorá']);
		DB::table('cidades')->insert(['id' => 2908903, 'estado_id' => 29, 'nome' => 'Coração de Maria']);
		DB::table('cidades')->insert(['id' => 2909000, 'estado_id' => 29, 'nome' => 'Cordeiros']);
		DB::table('cidades')->insert(['id' => 2909109, 'estado_id' => 29, 'nome' => 'Coribe']);
		DB::table('cidades')->insert(['id' => 2909208, 'estado_id' => 29, 'nome' => 'Coronel João Sá']);
		DB::table('cidades')->insert(['id' => 2909307, 'estado_id' => 29, 'nome' => 'Correntina']);
		DB::table('cidades')->insert(['id' => 2909406, 'estado_id' => 29, 'nome' => 'Cotegipe']);
		DB::table('cidades')->insert(['id' => 2909505, 'estado_id' => 29, 'nome' => 'Cravolândia']);
		DB::table('cidades')->insert(['id' => 2909604, 'estado_id' => 29, 'nome' => 'Crisópolis']);
		DB::table('cidades')->insert(['id' => 2909703, 'estado_id' => 29, 'nome' => 'Cristópolis']);
		DB::table('cidades')->insert(['id' => 2909802, 'estado_id' => 29, 'nome' => 'Cruz das Almas']);
		DB::table('cidades')->insert(['id' => 2909901, 'estado_id' => 29, 'nome' => 'Curaçá']);
		DB::table('cidades')->insert(['id' => 2910008, 'estado_id' => 29, 'nome' => 'Dário Meira']);
		DB::table('cidades')->insert(['id' => 2910057, 'estado_id' => 29, 'nome' => 'Dias d\'Ávila']);
		DB::table('cidades')->insert(['id' => 2910107, 'estado_id' => 29, 'nome' => 'Dom Basílio']);
		DB::table('cidades')->insert(['id' => 2910206, 'estado_id' => 29, 'nome' => 'Dom Macedo Costa']);
		DB::table('cidades')->insert(['id' => 2910305, 'estado_id' => 29, 'nome' => 'Elísio Medrado']);
		DB::table('cidades')->insert(['id' => 2910404, 'estado_id' => 29, 'nome' => 'Encruzilhada']);
		DB::table('cidades')->insert(['id' => 2910503, 'estado_id' => 29, 'nome' => 'Entre Rios']);
		DB::table('cidades')->insert(['id' => 2910602, 'estado_id' => 29, 'nome' => 'Esplanada']);
		DB::table('cidades')->insert(['id' => 2910701, 'estado_id' => 29, 'nome' => 'Euclides da Cunha']);
		DB::table('cidades')->insert(['id' => 2910727, 'estado_id' => 29, 'nome' => 'Eunápolis']);
		DB::table('cidades')->insert(['id' => 2910750, 'estado_id' => 29, 'nome' => 'Fátima']);
		DB::table('cidades')->insert(['id' => 2910776, 'estado_id' => 29, 'nome' => 'Feira da Mata']);
		DB::table('cidades')->insert(['id' => 2910800, 'estado_id' => 29, 'nome' => 'Feira de Santana']);
		DB::table('cidades')->insert(['id' => 2910859, 'estado_id' => 29, 'nome' => 'Filadélfia']);
		DB::table('cidades')->insert(['id' => 2910909, 'estado_id' => 29, 'nome' => 'Firmino Alves']);
		DB::table('cidades')->insert(['id' => 2911006, 'estado_id' => 29, 'nome' => 'Floresta Azul']);
		DB::table('cidades')->insert(['id' => 2911105, 'estado_id' => 29, 'nome' => 'Formosa do Rio Preto']);
		DB::table('cidades')->insert(['id' => 2911204, 'estado_id' => 29, 'nome' => 'Gandu']);
		DB::table('cidades')->insert(['id' => 2911253, 'estado_id' => 29, 'nome' => 'Gavião']);
		DB::table('cidades')->insert(['id' => 2911303, 'estado_id' => 29, 'nome' => 'Gentio do Ouro']);
		DB::table('cidades')->insert(['id' => 2911402, 'estado_id' => 29, 'nome' => 'Glória']);
		DB::table('cidades')->insert(['id' => 2911501, 'estado_id' => 29, 'nome' => 'Gongogi']);
		DB::table('cidades')->insert(['id' => 2911600, 'estado_id' => 29, 'nome' => 'Governador Mangabeira']);
		DB::table('cidades')->insert(['id' => 2911659, 'estado_id' => 29, 'nome' => 'Guajeru']);
		DB::table('cidades')->insert(['id' => 2911709, 'estado_id' => 29, 'nome' => 'Guanambi']);
		DB::table('cidades')->insert(['id' => 2911808, 'estado_id' => 29, 'nome' => 'Guaratinga']);
		DB::table('cidades')->insert(['id' => 2911857, 'estado_id' => 29, 'nome' => 'Heliópolis']);
		DB::table('cidades')->insert(['id' => 2911907, 'estado_id' => 29, 'nome' => 'Iaçu']);
		DB::table('cidades')->insert(['id' => 2912004, 'estado_id' => 29, 'nome' => 'Ibiassucê']);
		DB::table('cidades')->insert(['id' => 2912103, 'estado_id' => 29, 'nome' => 'Ibicaraí']);
		DB::table('cidades')->insert(['id' => 2912202, 'estado_id' => 29, 'nome' => 'Ibicoara']);
		DB::table('cidades')->insert(['id' => 2912301, 'estado_id' => 29, 'nome' => 'Ibicuí']);
		DB::table('cidades')->insert(['id' => 2912400, 'estado_id' => 29, 'nome' => 'Ibipeba']);
		DB::table('cidades')->insert(['id' => 2912509, 'estado_id' => 29, 'nome' => 'Ibipitanga']);
		DB::table('cidades')->insert(['id' => 2912608, 'estado_id' => 29, 'nome' => 'Ibiquera']);
		DB::table('cidades')->insert(['id' => 2912707, 'estado_id' => 29, 'nome' => 'Ibirapitanga']);
		DB::table('cidades')->insert(['id' => 2912806, 'estado_id' => 29, 'nome' => 'Ibirapuã']);
		DB::table('cidades')->insert(['id' => 2912905, 'estado_id' => 29, 'nome' => 'Ibirataia']);
		DB::table('cidades')->insert(['id' => 2913002, 'estado_id' => 29, 'nome' => 'Ibitiara']);
		DB::table('cidades')->insert(['id' => 2913101, 'estado_id' => 29, 'nome' => 'Ibititá']);
		DB::table('cidades')->insert(['id' => 2913200, 'estado_id' => 29, 'nome' => 'Ibotirama']);
		DB::table('cidades')->insert(['id' => 2913309, 'estado_id' => 29, 'nome' => 'Ichu']);
		DB::table('cidades')->insert(['id' => 2913408, 'estado_id' => 29, 'nome' => 'Igaporã']);
		DB::table('cidades')->insert(['id' => 2913457, 'estado_id' => 29, 'nome' => 'Igrapiúna']);
		DB::table('cidades')->insert(['id' => 2913507, 'estado_id' => 29, 'nome' => 'Iguaí']);
		DB::table('cidades')->insert(['id' => 2913606, 'estado_id' => 29, 'nome' => 'Ilhéus']);
		DB::table('cidades')->insert(['id' => 2913705, 'estado_id' => 29, 'nome' => 'Inhambupe']);
		DB::table('cidades')->insert(['id' => 2913804, 'estado_id' => 29, 'nome' => 'Ipecaetá']);
		DB::table('cidades')->insert(['id' => 2913903, 'estado_id' => 29, 'nome' => 'Ipiaú']);
		DB::table('cidades')->insert(['id' => 2914000, 'estado_id' => 29, 'nome' => 'Ipirá']);
		DB::table('cidades')->insert(['id' => 2914109, 'estado_id' => 29, 'nome' => 'Ipupiara']);
		DB::table('cidades')->insert(['id' => 2914208, 'estado_id' => 29, 'nome' => 'Irajuba']);
		DB::table('cidades')->insert(['id' => 2914307, 'estado_id' => 29, 'nome' => 'Iramaia']);
		DB::table('cidades')->insert(['id' => 2914406, 'estado_id' => 29, 'nome' => 'Iraquara']);
		DB::table('cidades')->insert(['id' => 2914505, 'estado_id' => 29, 'nome' => 'Irará']);
		DB::table('cidades')->insert(['id' => 2914604, 'estado_id' => 29, 'nome' => 'Irecê']);
		DB::table('cidades')->insert(['id' => 2914653, 'estado_id' => 29, 'nome' => 'Itabela']);
		DB::table('cidades')->insert(['id' => 2914703, 'estado_id' => 29, 'nome' => 'Itaberaba']);
		DB::table('cidades')->insert(['id' => 2914802, 'estado_id' => 29, 'nome' => 'Itabuna']);
		DB::table('cidades')->insert(['id' => 2914901, 'estado_id' => 29, 'nome' => 'Itacaré']);
		DB::table('cidades')->insert(['id' => 2915007, 'estado_id' => 29, 'nome' => 'Itaeté']);
		DB::table('cidades')->insert(['id' => 2915106, 'estado_id' => 29, 'nome' => 'Itagi']);
		DB::table('cidades')->insert(['id' => 2915205, 'estado_id' => 29, 'nome' => 'Itagibá']);
		DB::table('cidades')->insert(['id' => 2915304, 'estado_id' => 29, 'nome' => 'Itagimirim']);
		DB::table('cidades')->insert(['id' => 2915353, 'estado_id' => 29, 'nome' => 'Itaguaçu da Bahia']);
		DB::table('cidades')->insert(['id' => 2915403, 'estado_id' => 29, 'nome' => 'Itaju do Colônia']);
		DB::table('cidades')->insert(['id' => 2915502, 'estado_id' => 29, 'nome' => 'Itajuípe']);
		DB::table('cidades')->insert(['id' => 2915601, 'estado_id' => 29, 'nome' => 'Itamaraju']);
		DB::table('cidades')->insert(['id' => 2915700, 'estado_id' => 29, 'nome' => 'Itamari']);
		DB::table('cidades')->insert(['id' => 2915809, 'estado_id' => 29, 'nome' => 'Itambé']);
		DB::table('cidades')->insert(['id' => 2915908, 'estado_id' => 29, 'nome' => 'Itanagra']);
		DB::table('cidades')->insert(['id' => 2916005, 'estado_id' => 29, 'nome' => 'Itanhém']);
		DB::table('cidades')->insert(['id' => 2916104, 'estado_id' => 29, 'nome' => 'Itaparica']);
		DB::table('cidades')->insert(['id' => 2916203, 'estado_id' => 29, 'nome' => 'Itapé']);
		DB::table('cidades')->insert(['id' => 2916302, 'estado_id' => 29, 'nome' => 'Itapebi']);
		DB::table('cidades')->insert(['id' => 2916401, 'estado_id' => 29, 'nome' => 'Itapetinga']);
		DB::table('cidades')->insert(['id' => 2916500, 'estado_id' => 29, 'nome' => 'Itapicuru']);
		DB::table('cidades')->insert(['id' => 2916609, 'estado_id' => 29, 'nome' => 'Itapitanga']);
		DB::table('cidades')->insert(['id' => 2916708, 'estado_id' => 29, 'nome' => 'Itaquara']);
		DB::table('cidades')->insert(['id' => 2916807, 'estado_id' => 29, 'nome' => 'Itarantim']);
		DB::table('cidades')->insert(['id' => 2916856, 'estado_id' => 29, 'nome' => 'Itatim']);
		DB::table('cidades')->insert(['id' => 2916906, 'estado_id' => 29, 'nome' => 'Itiruçu']);
		DB::table('cidades')->insert(['id' => 2917003, 'estado_id' => 29, 'nome' => 'Itiúba']);
		DB::table('cidades')->insert(['id' => 2917102, 'estado_id' => 29, 'nome' => 'Itororó']);
		DB::table('cidades')->insert(['id' => 2917201, 'estado_id' => 29, 'nome' => 'Ituaçu']);
		DB::table('cidades')->insert(['id' => 2917300, 'estado_id' => 29, 'nome' => 'Ituberá']);
		DB::table('cidades')->insert(['id' => 2917334, 'estado_id' => 29, 'nome' => 'Iuiú']);
		DB::table('cidades')->insert(['id' => 2917359, 'estado_id' => 29, 'nome' => 'Jaborandi']);
		DB::table('cidades')->insert(['id' => 2917409, 'estado_id' => 29, 'nome' => 'Jacaraci']);
		DB::table('cidades')->insert(['id' => 2917508, 'estado_id' => 29, 'nome' => 'Jacobina']);
		DB::table('cidades')->insert(['id' => 2917607, 'estado_id' => 29, 'nome' => 'Jaguaquara']);
		DB::table('cidades')->insert(['id' => 2917706, 'estado_id' => 29, 'nome' => 'Jaguarari']);
		DB::table('cidades')->insert(['id' => 2917805, 'estado_id' => 29, 'nome' => 'Jaguaripe']);
		DB::table('cidades')->insert(['id' => 2917904, 'estado_id' => 29, 'nome' => 'Jandaíra']);
		DB::table('cidades')->insert(['id' => 2918001, 'estado_id' => 29, 'nome' => 'Jequié']);
		DB::table('cidades')->insert(['id' => 2918100, 'estado_id' => 29, 'nome' => 'Jeremoabo']);
		DB::table('cidades')->insert(['id' => 2918209, 'estado_id' => 29, 'nome' => 'Jiquiriçá']);
		DB::table('cidades')->insert(['id' => 2918308, 'estado_id' => 29, 'nome' => 'Jitaúna']);
		DB::table('cidades')->insert(['id' => 2918357, 'estado_id' => 29, 'nome' => 'João Dourado']);
		DB::table('cidades')->insert(['id' => 2918407, 'estado_id' => 29, 'nome' => 'Juazeiro']);
		DB::table('cidades')->insert(['id' => 2918456, 'estado_id' => 29, 'nome' => 'Jucuruçu']);
		DB::table('cidades')->insert(['id' => 2918506, 'estado_id' => 29, 'nome' => 'Jussara']);
		DB::table('cidades')->insert(['id' => 2918555, 'estado_id' => 29, 'nome' => 'Jussari']);
		DB::table('cidades')->insert(['id' => 2918605, 'estado_id' => 29, 'nome' => 'Jussiape']);
		DB::table('cidades')->insert(['id' => 2918704, 'estado_id' => 29, 'nome' => 'Lafaiete Coutinho']);
		DB::table('cidades')->insert(['id' => 2918753, 'estado_id' => 29, 'nome' => 'Lagoa Real']);
		DB::table('cidades')->insert(['id' => 2918803, 'estado_id' => 29, 'nome' => 'Laje']);
		DB::table('cidades')->insert(['id' => 2918902, 'estado_id' => 29, 'nome' => 'Lajedão']);
		DB::table('cidades')->insert(['id' => 2919009, 'estado_id' => 29, 'nome' => 'Lajedinho']);
		DB::table('cidades')->insert(['id' => 2919058, 'estado_id' => 29, 'nome' => 'Lajedo do Tabocal']);
		DB::table('cidades')->insert(['id' => 2919108, 'estado_id' => 29, 'nome' => 'Lamarão']);
		DB::table('cidades')->insert(['id' => 2919157, 'estado_id' => 29, 'nome' => 'Lapão']);
		DB::table('cidades')->insert(['id' => 2919207, 'estado_id' => 29, 'nome' => 'Lauro de Freitas']);
		DB::table('cidades')->insert(['id' => 2919306, 'estado_id' => 29, 'nome' => 'Lençóis']);
		DB::table('cidades')->insert(['id' => 2919405, 'estado_id' => 29, 'nome' => 'Licínio de Almeida']);
		DB::table('cidades')->insert(['id' => 2919504, 'estado_id' => 29, 'nome' => 'Livramento de Nossa Senhora']);
		DB::table('cidades')->insert(['id' => 2919553, 'estado_id' => 29, 'nome' => 'Luís Eduardo Magalhães']);
		DB::table('cidades')->insert(['id' => 2919603, 'estado_id' => 29, 'nome' => 'Macajuba']);
		DB::table('cidades')->insert(['id' => 2919702, 'estado_id' => 29, 'nome' => 'Macarani']);
		DB::table('cidades')->insert(['id' => 2919801, 'estado_id' => 29, 'nome' => 'Macaúbas']);
		DB::table('cidades')->insert(['id' => 2919900, 'estado_id' => 29, 'nome' => 'Macururé']);
		DB::table('cidades')->insert(['id' => 2919926, 'estado_id' => 29, 'nome' => 'Madre de Deus']);
		DB::table('cidades')->insert(['id' => 2919959, 'estado_id' => 29, 'nome' => 'Maetinga']);
		DB::table('cidades')->insert(['id' => 2920007, 'estado_id' => 29, 'nome' => 'Maiquinique']);
		DB::table('cidades')->insert(['id' => 2920106, 'estado_id' => 29, 'nome' => 'Mairi']);
		DB::table('cidades')->insert(['id' => 2920205, 'estado_id' => 29, 'nome' => 'Malhada']);
		DB::table('cidades')->insert(['id' => 2920304, 'estado_id' => 29, 'nome' => 'Malhada de Pedras']);
		DB::table('cidades')->insert(['id' => 2920403, 'estado_id' => 29, 'nome' => 'Manoel Vitorino']);
		DB::table('cidades')->insert(['id' => 2920452, 'estado_id' => 29, 'nome' => 'Mansidão']);
		DB::table('cidades')->insert(['id' => 2920502, 'estado_id' => 29, 'nome' => 'Maracás']);
		DB::table('cidades')->insert(['id' => 2920601, 'estado_id' => 29, 'nome' => 'Maragogipe']);
		DB::table('cidades')->insert(['id' => 2920700, 'estado_id' => 29, 'nome' => 'Maraú']);
		DB::table('cidades')->insert(['id' => 2920809, 'estado_id' => 29, 'nome' => 'Marcionílio Souza']);
		DB::table('cidades')->insert(['id' => 2920908, 'estado_id' => 29, 'nome' => 'Mascote']);
		DB::table('cidades')->insert(['id' => 2921005, 'estado_id' => 29, 'nome' => 'Mata de São João']);
		DB::table('cidades')->insert(['id' => 2921054, 'estado_id' => 29, 'nome' => 'Matina']);
		DB::table('cidades')->insert(['id' => 2921104, 'estado_id' => 29, 'nome' => 'Medeiros Neto']);
		DB::table('cidades')->insert(['id' => 2921203, 'estado_id' => 29, 'nome' => 'Miguel Calmon']);
		DB::table('cidades')->insert(['id' => 2921302, 'estado_id' => 29, 'nome' => 'Milagres']);
		DB::table('cidades')->insert(['id' => 2921401, 'estado_id' => 29, 'nome' => 'Mirangaba']);
		DB::table('cidades')->insert(['id' => 2921450, 'estado_id' => 29, 'nome' => 'Mirante']);
		DB::table('cidades')->insert(['id' => 2921500, 'estado_id' => 29, 'nome' => 'Monte Santo']);
		DB::table('cidades')->insert(['id' => 2921609, 'estado_id' => 29, 'nome' => 'Morpará']);
		DB::table('cidades')->insert(['id' => 2921708, 'estado_id' => 29, 'nome' => 'Morro do Chapéu']);
		DB::table('cidades')->insert(['id' => 2921807, 'estado_id' => 29, 'nome' => 'Mortugaba']);
		DB::table('cidades')->insert(['id' => 2921906, 'estado_id' => 29, 'nome' => 'Mucugê']);
		DB::table('cidades')->insert(['id' => 2922003, 'estado_id' => 29, 'nome' => 'Mucuri']);
		DB::table('cidades')->insert(['id' => 2922052, 'estado_id' => 29, 'nome' => 'Mulungu do Morro']);
		DB::table('cidades')->insert(['id' => 2922102, 'estado_id' => 29, 'nome' => 'Mundo Novo']);
		DB::table('cidades')->insert(['id' => 2922201, 'estado_id' => 29, 'nome' => 'Muniz Ferreira']);
		DB::table('cidades')->insert(['id' => 2922250, 'estado_id' => 29, 'nome' => 'Muquém de São Francisco']);
		DB::table('cidades')->insert(['id' => 2922300, 'estado_id' => 29, 'nome' => 'Muritiba']);
		DB::table('cidades')->insert(['id' => 2922409, 'estado_id' => 29, 'nome' => 'Mutuípe']);
		DB::table('cidades')->insert(['id' => 2922508, 'estado_id' => 29, 'nome' => 'Nazaré']);
		DB::table('cidades')->insert(['id' => 2922607, 'estado_id' => 29, 'nome' => 'Nilo Peçanha']);
		DB::table('cidades')->insert(['id' => 2922656, 'estado_id' => 29, 'nome' => 'Nordestina']);
		DB::table('cidades')->insert(['id' => 2922706, 'estado_id' => 29, 'nome' => 'Nova Canaã']);
		DB::table('cidades')->insert(['id' => 2922730, 'estado_id' => 29, 'nome' => 'Nova Fátima']);
		DB::table('cidades')->insert(['id' => 2922755, 'estado_id' => 29, 'nome' => 'Nova Ibiá']);
		DB::table('cidades')->insert(['id' => 2922805, 'estado_id' => 29, 'nome' => 'Nova Itarana']);
		DB::table('cidades')->insert(['id' => 2922854, 'estado_id' => 29, 'nome' => 'Nova Redenção']);
		DB::table('cidades')->insert(['id' => 2922904, 'estado_id' => 29, 'nome' => 'Nova Soure']);
		DB::table('cidades')->insert(['id' => 2923001, 'estado_id' => 29, 'nome' => 'Nova Viçosa']);
		DB::table('cidades')->insert(['id' => 2923035, 'estado_id' => 29, 'nome' => 'Novo Horizonte']);
		DB::table('cidades')->insert(['id' => 2923050, 'estado_id' => 29, 'nome' => 'Novo Triunfo']);
		DB::table('cidades')->insert(['id' => 2923100, 'estado_id' => 29, 'nome' => 'Olindina']);
		DB::table('cidades')->insert(['id' => 2923209, 'estado_id' => 29, 'nome' => 'Oliveira dos Brejinhos']);
		DB::table('cidades')->insert(['id' => 2923308, 'estado_id' => 29, 'nome' => 'Ouriçangas']);
		DB::table('cidades')->insert(['id' => 2923357, 'estado_id' => 29, 'nome' => 'Ourolândia']);
		DB::table('cidades')->insert(['id' => 2923407, 'estado_id' => 29, 'nome' => 'Palmas de Monte Alto']);
		DB::table('cidades')->insert(['id' => 2923506, 'estado_id' => 29, 'nome' => 'Palmeiras']);
		DB::table('cidades')->insert(['id' => 2923605, 'estado_id' => 29, 'nome' => 'Paramirim']);
		DB::table('cidades')->insert(['id' => 2923704, 'estado_id' => 29, 'nome' => 'Paratinga']);
		DB::table('cidades')->insert(['id' => 2923803, 'estado_id' => 29, 'nome' => 'Paripiranga']);
		DB::table('cidades')->insert(['id' => 2923902, 'estado_id' => 29, 'nome' => 'Pau Brasil']);
		DB::table('cidades')->insert(['id' => 2924009, 'estado_id' => 29, 'nome' => 'Paulo Afonso']);
		DB::table('cidades')->insert(['id' => 2924058, 'estado_id' => 29, 'nome' => 'Pé de Serra']);
		DB::table('cidades')->insert(['id' => 2924108, 'estado_id' => 29, 'nome' => 'Pedrão']);
		DB::table('cidades')->insert(['id' => 2924207, 'estado_id' => 29, 'nome' => 'Pedro Alexandre']);
		DB::table('cidades')->insert(['id' => 2924306, 'estado_id' => 29, 'nome' => 'Piatã']);
		DB::table('cidades')->insert(['id' => 2924405, 'estado_id' => 29, 'nome' => 'Pilão Arcado']);
		DB::table('cidades')->insert(['id' => 2924504, 'estado_id' => 29, 'nome' => 'Pindaí']);
		DB::table('cidades')->insert(['id' => 2924603, 'estado_id' => 29, 'nome' => 'Pindobaçu']);
		DB::table('cidades')->insert(['id' => 2924652, 'estado_id' => 29, 'nome' => 'Pintadas']);
		DB::table('cidades')->insert(['id' => 2924678, 'estado_id' => 29, 'nome' => 'Piraí do Norte']);
		DB::table('cidades')->insert(['id' => 2924702, 'estado_id' => 29, 'nome' => 'Piripá']);
		DB::table('cidades')->insert(['id' => 2924801, 'estado_id' => 29, 'nome' => 'Piritiba']);
		DB::table('cidades')->insert(['id' => 2924900, 'estado_id' => 29, 'nome' => 'Planaltino']);
		DB::table('cidades')->insert(['id' => 2925006, 'estado_id' => 29, 'nome' => 'Planalto']);
		DB::table('cidades')->insert(['id' => 2925105, 'estado_id' => 29, 'nome' => 'Poções']);
		DB::table('cidades')->insert(['id' => 2925204, 'estado_id' => 29, 'nome' => 'Pojuca']);
		DB::table('cidades')->insert(['id' => 2925253, 'estado_id' => 29, 'nome' => 'Ponto Novo']);
		DB::table('cidades')->insert(['id' => 2925303, 'estado_id' => 29, 'nome' => 'Porto Seguro']);
		DB::table('cidades')->insert(['id' => 2925402, 'estado_id' => 29, 'nome' => 'Potiraguá']);
		DB::table('cidades')->insert(['id' => 2925501, 'estado_id' => 29, 'nome' => 'Prado']);
		DB::table('cidades')->insert(['id' => 2925600, 'estado_id' => 29, 'nome' => 'Presidente Dutra']);
		DB::table('cidades')->insert(['id' => 2925709, 'estado_id' => 29, 'nome' => 'Presidente Jânio Quadros']);
		DB::table('cidades')->insert(['id' => 2925758, 'estado_id' => 29, 'nome' => 'Presidente Tancredo Neves']);
		DB::table('cidades')->insert(['id' => 2925808, 'estado_id' => 29, 'nome' => 'Queimadas']);
		DB::table('cidades')->insert(['id' => 2925907, 'estado_id' => 29, 'nome' => 'Quijingue']);
		DB::table('cidades')->insert(['id' => 2925931, 'estado_id' => 29, 'nome' => 'Quixabeira']);
		DB::table('cidades')->insert(['id' => 2925956, 'estado_id' => 29, 'nome' => 'Rafael Jambeiro']);
		DB::table('cidades')->insert(['id' => 2926004, 'estado_id' => 29, 'nome' => 'Remanso']);
		DB::table('cidades')->insert(['id' => 2926103, 'estado_id' => 29, 'nome' => 'Retirolândia']);
		DB::table('cidades')->insert(['id' => 2926202, 'estado_id' => 29, 'nome' => 'Riachão das Neves']);
		DB::table('cidades')->insert(['id' => 2926301, 'estado_id' => 29, 'nome' => 'Riachão do Jacuípe']);
		DB::table('cidades')->insert(['id' => 2926400, 'estado_id' => 29, 'nome' => 'Riacho de Santana']);
		DB::table('cidades')->insert(['id' => 2926509, 'estado_id' => 29, 'nome' => 'Ribeira do Amparo']);
		DB::table('cidades')->insert(['id' => 2926608, 'estado_id' => 29, 'nome' => 'Ribeira do Pombal']);
		DB::table('cidades')->insert(['id' => 2926657, 'estado_id' => 29, 'nome' => 'Ribeirão do Largo']);
		DB::table('cidades')->insert(['id' => 2926707, 'estado_id' => 29, 'nome' => 'Rio de Contas']);
		DB::table('cidades')->insert(['id' => 2926806, 'estado_id' => 29, 'nome' => 'Rio do Antônio']);
		DB::table('cidades')->insert(['id' => 2926905, 'estado_id' => 29, 'nome' => 'Rio do Pires']);
		DB::table('cidades')->insert(['id' => 2927002, 'estado_id' => 29, 'nome' => 'Rio Real']);
		DB::table('cidades')->insert(['id' => 2927101, 'estado_id' => 29, 'nome' => 'Rodelas']);
		DB::table('cidades')->insert(['id' => 2927200, 'estado_id' => 29, 'nome' => 'Ruy Barbosa']);
		DB::table('cidades')->insert(['id' => 2927309, 'estado_id' => 29, 'nome' => 'Salinas da Margarida']);
		DB::table('cidades')->insert(['id' => 2927408, 'estado_id' => 29, 'nome' => 'Salvador']);
		DB::table('cidades')->insert(['id' => 2927507, 'estado_id' => 29, 'nome' => 'Santa Bárbara']);
		DB::table('cidades')->insert(['id' => 2927606, 'estado_id' => 29, 'nome' => 'Santa Brígida']);
		DB::table('cidades')->insert(['id' => 2927705, 'estado_id' => 29, 'nome' => 'Santa Cruz Cabrália']);
		DB::table('cidades')->insert(['id' => 2927804, 'estado_id' => 29, 'nome' => 'Santa Cruz da Vitória']);
		DB::table('cidades')->insert(['id' => 2927903, 'estado_id' => 29, 'nome' => 'Santa Inês']);
		DB::table('cidades')->insert(['id' => 2928000, 'estado_id' => 29, 'nome' => 'Santaluz']);
		DB::table('cidades')->insert(['id' => 2928059, 'estado_id' => 29, 'nome' => 'Santa Luzia']);
		DB::table('cidades')->insert(['id' => 2928109, 'estado_id' => 29, 'nome' => 'Santa Maria da Vitória']);
		DB::table('cidades')->insert(['id' => 2928208, 'estado_id' => 29, 'nome' => 'Santana']);
		DB::table('cidades')->insert(['id' => 2928307, 'estado_id' => 29, 'nome' => 'Santanópolis']);
		DB::table('cidades')->insert(['id' => 2928406, 'estado_id' => 29, 'nome' => 'Santa Rita de Cássia']);
		DB::table('cidades')->insert(['id' => 2928505, 'estado_id' => 29, 'nome' => 'Santa Teresinha']);
		DB::table('cidades')->insert(['id' => 2928604, 'estado_id' => 29, 'nome' => 'Santo Amaro']);
		DB::table('cidades')->insert(['id' => 2928703, 'estado_id' => 29, 'nome' => 'Santo Antônio de Jesus']);
		DB::table('cidades')->insert(['id' => 2928802, 'estado_id' => 29, 'nome' => 'Santo Estêvão']);
		DB::table('cidades')->insert(['id' => 2928901, 'estado_id' => 29, 'nome' => 'São Desidério']);
		DB::table('cidades')->insert(['id' => 2928950, 'estado_id' => 29, 'nome' => 'São Domingos']);
		DB::table('cidades')->insert(['id' => 2929008, 'estado_id' => 29, 'nome' => 'São Félix']);
		DB::table('cidades')->insert(['id' => 2929057, 'estado_id' => 29, 'nome' => 'São Félix do Coribe']);
		DB::table('cidades')->insert(['id' => 2929107, 'estado_id' => 29, 'nome' => 'São Felipe']);
		DB::table('cidades')->insert(['id' => 2929206, 'estado_id' => 29, 'nome' => 'São Francisco do Conde']);
		DB::table('cidades')->insert(['id' => 2929255, 'estado_id' => 29, 'nome' => 'São Gabriel']);
		DB::table('cidades')->insert(['id' => 2929305, 'estado_id' => 29, 'nome' => 'São Gonçalo dos Campos']);
		DB::table('cidades')->insert(['id' => 2929354, 'estado_id' => 29, 'nome' => 'São José da Vitória']);
		DB::table('cidades')->insert(['id' => 2929370, 'estado_id' => 29, 'nome' => 'São José do Jacuípe']);
		DB::table('cidades')->insert(['id' => 2929404, 'estado_id' => 29, 'nome' => 'São Miguel das Matas']);
		DB::table('cidades')->insert(['id' => 2929503, 'estado_id' => 29, 'nome' => 'São Sebastião do Passé']);
		DB::table('cidades')->insert(['id' => 2929602, 'estado_id' => 29, 'nome' => 'Sapeaçu']);
		DB::table('cidades')->insert(['id' => 2929701, 'estado_id' => 29, 'nome' => 'Sátiro Dias']);
		DB::table('cidades')->insert(['id' => 2929750, 'estado_id' => 29, 'nome' => 'Saubara']);
		DB::table('cidades')->insert(['id' => 2929800, 'estado_id' => 29, 'nome' => 'Saúde']);
		DB::table('cidades')->insert(['id' => 2929909, 'estado_id' => 29, 'nome' => 'Seabra']);
		DB::table('cidades')->insert(['id' => 2930006, 'estado_id' => 29, 'nome' => 'Sebastião Laranjeiras']);
		DB::table('cidades')->insert(['id' => 2930105, 'estado_id' => 29, 'nome' => 'Senhor do Bonfim']);
		DB::table('cidades')->insert(['id' => 2930154, 'estado_id' => 29, 'nome' => 'Serra do Ramalho']);
		DB::table('cidades')->insert(['id' => 2930204, 'estado_id' => 29, 'nome' => 'Sento Sé']);
		DB::table('cidades')->insert(['id' => 2930303, 'estado_id' => 29, 'nome' => 'Serra Dourada']);
		DB::table('cidades')->insert(['id' => 2930402, 'estado_id' => 29, 'nome' => 'Serra Preta']);
		DB::table('cidades')->insert(['id' => 2930501, 'estado_id' => 29, 'nome' => 'Serrinha']);
		DB::table('cidades')->insert(['id' => 2930600, 'estado_id' => 29, 'nome' => 'Serrolândia']);
		DB::table('cidades')->insert(['id' => 2930709, 'estado_id' => 29, 'nome' => 'Simões Filho']);
		DB::table('cidades')->insert(['id' => 2930758, 'estado_id' => 29, 'nome' => 'Sítio do Mato']);
		DB::table('cidades')->insert(['id' => 2930766, 'estado_id' => 29, 'nome' => 'Sítio do Quinto']);
		DB::table('cidades')->insert(['id' => 2930774, 'estado_id' => 29, 'nome' => 'Sobradinho']);
		DB::table('cidades')->insert(['id' => 2930808, 'estado_id' => 29, 'nome' => 'Souto Soares']);
		DB::table('cidades')->insert(['id' => 2930907, 'estado_id' => 29, 'nome' => 'Tabocas do Brejo Velho']);
		DB::table('cidades')->insert(['id' => 2931004, 'estado_id' => 29, 'nome' => 'Tanhaçu']);
		DB::table('cidades')->insert(['id' => 2931053, 'estado_id' => 29, 'nome' => 'Tanque Novo']);
		DB::table('cidades')->insert(['id' => 2931103, 'estado_id' => 29, 'nome' => 'Tanquinho']);
		DB::table('cidades')->insert(['id' => 2931202, 'estado_id' => 29, 'nome' => 'Taperoá']);
		DB::table('cidades')->insert(['id' => 2931301, 'estado_id' => 29, 'nome' => 'Tapiramutá']);
		DB::table('cidades')->insert(['id' => 2931350, 'estado_id' => 29, 'nome' => 'Teixeira de Freitas']);
		DB::table('cidades')->insert(['id' => 2931400, 'estado_id' => 29, 'nome' => 'Teodoro Sampaio']);
		DB::table('cidades')->insert(['id' => 2931509, 'estado_id' => 29, 'nome' => 'Teofilândia']);
		DB::table('cidades')->insert(['id' => 2931608, 'estado_id' => 29, 'nome' => 'Teolândia']);
		DB::table('cidades')->insert(['id' => 2931707, 'estado_id' => 29, 'nome' => 'Terra Nova']);
		DB::table('cidades')->insert(['id' => 2931806, 'estado_id' => 29, 'nome' => 'Tremedal']);
		DB::table('cidades')->insert(['id' => 2931905, 'estado_id' => 29, 'nome' => 'Tucano']);
		DB::table('cidades')->insert(['id' => 2932002, 'estado_id' => 29, 'nome' => 'Uauá']);
		DB::table('cidades')->insert(['id' => 2932101, 'estado_id' => 29, 'nome' => 'Ubaíra']);
		DB::table('cidades')->insert(['id' => 2932200, 'estado_id' => 29, 'nome' => 'Ubaitaba']);
		DB::table('cidades')->insert(['id' => 2932309, 'estado_id' => 29, 'nome' => 'Ubatã']);
		DB::table('cidades')->insert(['id' => 2932408, 'estado_id' => 29, 'nome' => 'Uibaí']);
		DB::table('cidades')->insert(['id' => 2932457, 'estado_id' => 29, 'nome' => 'Umburanas']);
		DB::table('cidades')->insert(['id' => 2932507, 'estado_id' => 29, 'nome' => 'Una']);
		DB::table('cidades')->insert(['id' => 2932606, 'estado_id' => 29, 'nome' => 'Urandi']);
		DB::table('cidades')->insert(['id' => 2932705, 'estado_id' => 29, 'nome' => 'Uruçuca']);
		DB::table('cidades')->insert(['id' => 2932804, 'estado_id' => 29, 'nome' => 'Utinga']);
		DB::table('cidades')->insert(['id' => 2932903, 'estado_id' => 29, 'nome' => 'Valença']);
		DB::table('cidades')->insert(['id' => 2933000, 'estado_id' => 29, 'nome' => 'Valente']);
		DB::table('cidades')->insert(['id' => 2933059, 'estado_id' => 29, 'nome' => 'Várzea da Roça']);
		DB::table('cidades')->insert(['id' => 2933109, 'estado_id' => 29, 'nome' => 'Várzea do Poço']);
		DB::table('cidades')->insert(['id' => 2933158, 'estado_id' => 29, 'nome' => 'Várzea Nova']);
		DB::table('cidades')->insert(['id' => 2933174, 'estado_id' => 29, 'nome' => 'Varzedo']);
		DB::table('cidades')->insert(['id' => 2933208, 'estado_id' => 29, 'nome' => 'Vera Cruz']);
		DB::table('cidades')->insert(['id' => 2933257, 'estado_id' => 29, 'nome' => 'Vereda']);
		DB::table('cidades')->insert(['id' => 2933307, 'estado_id' => 29, 'nome' => 'Vitória da Conquista']);
		DB::table('cidades')->insert(['id' => 2933406, 'estado_id' => 29, 'nome' => 'Wagner']);
		DB::table('cidades')->insert(['id' => 2933455, 'estado_id' => 29, 'nome' => 'Wanderley']);
		DB::table('cidades')->insert(['id' => 2933505, 'estado_id' => 29, 'nome' => 'Wenceslau Guimarães']);
		DB::table('cidades')->insert(['id' => 2933604, 'estado_id' => 29, 'nome' => 'Xique-Xique']);
    }
}
