<?php

use Illuminate\Database\Seeder;

class CidadesTablePESeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades de Pernambuco
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    DB::table('cidades')->insert(['id' => 2600054, 'estado_id' => 26, 'nome' => 'Abreu e Lima']);
	DB::table('cidades')->insert(['id' => 2600104, 'estado_id' => 26, 'nome' => 'Afogados da Ingazeira']);
	DB::table('cidades')->insert(['id' => 2600203, 'estado_id' => 26, 'nome' => 'Afrânio']);
	DB::table('cidades')->insert(['id' => 2600302, 'estado_id' => 26, 'nome' => 'Agrestina']);
	DB::table('cidades')->insert(['id' => 2600401, 'estado_id' => 26, 'nome' => 'Água Preta']);
	DB::table('cidades')->insert(['id' => 2600500, 'estado_id' => 26, 'nome' => 'Águas Belas']);
	DB::table('cidades')->insert(['id' => 2600609, 'estado_id' => 26, 'nome' => 'Alagoinha']);
	DB::table('cidades')->insert(['id' => 2600708, 'estado_id' => 26, 'nome' => 'Aliança']);
	DB::table('cidades')->insert(['id' => 2600807, 'estado_id' => 26, 'nome' => 'Altinho']);
	DB::table('cidades')->insert(['id' => 2600906, 'estado_id' => 26, 'nome' => 'Amaraji']);
	DB::table('cidades')->insert(['id' => 2601003, 'estado_id' => 26, 'nome' => 'Angelim']);
	DB::table('cidades')->insert(['id' => 2601052, 'estado_id' => 26, 'nome' => 'Araçoiaba']);
	DB::table('cidades')->insert(['id' => 2601102, 'estado_id' => 26, 'nome' => 'Araripina']);
	DB::table('cidades')->insert(['id' => 2601201, 'estado_id' => 26, 'nome' => 'Arcoverde']);
	DB::table('cidades')->insert(['id' => 2601300, 'estado_id' => 26, 'nome' => 'Barra de Guabiraba']);
	DB::table('cidades')->insert(['id' => 2601409, 'estado_id' => 26, 'nome' => 'Barreiros']);
	DB::table('cidades')->insert(['id' => 2601508, 'estado_id' => 26, 'nome' => 'Belém de Maria']);
	DB::table('cidades')->insert(['id' => 2601607, 'estado_id' => 26, 'nome' => 'Belém de São Francisco']);
	DB::table('cidades')->insert(['id' => 2601706, 'estado_id' => 26, 'nome' => 'Belo Jardim']);
	DB::table('cidades')->insert(['id' => 2601805, 'estado_id' => 26, 'nome' => 'Betânia']);
	DB::table('cidades')->insert(['id' => 2601904, 'estado_id' => 26, 'nome' => 'Bezerros']);
	DB::table('cidades')->insert(['id' => 2602001, 'estado_id' => 26, 'nome' => 'Bodocó']);
	DB::table('cidades')->insert(['id' => 2602100, 'estado_id' => 26, 'nome' => 'Bom Conselho']);
	DB::table('cidades')->insert(['id' => 2602209, 'estado_id' => 26, 'nome' => 'Bom Jardim']);
	DB::table('cidades')->insert(['id' => 2602308, 'estado_id' => 26, 'nome' => 'Bonito']);
	DB::table('cidades')->insert(['id' => 2602407, 'estado_id' => 26, 'nome' => 'Brejão']);
	DB::table('cidades')->insert(['id' => 2602506, 'estado_id' => 26, 'nome' => 'Brejinho']);
	DB::table('cidades')->insert(['id' => 2602605, 'estado_id' => 26, 'nome' => 'Brejo da Madre de Deus']);
	DB::table('cidades')->insert(['id' => 2602704, 'estado_id' => 26, 'nome' => 'Buenos Aires']);
	DB::table('cidades')->insert(['id' => 2602803, 'estado_id' => 26, 'nome' => 'Buíque']);
	DB::table('cidades')->insert(['id' => 2602902, 'estado_id' => 26, 'nome' => 'Cabo de Santo Agostinho']);
	DB::table('cidades')->insert(['id' => 2603009, 'estado_id' => 26, 'nome' => 'Cabrobó']);
	DB::table('cidades')->insert(['id' => 2603108, 'estado_id' => 26, 'nome' => 'Cachoeirinha']);
	DB::table('cidades')->insert(['id' => 2603207, 'estado_id' => 26, 'nome' => 'Caetés']);
	DB::table('cidades')->insert(['id' => 2603306, 'estado_id' => 26, 'nome' => 'Calçado']);
	DB::table('cidades')->insert(['id' => 2603405, 'estado_id' => 26, 'nome' => 'Calumbi']);
	DB::table('cidades')->insert(['id' => 2603454, 'estado_id' => 26, 'nome' => 'Camaragibe']);
	DB::table('cidades')->insert(['id' => 2603504, 'estado_id' => 26, 'nome' => 'Camocim de São Félix']);
	DB::table('cidades')->insert(['id' => 2603603, 'estado_id' => 26, 'nome' => 'Camutanga']);
	DB::table('cidades')->insert(['id' => 2603702, 'estado_id' => 26, 'nome' => 'Canhotinho']);
	DB::table('cidades')->insert(['id' => 2603801, 'estado_id' => 26, 'nome' => 'Capoeiras']);
	DB::table('cidades')->insert(['id' => 2603900, 'estado_id' => 26, 'nome' => 'Carnaíba']);
	DB::table('cidades')->insert(['id' => 2603926, 'estado_id' => 26, 'nome' => 'Carnaubeira da Penha']);
	DB::table('cidades')->insert(['id' => 2604007, 'estado_id' => 26, 'nome' => 'Carpina']);
	DB::table('cidades')->insert(['id' => 2604106, 'estado_id' => 26, 'nome' => 'Caruaru']);
	DB::table('cidades')->insert(['id' => 2604155, 'estado_id' => 26, 'nome' => 'Casinhas']);
	DB::table('cidades')->insert(['id' => 2604205, 'estado_id' => 26, 'nome' => 'Catende']);
	DB::table('cidades')->insert(['id' => 2604304, 'estado_id' => 26, 'nome' => 'Cedro']);
	DB::table('cidades')->insert(['id' => 2604403, 'estado_id' => 26, 'nome' => 'Chã de Alegria']);
	DB::table('cidades')->insert(['id' => 2604502, 'estado_id' => 26, 'nome' => 'Chã Grande']);
	DB::table('cidades')->insert(['id' => 2604601, 'estado_id' => 26, 'nome' => 'Condado']);
	DB::table('cidades')->insert(['id' => 2604700, 'estado_id' => 26, 'nome' => 'Correntes']);
	DB::table('cidades')->insert(['id' => 2604809, 'estado_id' => 26, 'nome' => 'Cortês']);
	DB::table('cidades')->insert(['id' => 2604908, 'estado_id' => 26, 'nome' => 'Cumaru']);
	DB::table('cidades')->insert(['id' => 2605004, 'estado_id' => 26, 'nome' => 'Cupira']);
	DB::table('cidades')->insert(['id' => 2605103, 'estado_id' => 26, 'nome' => 'Custódia']);
	DB::table('cidades')->insert(['id' => 2605152, 'estado_id' => 26, 'nome' => 'Dormentes']);
	DB::table('cidades')->insert(['id' => 2605202, 'estado_id' => 26, 'nome' => 'Escada']);
	DB::table('cidades')->insert(['id' => 2605301, 'estado_id' => 26, 'nome' => 'Exu']);
	DB::table('cidades')->insert(['id' => 2605400, 'estado_id' => 26, 'nome' => 'Feira Nova']);
	DB::table('cidades')->insert(['id' => 2605459, 'estado_id' => 26, 'nome' => 'Fernando de Noronha']);
	DB::table('cidades')->insert(['id' => 2605509, 'estado_id' => 26, 'nome' => 'Ferreiros']);
	DB::table('cidades')->insert(['id' => 2605608, 'estado_id' => 26, 'nome' => 'Flores']);
	DB::table('cidades')->insert(['id' => 2605707, 'estado_id' => 26, 'nome' => 'Floresta']);
	DB::table('cidades')->insert(['id' => 2605806, 'estado_id' => 26, 'nome' => 'Frei Miguelinho']);
	DB::table('cidades')->insert(['id' => 2605905, 'estado_id' => 26, 'nome' => 'Gameleira']);
	DB::table('cidades')->insert(['id' => 2606002, 'estado_id' => 26, 'nome' => 'Garanhuns']);
	DB::table('cidades')->insert(['id' => 2606101, 'estado_id' => 26, 'nome' => 'Glória do Goitá']);
	DB::table('cidades')->insert(['id' => 2606200, 'estado_id' => 26, 'nome' => 'Goiana']);
	DB::table('cidades')->insert(['id' => 2606309, 'estado_id' => 26, 'nome' => 'Granito']);
	DB::table('cidades')->insert(['id' => 2606408, 'estado_id' => 26, 'nome' => 'Gravatá']);
	DB::table('cidades')->insert(['id' => 2606507, 'estado_id' => 26, 'nome' => 'Iati']);
	DB::table('cidades')->insert(['id' => 2606606, 'estado_id' => 26, 'nome' => 'Ibimirim']);
	DB::table('cidades')->insert(['id' => 2606705, 'estado_id' => 26, 'nome' => 'Ibirajuba']);
	DB::table('cidades')->insert(['id' => 2606804, 'estado_id' => 26, 'nome' => 'Igarassu']);
	DB::table('cidades')->insert(['id' => 2606903, 'estado_id' => 26, 'nome' => 'Iguaraci']);
	DB::table('cidades')->insert(['id' => 2607000, 'estado_id' => 26, 'nome' => 'Inajá']);
	DB::table('cidades')->insert(['id' => 2607109, 'estado_id' => 26, 'nome' => 'Ingazeira']);
	DB::table('cidades')->insert(['id' => 2607208, 'estado_id' => 26, 'nome' => 'Ipojuca']);
	DB::table('cidades')->insert(['id' => 2607307, 'estado_id' => 26, 'nome' => 'Ipubi']);
	DB::table('cidades')->insert(['id' => 2607406, 'estado_id' => 26, 'nome' => 'Itacuruba']);
	DB::table('cidades')->insert(['id' => 2607505, 'estado_id' => 26, 'nome' => 'Itaíba']);
	DB::table('cidades')->insert(['id' => 2607604, 'estado_id' => 26, 'nome' => 'Ilha de Itamaracá']);
	DB::table('cidades')->insert(['id' => 2607653, 'estado_id' => 26, 'nome' => 'Itambé']);
	DB::table('cidades')->insert(['id' => 2607703, 'estado_id' => 26, 'nome' => 'Itapetim']);
	DB::table('cidades')->insert(['id' => 2607752, 'estado_id' => 26, 'nome' => 'Itapissuma']);
	DB::table('cidades')->insert(['id' => 2607802, 'estado_id' => 26, 'nome' => 'Itaquitinga']);
	DB::table('cidades')->insert(['id' => 2607901, 'estado_id' => 26, 'nome' => 'Jaboatão dos Guararapes']);
	DB::table('cidades')->insert(['id' => 2607950, 'estado_id' => 26, 'nome' => 'Jaqueira']);
	DB::table('cidades')->insert(['id' => 2608008, 'estado_id' => 26, 'nome' => 'Jataúba']);
	DB::table('cidades')->insert(['id' => 2608057, 'estado_id' => 26, 'nome' => 'Jatobá']);
	DB::table('cidades')->insert(['id' => 2608107, 'estado_id' => 26, 'nome' => 'João Alfredo']);
	DB::table('cidades')->insert(['id' => 2608206, 'estado_id' => 26, 'nome' => 'Joaquim Nabuco']);
	DB::table('cidades')->insert(['id' => 2608255, 'estado_id' => 26, 'nome' => 'Jucati']);
	DB::table('cidades')->insert(['id' => 2608305, 'estado_id' => 26, 'nome' => 'Jupi']);
	DB::table('cidades')->insert(['id' => 2608404, 'estado_id' => 26, 'nome' => 'Jurema']);
	DB::table('cidades')->insert(['id' => 2608453, 'estado_id' => 26, 'nome' => 'Lagoa do Carro']);
	DB::table('cidades')->insert(['id' => 2608503, 'estado_id' => 26, 'nome' => 'Lagoa do Itaenga']);
	DB::table('cidades')->insert(['id' => 2608602, 'estado_id' => 26, 'nome' => 'Lagoa do Ouro']);
	DB::table('cidades')->insert(['id' => 2608701, 'estado_id' => 26, 'nome' => 'Lagoa dos Gatos']);
	DB::table('cidades')->insert(['id' => 2608750, 'estado_id' => 26, 'nome' => 'Lagoa Grande']);
	DB::table('cidades')->insert(['id' => 2608800, 'estado_id' => 26, 'nome' => 'Lajedo']);
	DB::table('cidades')->insert(['id' => 2608909, 'estado_id' => 26, 'nome' => 'Limoeiro']);
	DB::table('cidades')->insert(['id' => 2609006, 'estado_id' => 26, 'nome' => 'Macaparana']);
	DB::table('cidades')->insert(['id' => 2609105, 'estado_id' => 26, 'nome' => 'Machados']);
	DB::table('cidades')->insert(['id' => 2609154, 'estado_id' => 26, 'nome' => 'Manari']);
	DB::table('cidades')->insert(['id' => 2609204, 'estado_id' => 26, 'nome' => 'Maraial']);
	DB::table('cidades')->insert(['id' => 2609303, 'estado_id' => 26, 'nome' => 'Mirandiba']);
	DB::table('cidades')->insert(['id' => 2609402, 'estado_id' => 26, 'nome' => 'Moreno']);
	DB::table('cidades')->insert(['id' => 2609501, 'estado_id' => 26, 'nome' => 'Nazaré da Mata']);
	DB::table('cidades')->insert(['id' => 2609600, 'estado_id' => 26, 'nome' => 'Olinda']);
	DB::table('cidades')->insert(['id' => 2609709, 'estado_id' => 26, 'nome' => 'Orobó']);
	DB::table('cidades')->insert(['id' => 2609808, 'estado_id' => 26, 'nome' => 'Orocó']);
	DB::table('cidades')->insert(['id' => 2609907, 'estado_id' => 26, 'nome' => 'Ouricuri']);
	DB::table('cidades')->insert(['id' => 2610004, 'estado_id' => 26, 'nome' => 'Palmares']);
	DB::table('cidades')->insert(['id' => 2610103, 'estado_id' => 26, 'nome' => 'Palmeirina']);
	DB::table('cidades')->insert(['id' => 2610202, 'estado_id' => 26, 'nome' => 'Panelas']);
	DB::table('cidades')->insert(['id' => 2610301, 'estado_id' => 26, 'nome' => 'Paranatama']);
	DB::table('cidades')->insert(['id' => 2610400, 'estado_id' => 26, 'nome' => 'Parnamirim']);
	DB::table('cidades')->insert(['id' => 2610509, 'estado_id' => 26, 'nome' => 'Passira']);
	DB::table('cidades')->insert(['id' => 2610608, 'estado_id' => 26, 'nome' => 'Paudalho']);
	DB::table('cidades')->insert(['id' => 2610707, 'estado_id' => 26, 'nome' => 'Paulista']);
	DB::table('cidades')->insert(['id' => 2610806, 'estado_id' => 26, 'nome' => 'Pedra']);
	DB::table('cidades')->insert(['id' => 2610905, 'estado_id' => 26, 'nome' => 'Pesqueira']);
	DB::table('cidades')->insert(['id' => 2611002, 'estado_id' => 26, 'nome' => 'Petrolândia']);
	DB::table('cidades')->insert(['id' => 2611101, 'estado_id' => 26, 'nome' => 'Petrolina']);
	DB::table('cidades')->insert(['id' => 2611200, 'estado_id' => 26, 'nome' => 'Poção']);
	DB::table('cidades')->insert(['id' => 2611309, 'estado_id' => 26, 'nome' => 'Pombos']);
	DB::table('cidades')->insert(['id' => 2611408, 'estado_id' => 26, 'nome' => 'Primavera']);
	DB::table('cidades')->insert(['id' => 2611507, 'estado_id' => 26, 'nome' => 'Quipapá']);
	DB::table('cidades')->insert(['id' => 2611533, 'estado_id' => 26, 'nome' => 'Quixaba']);
	DB::table('cidades')->insert(['id' => 2611606, 'estado_id' => 26, 'nome' => 'Recife']);
	DB::table('cidades')->insert(['id' => 2611705, 'estado_id' => 26, 'nome' => 'Riacho das Almas']);
	DB::table('cidades')->insert(['id' => 2611804, 'estado_id' => 26, 'nome' => 'Ribeirão']);
	DB::table('cidades')->insert(['id' => 2611903, 'estado_id' => 26, 'nome' => 'Rio Formoso']);
	DB::table('cidades')->insert(['id' => 2612000, 'estado_id' => 26, 'nome' => 'Sairé']);
	DB::table('cidades')->insert(['id' => 2612109, 'estado_id' => 26, 'nome' => 'Salgadinho']);
	DB::table('cidades')->insert(['id' => 2612208, 'estado_id' => 26, 'nome' => 'Salgueiro']);
	DB::table('cidades')->insert(['id' => 2612307, 'estado_id' => 26, 'nome' => 'Saloá']);
	DB::table('cidades')->insert(['id' => 2612406, 'estado_id' => 26, 'nome' => 'Sanharó']);
	DB::table('cidades')->insert(['id' => 2612455, 'estado_id' => 26, 'nome' => 'Santa Cruz']);
	DB::table('cidades')->insert(['id' => 2612471, 'estado_id' => 26, 'nome' => 'Santa Cruz da Baixa Verde']);
	DB::table('cidades')->insert(['id' => 2612505, 'estado_id' => 26, 'nome' => 'Santa Cruz do Capibaribe']);
	DB::table('cidades')->insert(['id' => 2612554, 'estado_id' => 26, 'nome' => 'Santa Filomena']);
	DB::table('cidades')->insert(['id' => 2612604, 'estado_id' => 26, 'nome' => 'Santa Maria da Boa Vista']);
	DB::table('cidades')->insert(['id' => 2612703, 'estado_id' => 26, 'nome' => 'Santa Maria do Cambucá']);
	DB::table('cidades')->insert(['id' => 2612802, 'estado_id' => 26, 'nome' => 'Santa Terezinha']);
	DB::table('cidades')->insert(['id' => 2612901, 'estado_id' => 26, 'nome' => 'São Benedito do Sul']);
	DB::table('cidades')->insert(['id' => 2613008, 'estado_id' => 26, 'nome' => 'São Bento do Una']);
	DB::table('cidades')->insert(['id' => 2613107, 'estado_id' => 26, 'nome' => 'São Caitano']);
	DB::table('cidades')->insert(['id' => 2613206, 'estado_id' => 26, 'nome' => 'São João']);
	DB::table('cidades')->insert(['id' => 2613305, 'estado_id' => 26, 'nome' => 'São Joaquim do Monte']);
	DB::table('cidades')->insert(['id' => 2613404, 'estado_id' => 26, 'nome' => 'São José da Coroa Grande']);
	DB::table('cidades')->insert(['id' => 2613503, 'estado_id' => 26, 'nome' => 'São José do Belmonte']);
	DB::table('cidades')->insert(['id' => 2613602, 'estado_id' => 26, 'nome' => 'São José do Egito']);
	DB::table('cidades')->insert(['id' => 2613701, 'estado_id' => 26, 'nome' => 'São Lourenço da Mata']);
	DB::table('cidades')->insert(['id' => 2613800, 'estado_id' => 26, 'nome' => 'São Vicente Ferrer']);
	DB::table('cidades')->insert(['id' => 2613909, 'estado_id' => 26, 'nome' => 'Serra Talhada']);
	DB::table('cidades')->insert(['id' => 2614006, 'estado_id' => 26, 'nome' => 'Serrita']);
	DB::table('cidades')->insert(['id' => 2614105, 'estado_id' => 26, 'nome' => 'Sertânia']);
	DB::table('cidades')->insert(['id' => 2614204, 'estado_id' => 26, 'nome' => 'Sirinhaém']);
	DB::table('cidades')->insert(['id' => 2614303, 'estado_id' => 26, 'nome' => 'Moreilândia']);
	DB::table('cidades')->insert(['id' => 2614402, 'estado_id' => 26, 'nome' => 'Solidão']);
	DB::table('cidades')->insert(['id' => 2614501, 'estado_id' => 26, 'nome' => 'Surubim']);
	DB::table('cidades')->insert(['id' => 2614600, 'estado_id' => 26, 'nome' => 'Tabira']);
	DB::table('cidades')->insert(['id' => 2614709, 'estado_id' => 26, 'nome' => 'Tacaimbó']);
	DB::table('cidades')->insert(['id' => 2614808, 'estado_id' => 26, 'nome' => 'Tacaratu']);
	DB::table('cidades')->insert(['id' => 2614857, 'estado_id' => 26, 'nome' => 'Tamandaré']);
	DB::table('cidades')->insert(['id' => 2615003, 'estado_id' => 26, 'nome' => 'Taquaritinga do Norte']);
	DB::table('cidades')->insert(['id' => 2615102, 'estado_id' => 26, 'nome' => 'Terezinha']);
	DB::table('cidades')->insert(['id' => 2615201, 'estado_id' => 26, 'nome' => 'Terra Nova']);
	DB::table('cidades')->insert(['id' => 2615300, 'estado_id' => 26, 'nome' => 'Timbaúba']);
	DB::table('cidades')->insert(['id' => 2615409, 'estado_id' => 26, 'nome' => 'Toritama']);
	DB::table('cidades')->insert(['id' => 2615508, 'estado_id' => 26, 'nome' => 'Tracunhaém']);
	DB::table('cidades')->insert(['id' => 2615607, 'estado_id' => 26, 'nome' => 'Trindade']);
	DB::table('cidades')->insert(['id' => 2615706, 'estado_id' => 26, 'nome' => 'Triunfo']);
	DB::table('cidades')->insert(['id' => 2615805, 'estado_id' => 26, 'nome' => 'Tupanatinga']);
	DB::table('cidades')->insert(['id' => 2615904, 'estado_id' => 26, 'nome' => 'Tuparetama']);
	DB::table('cidades')->insert(['id' => 2616001, 'estado_id' => 26, 'nome' => 'Venturosa']);
	DB::table('cidades')->insert(['id' => 2616100, 'estado_id' => 26, 'nome' => 'Verdejante']);
	DB::table('cidades')->insert(['id' => 2616183, 'estado_id' => 26, 'nome' => 'Vertente do Lério']);
	DB::table('cidades')->insert(['id' => 2616209, 'estado_id' => 26, 'nome' => 'Vertentes']);
	DB::table('cidades')->insert(['id' => 2616308, 'estado_id' => 26, 'nome' => 'Vicência']);
	DB::table('cidades')->insert(['id' => 2616407, 'estado_id' => 26, 'nome' => 'Vitória de Santo Antão']);
	DB::table('cidades')->insert(['id' => 2616506, 'estado_id' => 26, 'nome' => 'Xexéu']);
    }
}
