<?php

use Illuminate\Database\Seeder;

class CidadesTableGOSeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades de Goiás
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 5200050, 'estado_id' => 52, 'nome' => 'Abadia de Goiás']);
		DB::table('cidades')->insert(['id' => 5200100, 'estado_id' => 52, 'nome' => 'Abadiânia']);
		DB::table('cidades')->insert(['id' => 5200134, 'estado_id' => 52, 'nome' => 'Acreúna']);
		DB::table('cidades')->insert(['id' => 5200159, 'estado_id' => 52, 'nome' => 'Adelândia']);
		DB::table('cidades')->insert(['id' => 5200175, 'estado_id' => 52, 'nome' => 'Água Fria de Goiás']);
		DB::table('cidades')->insert(['id' => 5200209, 'estado_id' => 52, 'nome' => 'Água Limpa']);
		DB::table('cidades')->insert(['id' => 5200258, 'estado_id' => 52, 'nome' => 'Águas Lindas de Goiás']);
		DB::table('cidades')->insert(['id' => 5200308, 'estado_id' => 52, 'nome' => 'Alexânia']);
		DB::table('cidades')->insert(['id' => 5200506, 'estado_id' => 52, 'nome' => 'Aloândia']);
		DB::table('cidades')->insert(['id' => 5200555, 'estado_id' => 52, 'nome' => 'Alto Horizonte']);
		DB::table('cidades')->insert(['id' => 5200605, 'estado_id' => 52, 'nome' => 'Alto Paraíso de Goiás']);
		DB::table('cidades')->insert(['id' => 5200803, 'estado_id' => 52, 'nome' => 'Alvorada do Norte']);
		DB::table('cidades')->insert(['id' => 5200829, 'estado_id' => 52, 'nome' => 'Amaralina']);
		DB::table('cidades')->insert(['id' => 5200852, 'estado_id' => 52, 'nome' => 'Americano do Brasil']);
		DB::table('cidades')->insert(['id' => 5200902, 'estado_id' => 52, 'nome' => 'Amorinópolis']);
		DB::table('cidades')->insert(['id' => 5201108, 'estado_id' => 52, 'nome' => 'Anápolis']);
		DB::table('cidades')->insert(['id' => 5201207, 'estado_id' => 52, 'nome' => 'Anhanguera']);
		DB::table('cidades')->insert(['id' => 5201306, 'estado_id' => 52, 'nome' => 'Anicuns']);
		DB::table('cidades')->insert(['id' => 5201405, 'estado_id' => 52, 'nome' => 'Aparecida de Goiânia']);
		DB::table('cidades')->insert(['id' => 5201454, 'estado_id' => 52, 'nome' => 'Aparecida do Rio Doce']);
		DB::table('cidades')->insert(['id' => 5201504, 'estado_id' => 52, 'nome' => 'Aporé']);
		DB::table('cidades')->insert(['id' => 5201603, 'estado_id' => 52, 'nome' => 'Araçu']);
		DB::table('cidades')->insert(['id' => 5201702, 'estado_id' => 52, 'nome' => 'Aragarças']);
		DB::table('cidades')->insert(['id' => 5201801, 'estado_id' => 52, 'nome' => 'Aragoiânia']);
		DB::table('cidades')->insert(['id' => 5202155, 'estado_id' => 52, 'nome' => 'Araguapaz']);
		DB::table('cidades')->insert(['id' => 5202353, 'estado_id' => 52, 'nome' => 'Arenópolis']);
		DB::table('cidades')->insert(['id' => 5202502, 'estado_id' => 52, 'nome' => 'Aruanã']);
		DB::table('cidades')->insert(['id' => 5202601, 'estado_id' => 52, 'nome' => 'Aurilândia']);
		DB::table('cidades')->insert(['id' => 5202809, 'estado_id' => 52, 'nome' => 'Avelinópolis']);
		DB::table('cidades')->insert(['id' => 5203104, 'estado_id' => 52, 'nome' => 'Baliza']);
		DB::table('cidades')->insert(['id' => 5203203, 'estado_id' => 52, 'nome' => 'Barro Alto']);
		DB::table('cidades')->insert(['id' => 5203302, 'estado_id' => 52, 'nome' => 'Bela Vista de Goiás']);
		DB::table('cidades')->insert(['id' => 5203401, 'estado_id' => 52, 'nome' => 'Bom Jardim de Goiás']);
		DB::table('cidades')->insert(['id' => 5203500, 'estado_id' => 52, 'nome' => 'Bom Jesus de Goiás']);
		DB::table('cidades')->insert(['id' => 5203559, 'estado_id' => 52, 'nome' => 'Bonfinópolis']);
		DB::table('cidades')->insert(['id' => 5203575, 'estado_id' => 52, 'nome' => 'Bonópolis']);
		DB::table('cidades')->insert(['id' => 5203609, 'estado_id' => 52, 'nome' => 'Brazabrantes']);
		DB::table('cidades')->insert(['id' => 5203807, 'estado_id' => 52, 'nome' => 'Britânia']);
		DB::table('cidades')->insert(['id' => 5203906, 'estado_id' => 52, 'nome' => 'Buriti Alegre']);
		DB::table('cidades')->insert(['id' => 5203939, 'estado_id' => 52, 'nome' => 'Buriti de Goiás']);
		DB::table('cidades')->insert(['id' => 5203962, 'estado_id' => 52, 'nome' => 'Buritinópolis']);
		DB::table('cidades')->insert(['id' => 5204003, 'estado_id' => 52, 'nome' => 'Cabeceiras']);
		DB::table('cidades')->insert(['id' => 5204102, 'estado_id' => 52, 'nome' => 'Cachoeira Alta']);
		DB::table('cidades')->insert(['id' => 5204201, 'estado_id' => 52, 'nome' => 'Cachoeira de Goiás']);
		DB::table('cidades')->insert(['id' => 5204250, 'estado_id' => 52, 'nome' => 'Cachoeira Dourada']);
		DB::table('cidades')->insert(['id' => 5204300, 'estado_id' => 52, 'nome' => 'Caçu']);
		DB::table('cidades')->insert(['id' => 5204409, 'estado_id' => 52, 'nome' => 'Caiapônia']);
		DB::table('cidades')->insert(['id' => 5204508, 'estado_id' => 52, 'nome' => 'Caldas Novas']);
		DB::table('cidades')->insert(['id' => 5204557, 'estado_id' => 52, 'nome' => 'Caldazinha']);
		DB::table('cidades')->insert(['id' => 5204607, 'estado_id' => 52, 'nome' => 'Campestre de Goiás']);
		DB::table('cidades')->insert(['id' => 5204656, 'estado_id' => 52, 'nome' => 'Campinaçu']);
		DB::table('cidades')->insert(['id' => 5204706, 'estado_id' => 52, 'nome' => 'Campinorte']);
		DB::table('cidades')->insert(['id' => 5204805, 'estado_id' => 52, 'nome' => 'Campo Alegre de Goiás']);
		DB::table('cidades')->insert(['id' => 5204854, 'estado_id' => 52, 'nome' => 'Campo Limpo de Goiás']);
		DB::table('cidades')->insert(['id' => 5204904, 'estado_id' => 52, 'nome' => 'Campos Belos']);
		DB::table('cidades')->insert(['id' => 5204953, 'estado_id' => 52, 'nome' => 'Campos Verdes']);
		DB::table('cidades')->insert(['id' => 5205000, 'estado_id' => 52, 'nome' => 'Carmo do Rio Verde']);
		DB::table('cidades')->insert(['id' => 5205059, 'estado_id' => 52, 'nome' => 'Castelândia']);
		DB::table('cidades')->insert(['id' => 5205109, 'estado_id' => 52, 'nome' => 'Catalão']);
		DB::table('cidades')->insert(['id' => 5205208, 'estado_id' => 52, 'nome' => 'Caturaí']);
		DB::table('cidades')->insert(['id' => 5205307, 'estado_id' => 52, 'nome' => 'Cavalcante']);
		DB::table('cidades')->insert(['id' => 5205406, 'estado_id' => 52, 'nome' => 'Ceres']);
		DB::table('cidades')->insert(['id' => 5205455, 'estado_id' => 52, 'nome' => 'Cezarina']);
		DB::table('cidades')->insert(['id' => 5205471, 'estado_id' => 52, 'nome' => 'Chapadão do Céu']);
		DB::table('cidades')->insert(['id' => 5205497, 'estado_id' => 52, 'nome' => 'Cidade Ocidental']);
		DB::table('cidades')->insert(['id' => 5205513, 'estado_id' => 52, 'nome' => 'Cocalzinho de Goiás']);
		DB::table('cidades')->insert(['id' => 5205521, 'estado_id' => 52, 'nome' => 'Colinas do Sul']);
		DB::table('cidades')->insert(['id' => 5205703, 'estado_id' => 52, 'nome' => 'Córrego do Ouro']);
		DB::table('cidades')->insert(['id' => 5205802, 'estado_id' => 52, 'nome' => 'Corumbá de Goiás']);
		DB::table('cidades')->insert(['id' => 5205901, 'estado_id' => 52, 'nome' => 'Corumbaíba']);
		DB::table('cidades')->insert(['id' => 5206206, 'estado_id' => 52, 'nome' => 'Cristalina']);
		DB::table('cidades')->insert(['id' => 5206305, 'estado_id' => 52, 'nome' => 'Cristianópolis']);
		DB::table('cidades')->insert(['id' => 5206404, 'estado_id' => 52, 'nome' => 'Crixás']);
		DB::table('cidades')->insert(['id' => 5206503, 'estado_id' => 52, 'nome' => 'Cromínia']);
		DB::table('cidades')->insert(['id' => 5206602, 'estado_id' => 52, 'nome' => 'Cumari']);
		DB::table('cidades')->insert(['id' => 5206701, 'estado_id' => 52, 'nome' => 'Damianópolis']);
		DB::table('cidades')->insert(['id' => 5206800, 'estado_id' => 52, 'nome' => 'Damolândia']);
		DB::table('cidades')->insert(['id' => 5206909, 'estado_id' => 52, 'nome' => 'Davinópolis']);
		DB::table('cidades')->insert(['id' => 5207105, 'estado_id' => 52, 'nome' => 'Diorama']);
		DB::table('cidades')->insert(['id' => 5207253, 'estado_id' => 52, 'nome' => 'Doverlândia']);
		DB::table('cidades')->insert(['id' => 5207352, 'estado_id' => 52, 'nome' => 'Edealina']);
		DB::table('cidades')->insert(['id' => 5207402, 'estado_id' => 52, 'nome' => 'Edéia']);
		DB::table('cidades')->insert(['id' => 5207501, 'estado_id' => 52, 'nome' => 'Estrela do Norte']);
		DB::table('cidades')->insert(['id' => 5207535, 'estado_id' => 52, 'nome' => 'Faina']);
		DB::table('cidades')->insert(['id' => 5207600, 'estado_id' => 52, 'nome' => 'Fazenda Nova']);
		DB::table('cidades')->insert(['id' => 5207808, 'estado_id' => 52, 'nome' => 'Firminópolis']);
		DB::table('cidades')->insert(['id' => 5207907, 'estado_id' => 52, 'nome' => 'Flores de Goiás']);
		DB::table('cidades')->insert(['id' => 5208004, 'estado_id' => 52, 'nome' => 'Formosa']);
		DB::table('cidades')->insert(['id' => 5208103, 'estado_id' => 52, 'nome' => 'Formoso']);
		DB::table('cidades')->insert(['id' => 5208152, 'estado_id' => 52, 'nome' => 'Gameleira de Goiás']);
		DB::table('cidades')->insert(['id' => 5208301, 'estado_id' => 52, 'nome' => 'Divinópolis de Goiás']);
		DB::table('cidades')->insert(['id' => 5208400, 'estado_id' => 52, 'nome' => 'Goianápolis']);
		DB::table('cidades')->insert(['id' => 5208509, 'estado_id' => 52, 'nome' => 'Goiandira']);
		DB::table('cidades')->insert(['id' => 5208608, 'estado_id' => 52, 'nome' => 'Goianésia']);
		DB::table('cidades')->insert(['id' => 5208707, 'estado_id' => 52, 'nome' => 'Goiânia']);
		DB::table('cidades')->insert(['id' => 5208806, 'estado_id' => 52, 'nome' => 'Goianira']);
		DB::table('cidades')->insert(['id' => 5208905, 'estado_id' => 52, 'nome' => 'Goiás']);
		DB::table('cidades')->insert(['id' => 5209101, 'estado_id' => 52, 'nome' => 'Goiatuba']);
		DB::table('cidades')->insert(['id' => 5209150, 'estado_id' => 52, 'nome' => 'Gouvelândia']);
		DB::table('cidades')->insert(['id' => 5209200, 'estado_id' => 52, 'nome' => 'Guapó']);
		DB::table('cidades')->insert(['id' => 5209291, 'estado_id' => 52, 'nome' => 'Guaraíta']);
		DB::table('cidades')->insert(['id' => 5209408, 'estado_id' => 52, 'nome' => 'Guarani de Goiás']);
		DB::table('cidades')->insert(['id' => 5209457, 'estado_id' => 52, 'nome' => 'Guarinos']);
		DB::table('cidades')->insert(['id' => 5209606, 'estado_id' => 52, 'nome' => 'Heitoraí']);
		DB::table('cidades')->insert(['id' => 5209705, 'estado_id' => 52, 'nome' => 'Hidrolândia']);
		DB::table('cidades')->insert(['id' => 5209804, 'estado_id' => 52, 'nome' => 'Hidrolina']);
		DB::table('cidades')->insert(['id' => 5209903, 'estado_id' => 52, 'nome' => 'Iaciara']);
		DB::table('cidades')->insert(['id' => 5209937, 'estado_id' => 52, 'nome' => 'Inaciolândia']);
		DB::table('cidades')->insert(['id' => 5209952, 'estado_id' => 52, 'nome' => 'Indiara']);
		DB::table('cidades')->insert(['id' => 5210000, 'estado_id' => 52, 'nome' => 'Inhumas']);
		DB::table('cidades')->insert(['id' => 5210109, 'estado_id' => 52, 'nome' => 'Ipameri']);
		DB::table('cidades')->insert(['id' => 5210158, 'estado_id' => 52, 'nome' => 'Ipiranga de Goiás']);
		DB::table('cidades')->insert(['id' => 5210208, 'estado_id' => 52, 'nome' => 'Iporá']);
		DB::table('cidades')->insert(['id' => 5210307, 'estado_id' => 52, 'nome' => 'Israelândia']);
		DB::table('cidades')->insert(['id' => 5210406, 'estado_id' => 52, 'nome' => 'Itaberaí']);
		DB::table('cidades')->insert(['id' => 5210562, 'estado_id' => 52, 'nome' => 'Itaguari']);
		DB::table('cidades')->insert(['id' => 5210604, 'estado_id' => 52, 'nome' => 'Itaguaru']);
		DB::table('cidades')->insert(['id' => 5210802, 'estado_id' => 52, 'nome' => 'Itajá']);
		DB::table('cidades')->insert(['id' => 5210901, 'estado_id' => 52, 'nome' => 'Itapaci']);
		DB::table('cidades')->insert(['id' => 5211008, 'estado_id' => 52, 'nome' => 'Itapirapuã']);
		DB::table('cidades')->insert(['id' => 5211206, 'estado_id' => 52, 'nome' => 'Itapuranga']);
		DB::table('cidades')->insert(['id' => 5211305, 'estado_id' => 52, 'nome' => 'Itarumã']);
		DB::table('cidades')->insert(['id' => 5211404, 'estado_id' => 52, 'nome' => 'Itauçu']);
		DB::table('cidades')->insert(['id' => 5211503, 'estado_id' => 52, 'nome' => 'Itumbiara']);
		DB::table('cidades')->insert(['id' => 5211602, 'estado_id' => 52, 'nome' => 'Ivolândia']);
		DB::table('cidades')->insert(['id' => 5211701, 'estado_id' => 52, 'nome' => 'Jandaia']);
		DB::table('cidades')->insert(['id' => 5211800, 'estado_id' => 52, 'nome' => 'Jaraguá']);
		DB::table('cidades')->insert(['id' => 5211909, 'estado_id' => 52, 'nome' => 'Jataí']);
		DB::table('cidades')->insert(['id' => 5212006, 'estado_id' => 52, 'nome' => 'Jaupaci']);
		DB::table('cidades')->insert(['id' => 5212055, 'estado_id' => 52, 'nome' => 'Jesúpolis']);
		DB::table('cidades')->insert(['id' => 5212105, 'estado_id' => 52, 'nome' => 'Joviânia']);
		DB::table('cidades')->insert(['id' => 5212204, 'estado_id' => 52, 'nome' => 'Jussara']);
		DB::table('cidades')->insert(['id' => 5212253, 'estado_id' => 52, 'nome' => 'Lagoa Santa']);
		DB::table('cidades')->insert(['id' => 5212303, 'estado_id' => 52, 'nome' => 'Leopoldo de Bulhões']);
		DB::table('cidades')->insert(['id' => 5212501, 'estado_id' => 52, 'nome' => 'Luziânia']);
		DB::table('cidades')->insert(['id' => 5212600, 'estado_id' => 52, 'nome' => 'Mairipotaba']);
		DB::table('cidades')->insert(['id' => 5212709, 'estado_id' => 52, 'nome' => 'Mambaí']);
		DB::table('cidades')->insert(['id' => 5212808, 'estado_id' => 52, 'nome' => 'Mara Rosa']);
		DB::table('cidades')->insert(['id' => 5212907, 'estado_id' => 52, 'nome' => 'Marzagão']);
		DB::table('cidades')->insert(['id' => 5212956, 'estado_id' => 52, 'nome' => 'Matrinchã']);
		DB::table('cidades')->insert(['id' => 5213004, 'estado_id' => 52, 'nome' => 'Maurilândia']);
		DB::table('cidades')->insert(['id' => 5213053, 'estado_id' => 52, 'nome' => 'Mimoso de Goiás']);
		DB::table('cidades')->insert(['id' => 5213087, 'estado_id' => 52, 'nome' => 'Minaçu']);
		DB::table('cidades')->insert(['id' => 5213103, 'estado_id' => 52, 'nome' => 'Mineiros']);
		DB::table('cidades')->insert(['id' => 5213400, 'estado_id' => 52, 'nome' => 'Moiporá']);
		DB::table('cidades')->insert(['id' => 5213509, 'estado_id' => 52, 'nome' => 'Monte Alegre de Goiás']);
		DB::table('cidades')->insert(['id' => 5213707, 'estado_id' => 52, 'nome' => 'Montes Claros de Goiás']);
		DB::table('cidades')->insert(['id' => 5213756, 'estado_id' => 52, 'nome' => 'Montividiu']);
		DB::table('cidades')->insert(['id' => 5213772, 'estado_id' => 52, 'nome' => 'Montividiu do Norte']);
		DB::table('cidades')->insert(['id' => 5213806, 'estado_id' => 52, 'nome' => 'Morrinhos']);
		DB::table('cidades')->insert(['id' => 5213855, 'estado_id' => 52, 'nome' => 'Morro Agudo de Goiás']);
		DB::table('cidades')->insert(['id' => 5213905, 'estado_id' => 52, 'nome' => 'Mossâmedes']);
		DB::table('cidades')->insert(['id' => 5214002, 'estado_id' => 52, 'nome' => 'Mozarlândia']);
		DB::table('cidades')->insert(['id' => 5214051, 'estado_id' => 52, 'nome' => 'Mundo Novo']);
		DB::table('cidades')->insert(['id' => 5214101, 'estado_id' => 52, 'nome' => 'Mutunópolis']);
		DB::table('cidades')->insert(['id' => 5214408, 'estado_id' => 52, 'nome' => 'Nazário']);
		DB::table('cidades')->insert(['id' => 5214507, 'estado_id' => 52, 'nome' => 'Nerópolis']);
		DB::table('cidades')->insert(['id' => 5214606, 'estado_id' => 52, 'nome' => 'Niquelândia']);
		DB::table('cidades')->insert(['id' => 5214705, 'estado_id' => 52, 'nome' => 'Nova América']);
		DB::table('cidades')->insert(['id' => 5214804, 'estado_id' => 52, 'nome' => 'Nova Aurora']);
		DB::table('cidades')->insert(['id' => 5214838, 'estado_id' => 52, 'nome' => 'Nova Crixás']);
		DB::table('cidades')->insert(['id' => 5214861, 'estado_id' => 52, 'nome' => 'Nova Glória']);
		DB::table('cidades')->insert(['id' => 5214879, 'estado_id' => 52, 'nome' => 'Nova Iguaçu de Goiás']);
		DB::table('cidades')->insert(['id' => 5214903, 'estado_id' => 52, 'nome' => 'Nova Roma']);
		DB::table('cidades')->insert(['id' => 5215009, 'estado_id' => 52, 'nome' => 'Nova Veneza']);
		DB::table('cidades')->insert(['id' => 5215207, 'estado_id' => 52, 'nome' => 'Novo Brasil']);
		DB::table('cidades')->insert(['id' => 5215231, 'estado_id' => 52, 'nome' => 'Novo Gama']);
		DB::table('cidades')->insert(['id' => 5215256, 'estado_id' => 52, 'nome' => 'Novo Planalto']);
		DB::table('cidades')->insert(['id' => 5215306, 'estado_id' => 52, 'nome' => 'Orizona']);
		DB::table('cidades')->insert(['id' => 5215405, 'estado_id' => 52, 'nome' => 'Ouro Verde de Goiás']);
		DB::table('cidades')->insert(['id' => 5215504, 'estado_id' => 52, 'nome' => 'Ouvidor']);
		DB::table('cidades')->insert(['id' => 5215603, 'estado_id' => 52, 'nome' => 'Padre Bernardo']);
		DB::table('cidades')->insert(['id' => 5215652, 'estado_id' => 52, 'nome' => 'Palestina de Goiás']);
		DB::table('cidades')->insert(['id' => 5215702, 'estado_id' => 52, 'nome' => 'Palmeiras de Goiás']);
		DB::table('cidades')->insert(['id' => 5215801, 'estado_id' => 52, 'nome' => 'Palmelo']);
		DB::table('cidades')->insert(['id' => 5215900, 'estado_id' => 52, 'nome' => 'Palminópolis']);
		DB::table('cidades')->insert(['id' => 5216007, 'estado_id' => 52, 'nome' => 'Panamá']);
		DB::table('cidades')->insert(['id' => 5216304, 'estado_id' => 52, 'nome' => 'Paranaiguara']);
		DB::table('cidades')->insert(['id' => 5216403, 'estado_id' => 52, 'nome' => 'Paraúna']);
		DB::table('cidades')->insert(['id' => 5216452, 'estado_id' => 52, 'nome' => 'Perolândia']);
		DB::table('cidades')->insert(['id' => 5216809, 'estado_id' => 52, 'nome' => 'Petrolina de Goiás']);
		DB::table('cidades')->insert(['id' => 5216908, 'estado_id' => 52, 'nome' => 'Pilar de Goiás']);
		DB::table('cidades')->insert(['id' => 5217104, 'estado_id' => 52, 'nome' => 'Piracanjuba']);
		DB::table('cidades')->insert(['id' => 5217203, 'estado_id' => 52, 'nome' => 'Piranhas']);
		DB::table('cidades')->insert(['id' => 5217302, 'estado_id' => 52, 'nome' => 'Pirenópolis']);
		DB::table('cidades')->insert(['id' => 5217401, 'estado_id' => 52, 'nome' => 'Pires do Rio']);
		DB::table('cidades')->insert(['id' => 5217609, 'estado_id' => 52, 'nome' => 'Planaltina']);
		DB::table('cidades')->insert(['id' => 5217708, 'estado_id' => 52, 'nome' => 'Pontalina']);
		DB::table('cidades')->insert(['id' => 5218003, 'estado_id' => 52, 'nome' => 'Porangatu']);
		DB::table('cidades')->insert(['id' => 5218052, 'estado_id' => 52, 'nome' => 'Porteirão']);
		DB::table('cidades')->insert(['id' => 5218102, 'estado_id' => 52, 'nome' => 'Portelândia']);
		DB::table('cidades')->insert(['id' => 5218300, 'estado_id' => 52, 'nome' => 'Posse']);
		DB::table('cidades')->insert(['id' => 5218391, 'estado_id' => 52, 'nome' => 'Professor Jamil']);
		DB::table('cidades')->insert(['id' => 5218508, 'estado_id' => 52, 'nome' => 'Quirinópolis']);
		DB::table('cidades')->insert(['id' => 5218607, 'estado_id' => 52, 'nome' => 'Rialma']);
		DB::table('cidades')->insert(['id' => 5218706, 'estado_id' => 52, 'nome' => 'Rianápolis']);
		DB::table('cidades')->insert(['id' => 5218789, 'estado_id' => 52, 'nome' => 'Rio Quente']);
		DB::table('cidades')->insert(['id' => 5218805, 'estado_id' => 52, 'nome' => 'Rio Verde']);
		DB::table('cidades')->insert(['id' => 5218904, 'estado_id' => 52, 'nome' => 'Rubiataba']);
		DB::table('cidades')->insert(['id' => 5219001, 'estado_id' => 52, 'nome' => 'Sanclerlândia']);
		DB::table('cidades')->insert(['id' => 5219100, 'estado_id' => 52, 'nome' => 'Santa Bárbara de Goiás']);
		DB::table('cidades')->insert(['id' => 5219209, 'estado_id' => 52, 'nome' => 'Santa Cruz de Goiás']);
		DB::table('cidades')->insert(['id' => 5219258, 'estado_id' => 52, 'nome' => 'Santa Fé de Goiás']);
		DB::table('cidades')->insert(['id' => 5219308, 'estado_id' => 52, 'nome' => 'Santa Helena de Goiás']);
		DB::table('cidades')->insert(['id' => 5219357, 'estado_id' => 52, 'nome' => 'Santa Isabel']);
		DB::table('cidades')->insert(['id' => 5219407, 'estado_id' => 52, 'nome' => 'Santa Rita do Araguaia']);
		DB::table('cidades')->insert(['id' => 5219456, 'estado_id' => 52, 'nome' => 'Santa Rita do Novo Destino']);
		DB::table('cidades')->insert(['id' => 5219506, 'estado_id' => 52, 'nome' => 'Santa Rosa de Goiás']);
		DB::table('cidades')->insert(['id' => 5219605, 'estado_id' => 52, 'nome' => 'Santa Tereza de Goiás']);
		DB::table('cidades')->insert(['id' => 5219704, 'estado_id' => 52, 'nome' => 'Santa Terezinha de Goiás']);
		DB::table('cidades')->insert(['id' => 5219712, 'estado_id' => 52, 'nome' => 'Santo Antônio da Barra']);
		DB::table('cidades')->insert(['id' => 5219738, 'estado_id' => 52, 'nome' => 'Santo Antônio de Goiás']);
		DB::table('cidades')->insert(['id' => 5219753, 'estado_id' => 52, 'nome' => 'Santo Antônio do Descoberto']);
		DB::table('cidades')->insert(['id' => 5219803, 'estado_id' => 52, 'nome' => 'São Domingos']);
		DB::table('cidades')->insert(['id' => 5219902, 'estado_id' => 52, 'nome' => 'São Francisco de Goiás']);
		DB::table('cidades')->insert(['id' => 5220009, 'estado_id' => 52, 'nome' => 'São João d\'Aliança']);
		DB::table('cidades')->insert(['id' => 5220058, 'estado_id' => 52, 'nome' => 'São João da Paraúna']);
		DB::table('cidades')->insert(['id' => 5220108, 'estado_id' => 52, 'nome' => 'São Luís de Montes Belos']);
		DB::table('cidades')->insert(['id' => 5220157, 'estado_id' => 52, 'nome' => 'São Luíz do Norte']);
		DB::table('cidades')->insert(['id' => 5220207, 'estado_id' => 52, 'nome' => 'São Miguel do Araguaia']);
		DB::table('cidades')->insert(['id' => 5220264, 'estado_id' => 52, 'nome' => 'São Miguel do Passa Quatro']);
		DB::table('cidades')->insert(['id' => 5220280, 'estado_id' => 52, 'nome' => 'São Patrício']);
		DB::table('cidades')->insert(['id' => 5220405, 'estado_id' => 52, 'nome' => 'São Simão']);
		DB::table('cidades')->insert(['id' => 5220454, 'estado_id' => 52, 'nome' => 'Senador Canedo']);
		DB::table('cidades')->insert(['id' => 5220504, 'estado_id' => 52, 'nome' => 'Serranópolis']);
		DB::table('cidades')->insert(['id' => 5220603, 'estado_id' => 52, 'nome' => 'Silvânia']);
		DB::table('cidades')->insert(['id' => 5220686, 'estado_id' => 52, 'nome' => 'Simolândia']);
		DB::table('cidades')->insert(['id' => 5220702, 'estado_id' => 52, 'nome' => 'Sítio d\'Abadia']);
		DB::table('cidades')->insert(['id' => 5221007, 'estado_id' => 52, 'nome' => 'Taquaral de Goiás']);
		DB::table('cidades')->insert(['id' => 5221080, 'estado_id' => 52, 'nome' => 'Teresina de Goiás']);
		DB::table('cidades')->insert(['id' => 5221197, 'estado_id' => 52, 'nome' => 'Terezópolis de Goiás']);
		DB::table('cidades')->insert(['id' => 5221304, 'estado_id' => 52, 'nome' => 'Três Ranchos']);
		DB::table('cidades')->insert(['id' => 5221403, 'estado_id' => 52, 'nome' => 'Trindade']);
		DB::table('cidades')->insert(['id' => 5221452, 'estado_id' => 52, 'nome' => 'Trombas']);
		DB::table('cidades')->insert(['id' => 5221502, 'estado_id' => 52, 'nome' => 'Turvânia']);
		DB::table('cidades')->insert(['id' => 5221551, 'estado_id' => 52, 'nome' => 'Turvelândia']);
		DB::table('cidades')->insert(['id' => 5221577, 'estado_id' => 52, 'nome' => 'Uirapuru']);
		DB::table('cidades')->insert(['id' => 5221601, 'estado_id' => 52, 'nome' => 'Uruaçu']);
		DB::table('cidades')->insert(['id' => 5221700, 'estado_id' => 52, 'nome' => 'Uruana']);
		DB::table('cidades')->insert(['id' => 5221809, 'estado_id' => 52, 'nome' => 'Urutaí']);
		DB::table('cidades')->insert(['id' => 5221858, 'estado_id' => 52, 'nome' => 'Valparaíso de Goiás']);
		DB::table('cidades')->insert(['id' => 5221908, 'estado_id' => 52, 'nome' => 'Varjão']);
		DB::table('cidades')->insert(['id' => 5222005, 'estado_id' => 52, 'nome' => 'Vianópolis']);
		DB::table('cidades')->insert(['id' => 5222054, 'estado_id' => 52, 'nome' => 'Vicentinópolis']);
		DB::table('cidades')->insert(['id' => 5222203, 'estado_id' => 52, 'nome' => 'Vila Boa']);
		DB::table('cidades')->insert(['id' => 5222302, 'estado_id' => 52, 'nome' => 'Vila Propício']);
    }
}
