<?php

use Illuminate\Database\Seeder;

class CidadesTablePISeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades do Piauí
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 2200053, 'estado_id' => 22, 'nome' => 'Acauã']);
		DB::table('cidades')->insert(['id' => 2200103, 'estado_id' => 22, 'nome' => 'Agricolândia']);
		DB::table('cidades')->insert(['id' => 2200202, 'estado_id' => 22, 'nome' => 'Água Branca']);
		DB::table('cidades')->insert(['id' => 2200251, 'estado_id' => 22, 'nome' => 'Alagoinha do Piauí']);
		DB::table('cidades')->insert(['id' => 2200277, 'estado_id' => 22, 'nome' => 'Alegrete do Piauí']);
		DB::table('cidades')->insert(['id' => 2200301, 'estado_id' => 22, 'nome' => 'Alto Longá']);
		DB::table('cidades')->insert(['id' => 2200400, 'estado_id' => 22, 'nome' => 'Altos']);
		DB::table('cidades')->insert(['id' => 2200459, 'estado_id' => 22, 'nome' => 'Alvorada do Gurguéia']);
		DB::table('cidades')->insert(['id' => 2200509, 'estado_id' => 22, 'nome' => 'Amarante']);
		DB::table('cidades')->insert(['id' => 2200608, 'estado_id' => 22, 'nome' => 'Angical do Piauí']);
		DB::table('cidades')->insert(['id' => 2200707, 'estado_id' => 22, 'nome' => 'Anísio de Abreu']);
		DB::table('cidades')->insert(['id' => 2200806, 'estado_id' => 22, 'nome' => 'Antônio Almeida']);
		DB::table('cidades')->insert(['id' => 2200905, 'estado_id' => 22, 'nome' => 'Aroazes']);
		DB::table('cidades')->insert(['id' => 2200954, 'estado_id' => 22, 'nome' => 'Aroeiras do Itaim']);
		DB::table('cidades')->insert(['id' => 2201002, 'estado_id' => 22, 'nome' => 'Arraial']);
		DB::table('cidades')->insert(['id' => 2201051, 'estado_id' => 22, 'nome' => 'Assunção do Piauí']);
		DB::table('cidades')->insert(['id' => 2201101, 'estado_id' => 22, 'nome' => 'Avelino Lopes']);
		DB::table('cidades')->insert(['id' => 2201150, 'estado_id' => 22, 'nome' => 'Baixa Grande do Ribeiro']);
		DB::table('cidades')->insert(['id' => 2201176, 'estado_id' => 22, 'nome' => 'Barra D\'Alcântara']);
		DB::table('cidades')->insert(['id' => 2201200, 'estado_id' => 22, 'nome' => 'Barras']);
		DB::table('cidades')->insert(['id' => 2201309, 'estado_id' => 22, 'nome' => 'Barreiras do Piauí']);
		DB::table('cidades')->insert(['id' => 2201408, 'estado_id' => 22, 'nome' => 'Barro Duro']);
		DB::table('cidades')->insert(['id' => 2201507, 'estado_id' => 22, 'nome' => 'Batalha']);
		DB::table('cidades')->insert(['id' => 2201556, 'estado_id' => 22, 'nome' => 'Bela Vista do Piauí']);
		DB::table('cidades')->insert(['id' => 2201572, 'estado_id' => 22, 'nome' => 'Belém do Piauí']);
		DB::table('cidades')->insert(['id' => 2201606, 'estado_id' => 22, 'nome' => 'Beneditinos']);
		DB::table('cidades')->insert(['id' => 2201705, 'estado_id' => 22, 'nome' => 'Bertolínia']);
		DB::table('cidades')->insert(['id' => 2201739, 'estado_id' => 22, 'nome' => 'Betânia do Piauí']);
		DB::table('cidades')->insert(['id' => 2201770, 'estado_id' => 22, 'nome' => 'Boa Hora']);
		DB::table('cidades')->insert(['id' => 2201804, 'estado_id' => 22, 'nome' => 'Bocaina']);
		DB::table('cidades')->insert(['id' => 2201903, 'estado_id' => 22, 'nome' => 'Bom Jesus']);
		DB::table('cidades')->insert(['id' => 2201919, 'estado_id' => 22, 'nome' => 'Bom Princípio do Piauí']);
		DB::table('cidades')->insert(['id' => 2201929, 'estado_id' => 22, 'nome' => 'Bonfim do Piauí']);
		DB::table('cidades')->insert(['id' => 2201945, 'estado_id' => 22, 'nome' => 'Boqueirão do Piauí']);
		DB::table('cidades')->insert(['id' => 2201960, 'estado_id' => 22, 'nome' => 'Brasileira']);
		DB::table('cidades')->insert(['id' => 2201988, 'estado_id' => 22, 'nome' => 'Brejo do Piauí']);
		DB::table('cidades')->insert(['id' => 2202000, 'estado_id' => 22, 'nome' => 'Buriti dos Lopes']);
		DB::table('cidades')->insert(['id' => 2202026, 'estado_id' => 22, 'nome' => 'Buriti dos Montes']);
		DB::table('cidades')->insert(['id' => 2202059, 'estado_id' => 22, 'nome' => 'Cabeceiras do Piauí']);
		DB::table('cidades')->insert(['id' => 2202075, 'estado_id' => 22, 'nome' => 'Cajazeiras do Piauí']);
		DB::table('cidades')->insert(['id' => 2202083, 'estado_id' => 22, 'nome' => 'Cajueiro da Praia']);
		DB::table('cidades')->insert(['id' => 2202091, 'estado_id' => 22, 'nome' => 'Caldeirão Grande do Piauí']);
		DB::table('cidades')->insert(['id' => 2202109, 'estado_id' => 22, 'nome' => 'Campinas do Piauí']);
		DB::table('cidades')->insert(['id' => 2202117, 'estado_id' => 22, 'nome' => 'Campo Alegre do Fidalgo']);
		DB::table('cidades')->insert(['id' => 2202133, 'estado_id' => 22, 'nome' => 'Campo Grande do Piauí']);
		DB::table('cidades')->insert(['id' => 2202174, 'estado_id' => 22, 'nome' => 'Campo Largo do Piauí']);
		DB::table('cidades')->insert(['id' => 2202208, 'estado_id' => 22, 'nome' => 'Campo Maior']);
		DB::table('cidades')->insert(['id' => 2202251, 'estado_id' => 22, 'nome' => 'Canavieira']);
		DB::table('cidades')->insert(['id' => 2202307, 'estado_id' => 22, 'nome' => 'Canto do Buriti']);
		DB::table('cidades')->insert(['id' => 2202406, 'estado_id' => 22, 'nome' => 'Capitão de Campos']);
		DB::table('cidades')->insert(['id' => 2202455, 'estado_id' => 22, 'nome' => 'Capitão Gervásio Oliveira']);
		DB::table('cidades')->insert(['id' => 2202505, 'estado_id' => 22, 'nome' => 'Caracol']);
		DB::table('cidades')->insert(['id' => 2202539, 'estado_id' => 22, 'nome' => 'Caraúbas do Piauí']);
		DB::table('cidades')->insert(['id' => 2202554, 'estado_id' => 22, 'nome' => 'Caridade do Piauí']);
		DB::table('cidades')->insert(['id' => 2202604, 'estado_id' => 22, 'nome' => 'Castelo do Piauí']);
		DB::table('cidades')->insert(['id' => 2202653, 'estado_id' => 22, 'nome' => 'Caxingó']);
		DB::table('cidades')->insert(['id' => 2202703, 'estado_id' => 22, 'nome' => 'Cocal']);
		DB::table('cidades')->insert(['id' => 2202711, 'estado_id' => 22, 'nome' => 'Cocal de Telha']);
		DB::table('cidades')->insert(['id' => 2202729, 'estado_id' => 22, 'nome' => 'Cocal dos Alves']);
		DB::table('cidades')->insert(['id' => 2202737, 'estado_id' => 22, 'nome' => 'Coivaras']);
		DB::table('cidades')->insert(['id' => 2202752, 'estado_id' => 22, 'nome' => 'Colônia do Gurguéia']);
		DB::table('cidades')->insert(['id' => 2202778, 'estado_id' => 22, 'nome' => 'Colônia do Piauí']);
		DB::table('cidades')->insert(['id' => 2202802, 'estado_id' => 22, 'nome' => 'Conceição do Canindé']);
		DB::table('cidades')->insert(['id' => 2202851, 'estado_id' => 22, 'nome' => 'Coronel José Dias']);
		DB::table('cidades')->insert(['id' => 2202901, 'estado_id' => 22, 'nome' => 'Corrente']);
		DB::table('cidades')->insert(['id' => 2203008, 'estado_id' => 22, 'nome' => 'Cristalândia do Piauí']);
		DB::table('cidades')->insert(['id' => 2203107, 'estado_id' => 22, 'nome' => 'Cristino Castro']);
		DB::table('cidades')->insert(['id' => 2203206, 'estado_id' => 22, 'nome' => 'Curimatá']);
		DB::table('cidades')->insert(['id' => 2203230, 'estado_id' => 22, 'nome' => 'Currais']);
		DB::table('cidades')->insert(['id' => 2203255, 'estado_id' => 22, 'nome' => 'Curralinhos']);
		DB::table('cidades')->insert(['id' => 2203271, 'estado_id' => 22, 'nome' => 'Curral Novo do Piauí']);
		DB::table('cidades')->insert(['id' => 2203305, 'estado_id' => 22, 'nome' => 'Demerval Lobão']);
		DB::table('cidades')->insert(['id' => 2203354, 'estado_id' => 22, 'nome' => 'Dirceu Arcoverde']);
		DB::table('cidades')->insert(['id' => 2203404, 'estado_id' => 22, 'nome' => 'Dom Expedito Lopes']);
		DB::table('cidades')->insert(['id' => 2203420, 'estado_id' => 22, 'nome' => 'Domingos Mourão']);
		DB::table('cidades')->insert(['id' => 2203453, 'estado_id' => 22, 'nome' => 'Dom Inocêncio']);
		DB::table('cidades')->insert(['id' => 2203503, 'estado_id' => 22, 'nome' => 'Elesbão Veloso']);
		DB::table('cidades')->insert(['id' => 2203602, 'estado_id' => 22, 'nome' => 'Eliseu Martins']);
		DB::table('cidades')->insert(['id' => 2203701, 'estado_id' => 22, 'nome' => 'Esperantina']);
		DB::table('cidades')->insert(['id' => 2203750, 'estado_id' => 22, 'nome' => 'Fartura do Piauí']);
		DB::table('cidades')->insert(['id' => 2203800, 'estado_id' => 22, 'nome' => 'Flores do Piauí']);
		DB::table('cidades')->insert(['id' => 2203859, 'estado_id' => 22, 'nome' => 'Floresta do Piauí']);
		DB::table('cidades')->insert(['id' => 2203909, 'estado_id' => 22, 'nome' => 'Floriano']);
		DB::table('cidades')->insert(['id' => 2204006, 'estado_id' => 22, 'nome' => 'Francinópolis']);
		DB::table('cidades')->insert(['id' => 2204105, 'estado_id' => 22, 'nome' => 'Francisco Ayres']);
		DB::table('cidades')->insert(['id' => 2204154, 'estado_id' => 22, 'nome' => 'Francisco Macedo']);
		DB::table('cidades')->insert(['id' => 2204204, 'estado_id' => 22, 'nome' => 'Francisco Santos']);
		DB::table('cidades')->insert(['id' => 2204303, 'estado_id' => 22, 'nome' => 'Fronteiras']);
		DB::table('cidades')->insert(['id' => 2204352, 'estado_id' => 22, 'nome' => 'Geminiano']);
		DB::table('cidades')->insert(['id' => 2204402, 'estado_id' => 22, 'nome' => 'Gilbués']);
		DB::table('cidades')->insert(['id' => 2204501, 'estado_id' => 22, 'nome' => 'Guadalupe']);
		DB::table('cidades')->insert(['id' => 2204550, 'estado_id' => 22, 'nome' => 'Guaribas']);
		DB::table('cidades')->insert(['id' => 2204600, 'estado_id' => 22, 'nome' => 'Hugo Napoleão']);
		DB::table('cidades')->insert(['id' => 2204659, 'estado_id' => 22, 'nome' => 'Ilha Grande']);
		DB::table('cidades')->insert(['id' => 2204709, 'estado_id' => 22, 'nome' => 'Inhuma']);
		DB::table('cidades')->insert(['id' => 2204808, 'estado_id' => 22, 'nome' => 'Ipiranga do Piauí']);
		DB::table('cidades')->insert(['id' => 2204907, 'estado_id' => 22, 'nome' => 'Isaías Coelho']);
		DB::table('cidades')->insert(['id' => 2205003, 'estado_id' => 22, 'nome' => 'Itainópolis']);
		DB::table('cidades')->insert(['id' => 2205102, 'estado_id' => 22, 'nome' => 'Itaueira']);
		DB::table('cidades')->insert(['id' => 2205151, 'estado_id' => 22, 'nome' => 'Jacobina do Piauí']);
		DB::table('cidades')->insert(['id' => 2205201, 'estado_id' => 22, 'nome' => 'Jaicós']);
		DB::table('cidades')->insert(['id' => 2205250, 'estado_id' => 22, 'nome' => 'Jardim do Mulato']);
		DB::table('cidades')->insert(['id' => 2205276, 'estado_id' => 22, 'nome' => 'Jatobá do Piauí']);
		DB::table('cidades')->insert(['id' => 2205300, 'estado_id' => 22, 'nome' => 'Jerumenha']);
		DB::table('cidades')->insert(['id' => 2205359, 'estado_id' => 22, 'nome' => 'João Costa']);
		DB::table('cidades')->insert(['id' => 2205409, 'estado_id' => 22, 'nome' => 'Joaquim Pires']);
		DB::table('cidades')->insert(['id' => 2205458, 'estado_id' => 22, 'nome' => 'Joca Marques']);
		DB::table('cidades')->insert(['id' => 2205508, 'estado_id' => 22, 'nome' => 'José de Freitas']);
		DB::table('cidades')->insert(['id' => 2205516, 'estado_id' => 22, 'nome' => 'Juazeiro do Piauí']);
		DB::table('cidades')->insert(['id' => 2205524, 'estado_id' => 22, 'nome' => 'Júlio Borges']);
		DB::table('cidades')->insert(['id' => 2205532, 'estado_id' => 22, 'nome' => 'Jurema']);
		DB::table('cidades')->insert(['id' => 2205540, 'estado_id' => 22, 'nome' => 'Lagoinha do Piauí']);
		DB::table('cidades')->insert(['id' => 2205557, 'estado_id' => 22, 'nome' => 'Lagoa Alegre']);
		DB::table('cidades')->insert(['id' => 2205565, 'estado_id' => 22, 'nome' => 'Lagoa do Barro do Piauí']);
		DB::table('cidades')->insert(['id' => 2205573, 'estado_id' => 22, 'nome' => 'Lagoa de São Francisco']);
		DB::table('cidades')->insert(['id' => 2205581, 'estado_id' => 22, 'nome' => 'Lagoa do Piauí']);
		DB::table('cidades')->insert(['id' => 2205599, 'estado_id' => 22, 'nome' => 'Lagoa do Sítio']);
		DB::table('cidades')->insert(['id' => 2205607, 'estado_id' => 22, 'nome' => 'Landri Sales']);
		DB::table('cidades')->insert(['id' => 2205706, 'estado_id' => 22, 'nome' => 'Luís Correia']);
		DB::table('cidades')->insert(['id' => 2205805, 'estado_id' => 22, 'nome' => 'Luzilândia']);
		DB::table('cidades')->insert(['id' => 2205854, 'estado_id' => 22, 'nome' => 'Madeiro']);
		DB::table('cidades')->insert(['id' => 2205904, 'estado_id' => 22, 'nome' => 'Manoel Emídio']);
		DB::table('cidades')->insert(['id' => 2205953, 'estado_id' => 22, 'nome' => 'Marcolândia']);
		DB::table('cidades')->insert(['id' => 2206001, 'estado_id' => 22, 'nome' => 'Marcos Parente']);
		DB::table('cidades')->insert(['id' => 2206050, 'estado_id' => 22, 'nome' => 'Massapê do Piauí']);
		DB::table('cidades')->insert(['id' => 2206100, 'estado_id' => 22, 'nome' => 'Matias Olímpio']);
		DB::table('cidades')->insert(['id' => 2206209, 'estado_id' => 22, 'nome' => 'Miguel Alves']);
		DB::table('cidades')->insert(['id' => 2206308, 'estado_id' => 22, 'nome' => 'Miguel Leão']);
		DB::table('cidades')->insert(['id' => 2206357, 'estado_id' => 22, 'nome' => 'Milton Brandão']);
		DB::table('cidades')->insert(['id' => 2206407, 'estado_id' => 22, 'nome' => 'Monsenhor Gil']);
		DB::table('cidades')->insert(['id' => 2206506, 'estado_id' => 22, 'nome' => 'Monsenhor Hipólito']);
		DB::table('cidades')->insert(['id' => 2206605, 'estado_id' => 22, 'nome' => 'Monte Alegre do Piauí']);
		DB::table('cidades')->insert(['id' => 2206654, 'estado_id' => 22, 'nome' => 'Morro Cabeça no Tempo']);
		DB::table('cidades')->insert(['id' => 2206670, 'estado_id' => 22, 'nome' => 'Morro do Chapéu do Piauí']);
		DB::table('cidades')->insert(['id' => 2206696, 'estado_id' => 22, 'nome' => 'Murici dos Portelas']);
		DB::table('cidades')->insert(['id' => 2206704, 'estado_id' => 22, 'nome' => 'Nazaré do Piauí']);
		DB::table('cidades')->insert(['id' => 2206753, 'estado_id' => 22, 'nome' => 'Nossa Senhora de Nazaré']);
		DB::table('cidades')->insert(['id' => 2206803, 'estado_id' => 22, 'nome' => 'Nossa Senhora dos Remédios']);
		DB::table('cidades')->insert(['id' => 2206902, 'estado_id' => 22, 'nome' => 'Novo Oriente do Piauí']);
		DB::table('cidades')->insert(['id' => 2206951, 'estado_id' => 22, 'nome' => 'Novo Santo Antônio']);
		DB::table('cidades')->insert(['id' => 2207009, 'estado_id' => 22, 'nome' => 'Oeiras']);
		DB::table('cidades')->insert(['id' => 2207108, 'estado_id' => 22, 'nome' => 'Olho D\'Água do Piauí']);
		DB::table('cidades')->insert(['id' => 2207207, 'estado_id' => 22, 'nome' => 'Padre Marcos']);
		DB::table('cidades')->insert(['id' => 2207306, 'estado_id' => 22, 'nome' => 'Paes Landim']);
		DB::table('cidades')->insert(['id' => 2207355, 'estado_id' => 22, 'nome' => 'Pajeú do Piauí']);
		DB::table('cidades')->insert(['id' => 2207405, 'estado_id' => 22, 'nome' => 'Palmeira do Piauí']);
		DB::table('cidades')->insert(['id' => 2207504, 'estado_id' => 22, 'nome' => 'Palmeirais']);
		DB::table('cidades')->insert(['id' => 2207553, 'estado_id' => 22, 'nome' => 'Paquetá']);
		DB::table('cidades')->insert(['id' => 2207603, 'estado_id' => 22, 'nome' => 'Parnaguá']);
		DB::table('cidades')->insert(['id' => 2207702, 'estado_id' => 22, 'nome' => 'Parnaíba']);
		DB::table('cidades')->insert(['id' => 2207751, 'estado_id' => 22, 'nome' => 'Passagem Franca do Piauí']);
		DB::table('cidades')->insert(['id' => 2207777, 'estado_id' => 22, 'nome' => 'Patos do Piauí']);
		DB::table('cidades')->insert(['id' => 2207793, 'estado_id' => 22, 'nome' => 'Pau D\'Arco do Piauí']);
		DB::table('cidades')->insert(['id' => 2207801, 'estado_id' => 22, 'nome' => 'Paulistana']);
		DB::table('cidades')->insert(['id' => 2207850, 'estado_id' => 22, 'nome' => 'Pavussu']);
		DB::table('cidades')->insert(['id' => 2207900, 'estado_id' => 22, 'nome' => 'Pedro II']);
		DB::table('cidades')->insert(['id' => 2207934, 'estado_id' => 22, 'nome' => 'Pedro Laurentino']);
		DB::table('cidades')->insert(['id' => 2207959, 'estado_id' => 22, 'nome' => 'Nova Santa Rita']);
		DB::table('cidades')->insert(['id' => 2208007, 'estado_id' => 22, 'nome' => 'Picos']);
		DB::table('cidades')->insert(['id' => 2208106, 'estado_id' => 22, 'nome' => 'Pimenteiras']);
		DB::table('cidades')->insert(['id' => 2208205, 'estado_id' => 22, 'nome' => 'Pio IX']);
		DB::table('cidades')->insert(['id' => 2208304, 'estado_id' => 22, 'nome' => 'Piracuruca']);
		DB::table('cidades')->insert(['id' => 2208403, 'estado_id' => 22, 'nome' => 'Piripiri']);
		DB::table('cidades')->insert(['id' => 2208502, 'estado_id' => 22, 'nome' => 'Porto']);
		DB::table('cidades')->insert(['id' => 2208551, 'estado_id' => 22, 'nome' => 'Porto Alegre do Piauí']);
		DB::table('cidades')->insert(['id' => 2208601, 'estado_id' => 22, 'nome' => 'Prata do Piauí']);
		DB::table('cidades')->insert(['id' => 2208650, 'estado_id' => 22, 'nome' => 'Queimada Nova']);
		DB::table('cidades')->insert(['id' => 2208700, 'estado_id' => 22, 'nome' => 'Redenção do Gurguéia']);
		DB::table('cidades')->insert(['id' => 2208809, 'estado_id' => 22, 'nome' => 'Regeneração']);
		DB::table('cidades')->insert(['id' => 2208858, 'estado_id' => 22, 'nome' => 'Riacho Frio']);
		DB::table('cidades')->insert(['id' => 2208874, 'estado_id' => 22, 'nome' => 'Ribeira do Piauí']);
		DB::table('cidades')->insert(['id' => 2208908, 'estado_id' => 22, 'nome' => 'Ribeiro Gonçalves']);
		DB::table('cidades')->insert(['id' => 2209005, 'estado_id' => 22, 'nome' => 'Rio Grande do Piauí']);
		DB::table('cidades')->insert(['id' => 2209104, 'estado_id' => 22, 'nome' => 'Santa Cruz do Piauí']);
		DB::table('cidades')->insert(['id' => 2209153, 'estado_id' => 22, 'nome' => 'Santa Cruz dos Milagres']);
		DB::table('cidades')->insert(['id' => 2209203, 'estado_id' => 22, 'nome' => 'Santa Filomena']);
		DB::table('cidades')->insert(['id' => 2209302, 'estado_id' => 22, 'nome' => 'Santa Luz']);
		DB::table('cidades')->insert(['id' => 2209351, 'estado_id' => 22, 'nome' => 'Santana do Piauí']);
		DB::table('cidades')->insert(['id' => 2209377, 'estado_id' => 22, 'nome' => 'Santa Rosa do Piauí']);
		DB::table('cidades')->insert(['id' => 2209401, 'estado_id' => 22, 'nome' => 'Santo Antônio de Lisboa']);
		DB::table('cidades')->insert(['id' => 2209450, 'estado_id' => 22, 'nome' => 'Santo Antônio dos Milagres']);
		DB::table('cidades')->insert(['id' => 2209500, 'estado_id' => 22, 'nome' => 'Santo Inácio do Piauí']);
		DB::table('cidades')->insert(['id' => 2209559, 'estado_id' => 22, 'nome' => 'São Braz do Piauí']);
		DB::table('cidades')->insert(['id' => 2209609, 'estado_id' => 22, 'nome' => 'São Félix do Piauí']);
		DB::table('cidades')->insert(['id' => 2209658, 'estado_id' => 22, 'nome' => 'São Francisco de Assis do Piauí']);
		DB::table('cidades')->insert(['id' => 2209708, 'estado_id' => 22, 'nome' => 'São Francisco do Piauí']);
		DB::table('cidades')->insert(['id' => 2209757, 'estado_id' => 22, 'nome' => 'São Gonçalo do Gurguéia']);
		DB::table('cidades')->insert(['id' => 2209807, 'estado_id' => 22, 'nome' => 'São Gonçalo do Piauí']);
		DB::table('cidades')->insert(['id' => 2209856, 'estado_id' => 22, 'nome' => 'São João da Canabrava']);
		DB::table('cidades')->insert(['id' => 2209872, 'estado_id' => 22, 'nome' => 'São João da Fronteira']);
		DB::table('cidades')->insert(['id' => 2209906, 'estado_id' => 22, 'nome' => 'São João da Serra']);
		DB::table('cidades')->insert(['id' => 2209955, 'estado_id' => 22, 'nome' => 'São João da Varjota']);
		DB::table('cidades')->insert(['id' => 2209971, 'estado_id' => 22, 'nome' => 'São João do Arraial']);
		DB::table('cidades')->insert(['id' => 2210003, 'estado_id' => 22, 'nome' => 'São João do Piauí']);
		DB::table('cidades')->insert(['id' => 2210052, 'estado_id' => 22, 'nome' => 'São José do Divino']);
		DB::table('cidades')->insert(['id' => 2210102, 'estado_id' => 22, 'nome' => 'São José do Peixe']);
		DB::table('cidades')->insert(['id' => 2210201, 'estado_id' => 22, 'nome' => 'São José do Piauí']);
		DB::table('cidades')->insert(['id' => 2210300, 'estado_id' => 22, 'nome' => 'São Julião']);
		DB::table('cidades')->insert(['id' => 2210359, 'estado_id' => 22, 'nome' => 'São Lourenço do Piauí']);
		DB::table('cidades')->insert(['id' => 2210375, 'estado_id' => 22, 'nome' => 'São Luis do Piauí']);
		DB::table('cidades')->insert(['id' => 2210383, 'estado_id' => 22, 'nome' => 'São Miguel da Baixa Grande']);
		DB::table('cidades')->insert(['id' => 2210391, 'estado_id' => 22, 'nome' => 'São Miguel do Fidalgo']);
		DB::table('cidades')->insert(['id' => 2210409, 'estado_id' => 22, 'nome' => 'São Miguel do Tapuio']);
		DB::table('cidades')->insert(['id' => 2210508, 'estado_id' => 22, 'nome' => 'São Pedro do Piauí']);
		DB::table('cidades')->insert(['id' => 2210607, 'estado_id' => 22, 'nome' => 'São Raimundo Nonato']);
		DB::table('cidades')->insert(['id' => 2210623, 'estado_id' => 22, 'nome' => 'Sebastião Barros']);
		DB::table('cidades')->insert(['id' => 2210631, 'estado_id' => 22, 'nome' => 'Sebastião Leal']);
		DB::table('cidades')->insert(['id' => 2210656, 'estado_id' => 22, 'nome' => 'Sigefredo Pacheco']);
		DB::table('cidades')->insert(['id' => 2210706, 'estado_id' => 22, 'nome' => 'Simões']);
		DB::table('cidades')->insert(['id' => 2210805, 'estado_id' => 22, 'nome' => 'Simplício Mendes']);
		DB::table('cidades')->insert(['id' => 2210904, 'estado_id' => 22, 'nome' => 'Socorro do Piauí']);
		DB::table('cidades')->insert(['id' => 2210938, 'estado_id' => 22, 'nome' => 'Sussuapara']);
		DB::table('cidades')->insert(['id' => 2210953, 'estado_id' => 22, 'nome' => 'Tamboril do Piauí']);
		DB::table('cidades')->insert(['id' => 2210979, 'estado_id' => 22, 'nome' => 'Tanque do Piauí']);
		DB::table('cidades')->insert(['id' => 2211001, 'estado_id' => 22, 'nome' => 'Teresina']);
		DB::table('cidades')->insert(['id' => 2211100, 'estado_id' => 22, 'nome' => 'União']);
		DB::table('cidades')->insert(['id' => 2211209, 'estado_id' => 22, 'nome' => 'Uruçuí']);
		DB::table('cidades')->insert(['id' => 2211308, 'estado_id' => 22, 'nome' => 'Valença do Piauí']);
		DB::table('cidades')->insert(['id' => 2211357, 'estado_id' => 22, 'nome' => 'Várzea Branca']);
		DB::table('cidades')->insert(['id' => 2211407, 'estado_id' => 22, 'nome' => 'Várzea Grande']);
		DB::table('cidades')->insert(['id' => 2211506, 'estado_id' => 22, 'nome' => 'Vera Mendes']);
		DB::table('cidades')->insert(['id' => 2211605, 'estado_id' => 22, 'nome' => 'Vila Nova do Piauí']);
		DB::table('cidades')->insert(['id' => 2211704, 'estado_id' => 22, 'nome' => 'Wall Ferraz']);
    }
}
