<?php

use Illuminate\Database\Seeder;

class CidadesTableSCSeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades de Santa Catarina
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 4200051, 'estado_id' => 42, 'nome' => 'Abdon Batista']);
		DB::table('cidades')->insert(['id' => 4200101, 'estado_id' => 42, 'nome' => 'Abelardo Luz']);
		DB::table('cidades')->insert(['id' => 4200200, 'estado_id' => 42, 'nome' => 'Agrolândia']);
		DB::table('cidades')->insert(['id' => 4200309, 'estado_id' => 42, 'nome' => 'Agronômica']);
		DB::table('cidades')->insert(['id' => 4200408, 'estado_id' => 42, 'nome' => 'Água Doce']);
		DB::table('cidades')->insert(['id' => 4200507, 'estado_id' => 42, 'nome' => 'Águas de Chapecó']);
		DB::table('cidades')->insert(['id' => 4200556, 'estado_id' => 42, 'nome' => 'Águas Frias']);
		DB::table('cidades')->insert(['id' => 4200606, 'estado_id' => 42, 'nome' => 'Águas Mornas']);
		DB::table('cidades')->insert(['id' => 4200705, 'estado_id' => 42, 'nome' => 'Alfredo Wagner']);
		DB::table('cidades')->insert(['id' => 4200754, 'estado_id' => 42, 'nome' => 'Alto Bela Vista']);
		DB::table('cidades')->insert(['id' => 4200804, 'estado_id' => 42, 'nome' => 'Anchieta']);
		DB::table('cidades')->insert(['id' => 4200903, 'estado_id' => 42, 'nome' => 'Angelina']);
		DB::table('cidades')->insert(['id' => 4201000, 'estado_id' => 42, 'nome' => 'Anita Garibaldi']);
		DB::table('cidades')->insert(['id' => 4201109, 'estado_id' => 42, 'nome' => 'Anitápolis']);
		DB::table('cidades')->insert(['id' => 4201208, 'estado_id' => 42, 'nome' => 'Antônio Carlos']);
		DB::table('cidades')->insert(['id' => 4201257, 'estado_id' => 42, 'nome' => 'Apiúna']);
		DB::table('cidades')->insert(['id' => 4201273, 'estado_id' => 42, 'nome' => 'Arabutã']);
		DB::table('cidades')->insert(['id' => 4201307, 'estado_id' => 42, 'nome' => 'Araquari']);
		DB::table('cidades')->insert(['id' => 4201406, 'estado_id' => 42, 'nome' => 'Araranguá']);
		DB::table('cidades')->insert(['id' => 4201505, 'estado_id' => 42, 'nome' => 'Armazém']);
		DB::table('cidades')->insert(['id' => 4201604, 'estado_id' => 42, 'nome' => 'Arroio Trinta']);
		DB::table('cidades')->insert(['id' => 4201653, 'estado_id' => 42, 'nome' => 'Arvoredo']);
		DB::table('cidades')->insert(['id' => 4201703, 'estado_id' => 42, 'nome' => 'Ascurra']);
		DB::table('cidades')->insert(['id' => 4201802, 'estado_id' => 42, 'nome' => 'Atalanta']);
		DB::table('cidades')->insert(['id' => 4201901, 'estado_id' => 42, 'nome' => 'Aurora']);
		DB::table('cidades')->insert(['id' => 4201950, 'estado_id' => 42, 'nome' => 'Balneário Arroio do Silva']);
		DB::table('cidades')->insert(['id' => 4202008, 'estado_id' => 42, 'nome' => 'Balneário Camboriú']);
		DB::table('cidades')->insert(['id' => 4202057, 'estado_id' => 42, 'nome' => 'Balneário Barra do Sul']);
		DB::table('cidades')->insert(['id' => 4202073, 'estado_id' => 42, 'nome' => 'Balneário Gaivota']);
		DB::table('cidades')->insert(['id' => 4202081, 'estado_id' => 42, 'nome' => 'Bandeirante']);
		DB::table('cidades')->insert(['id' => 4202099, 'estado_id' => 42, 'nome' => 'Barra Bonita']);
		DB::table('cidades')->insert(['id' => 4202107, 'estado_id' => 42, 'nome' => 'Barra Velha']);
		DB::table('cidades')->insert(['id' => 4202131, 'estado_id' => 42, 'nome' => 'Bela Vista do Toldo']);
		DB::table('cidades')->insert(['id' => 4202156, 'estado_id' => 42, 'nome' => 'Belmonte']);
		DB::table('cidades')->insert(['id' => 4202206, 'estado_id' => 42, 'nome' => 'Benedito Novo']);
		DB::table('cidades')->insert(['id' => 4202305, 'estado_id' => 42, 'nome' => 'Biguaçu']);
		DB::table('cidades')->insert(['id' => 4202404, 'estado_id' => 42, 'nome' => 'Blumenau']);
		DB::table('cidades')->insert(['id' => 4202438, 'estado_id' => 42, 'nome' => 'Bocaina do Sul']);
		DB::table('cidades')->insert(['id' => 4202453, 'estado_id' => 42, 'nome' => 'Bombinhas']);
		DB::table('cidades')->insert(['id' => 4202503, 'estado_id' => 42, 'nome' => 'Bom Jardim da Serra']);
		DB::table('cidades')->insert(['id' => 4202537, 'estado_id' => 42, 'nome' => 'Bom Jesus']);
		DB::table('cidades')->insert(['id' => 4202578, 'estado_id' => 42, 'nome' => 'Bom Jesus do Oeste']);
		DB::table('cidades')->insert(['id' => 4202602, 'estado_id' => 42, 'nome' => 'Bom Retiro']);
		DB::table('cidades')->insert(['id' => 4202701, 'estado_id' => 42, 'nome' => 'Botuverá']);
		DB::table('cidades')->insert(['id' => 4202800, 'estado_id' => 42, 'nome' => 'Braço do Norte']);
		DB::table('cidades')->insert(['id' => 4202859, 'estado_id' => 42, 'nome' => 'Braço do Trombudo']);
		DB::table('cidades')->insert(['id' => 4202875, 'estado_id' => 42, 'nome' => 'Brunópolis']);
		DB::table('cidades')->insert(['id' => 4202909, 'estado_id' => 42, 'nome' => 'Brusque']);
		DB::table('cidades')->insert(['id' => 4203006, 'estado_id' => 42, 'nome' => 'Caçador']);
		DB::table('cidades')->insert(['id' => 4203105, 'estado_id' => 42, 'nome' => 'Caibi']);
		DB::table('cidades')->insert(['id' => 4203154, 'estado_id' => 42, 'nome' => 'Calmon']);
		DB::table('cidades')->insert(['id' => 4203204, 'estado_id' => 42, 'nome' => 'Camboriú']);
		DB::table('cidades')->insert(['id' => 4203253, 'estado_id' => 42, 'nome' => 'Capão Alto']);
		DB::table('cidades')->insert(['id' => 4203303, 'estado_id' => 42, 'nome' => 'Campo Alegre']);
		DB::table('cidades')->insert(['id' => 4203402, 'estado_id' => 42, 'nome' => 'Campo Belo do Sul']);
		DB::table('cidades')->insert(['id' => 4203501, 'estado_id' => 42, 'nome' => 'Campo Erê']);
		DB::table('cidades')->insert(['id' => 4203600, 'estado_id' => 42, 'nome' => 'Campos Novos']);
		DB::table('cidades')->insert(['id' => 4203709, 'estado_id' => 42, 'nome' => 'Canelinha']);
		DB::table('cidades')->insert(['id' => 4203808, 'estado_id' => 42, 'nome' => 'Canoinhas']);
		DB::table('cidades')->insert(['id' => 4203907, 'estado_id' => 42, 'nome' => 'Capinzal']);
		DB::table('cidades')->insert(['id' => 4203956, 'estado_id' => 42, 'nome' => 'Capivari de Baixo']);
		DB::table('cidades')->insert(['id' => 4204004, 'estado_id' => 42, 'nome' => 'Catanduvas']);
		DB::table('cidades')->insert(['id' => 4204103, 'estado_id' => 42, 'nome' => 'Caxambu do Sul']);
		DB::table('cidades')->insert(['id' => 4204152, 'estado_id' => 42, 'nome' => 'Celso Ramos']);
		DB::table('cidades')->insert(['id' => 4204178, 'estado_id' => 42, 'nome' => 'Cerro Negro']);
		DB::table('cidades')->insert(['id' => 4204194, 'estado_id' => 42, 'nome' => 'Chapadão do Lageado']);
		DB::table('cidades')->insert(['id' => 4204202, 'estado_id' => 42, 'nome' => 'Chapecó']);
		DB::table('cidades')->insert(['id' => 4204251, 'estado_id' => 42, 'nome' => 'Cocal do Sul']);
		DB::table('cidades')->insert(['id' => 4204301, 'estado_id' => 42, 'nome' => 'Concórdia']);
		DB::table('cidades')->insert(['id' => 4204350, 'estado_id' => 42, 'nome' => 'Cordilheira Alta']);
		DB::table('cidades')->insert(['id' => 4204400, 'estado_id' => 42, 'nome' => 'Coronel Freitas']);
		DB::table('cidades')->insert(['id' => 4204459, 'estado_id' => 42, 'nome' => 'Coronel Martins']);
		DB::table('cidades')->insert(['id' => 4204509, 'estado_id' => 42, 'nome' => 'Corupá']);
		DB::table('cidades')->insert(['id' => 4204558, 'estado_id' => 42, 'nome' => 'Correia Pinto']);
		DB::table('cidades')->insert(['id' => 4204608, 'estado_id' => 42, 'nome' => 'Criciúma']);
		DB::table('cidades')->insert(['id' => 4204707, 'estado_id' => 42, 'nome' => 'Cunha Porã']);
		DB::table('cidades')->insert(['id' => 4204756, 'estado_id' => 42, 'nome' => 'Cunhataí']);
		DB::table('cidades')->insert(['id' => 4204806, 'estado_id' => 42, 'nome' => 'Curitibanos']);
		DB::table('cidades')->insert(['id' => 4204905, 'estado_id' => 42, 'nome' => 'Descanso']);
		DB::table('cidades')->insert(['id' => 4205001, 'estado_id' => 42, 'nome' => 'Dionísio Cerqueira']);
		DB::table('cidades')->insert(['id' => 4205100, 'estado_id' => 42, 'nome' => 'Dona Emma']);
		DB::table('cidades')->insert(['id' => 4205159, 'estado_id' => 42, 'nome' => 'Doutor Pedrinho']);
		DB::table('cidades')->insert(['id' => 4205175, 'estado_id' => 42, 'nome' => 'Entre Rios']);
		DB::table('cidades')->insert(['id' => 4205191, 'estado_id' => 42, 'nome' => 'Ermo']);
		DB::table('cidades')->insert(['id' => 4205209, 'estado_id' => 42, 'nome' => 'Erval Velho']);
		DB::table('cidades')->insert(['id' => 4205308, 'estado_id' => 42, 'nome' => 'Faxinal dos Guedes']);
		DB::table('cidades')->insert(['id' => 4205357, 'estado_id' => 42, 'nome' => 'Flor do Sertão']);
		DB::table('cidades')->insert(['id' => 4205407, 'estado_id' => 42, 'nome' => 'Florianópolis']);
		DB::table('cidades')->insert(['id' => 4205431, 'estado_id' => 42, 'nome' => 'Formosa do Sul']);
		DB::table('cidades')->insert(['id' => 4205456, 'estado_id' => 42, 'nome' => 'Forquilhinha']);
		DB::table('cidades')->insert(['id' => 4205506, 'estado_id' => 42, 'nome' => 'Fraiburgo']);
		DB::table('cidades')->insert(['id' => 4205555, 'estado_id' => 42, 'nome' => 'Frei Rogério']);
		DB::table('cidades')->insert(['id' => 4205605, 'estado_id' => 42, 'nome' => 'Galvão']);
		DB::table('cidades')->insert(['id' => 4205704, 'estado_id' => 42, 'nome' => 'Garopaba']);
		DB::table('cidades')->insert(['id' => 4205803, 'estado_id' => 42, 'nome' => 'Garuva']);
		DB::table('cidades')->insert(['id' => 4205902, 'estado_id' => 42, 'nome' => 'Gaspar']);
		DB::table('cidades')->insert(['id' => 4206009, 'estado_id' => 42, 'nome' => 'Governador Celso Ramos']);
		DB::table('cidades')->insert(['id' => 4206108, 'estado_id' => 42, 'nome' => 'Grão Pará']);
		DB::table('cidades')->insert(['id' => 4206207, 'estado_id' => 42, 'nome' => 'Gravatal']);
		DB::table('cidades')->insert(['id' => 4206306, 'estado_id' => 42, 'nome' => 'Guabiruba']);
		DB::table('cidades')->insert(['id' => 4206405, 'estado_id' => 42, 'nome' => 'Guaraciaba']);
		DB::table('cidades')->insert(['id' => 4206504, 'estado_id' => 42, 'nome' => 'Guaramirim']);
		DB::table('cidades')->insert(['id' => 4206603, 'estado_id' => 42, 'nome' => 'Guarujá do Sul']);
		DB::table('cidades')->insert(['id' => 4206652, 'estado_id' => 42, 'nome' => 'Guatambú']);
		DB::table('cidades')->insert(['id' => 4206702, 'estado_id' => 42, 'nome' => 'Herval d\'Oeste']);
		DB::table('cidades')->insert(['id' => 4206751, 'estado_id' => 42, 'nome' => 'Ibiam']);
		DB::table('cidades')->insert(['id' => 4206801, 'estado_id' => 42, 'nome' => 'Ibicaré']);
		DB::table('cidades')->insert(['id' => 4206900, 'estado_id' => 42, 'nome' => 'Ibirama']);
		DB::table('cidades')->insert(['id' => 4207007, 'estado_id' => 42, 'nome' => 'Içara']);
		DB::table('cidades')->insert(['id' => 4207106, 'estado_id' => 42, 'nome' => 'Ilhota']);
		DB::table('cidades')->insert(['id' => 4207205, 'estado_id' => 42, 'nome' => 'Imaruí']);
		DB::table('cidades')->insert(['id' => 4207304, 'estado_id' => 42, 'nome' => 'Imbituba']);
		DB::table('cidades')->insert(['id' => 4207403, 'estado_id' => 42, 'nome' => 'Imbuia']);
		DB::table('cidades')->insert(['id' => 4207502, 'estado_id' => 42, 'nome' => 'Indaial']);
		DB::table('cidades')->insert(['id' => 4207577, 'estado_id' => 42, 'nome' => 'Iomerê']);
		DB::table('cidades')->insert(['id' => 4207601, 'estado_id' => 42, 'nome' => 'Ipira']);
		DB::table('cidades')->insert(['id' => 4207650, 'estado_id' => 42, 'nome' => 'Iporã do Oeste']);
		DB::table('cidades')->insert(['id' => 4207684, 'estado_id' => 42, 'nome' => 'Ipuaçu']);
		DB::table('cidades')->insert(['id' => 4207700, 'estado_id' => 42, 'nome' => 'Ipumirim']);
		DB::table('cidades')->insert(['id' => 4207759, 'estado_id' => 42, 'nome' => 'Iraceminha']);
		DB::table('cidades')->insert(['id' => 4207809, 'estado_id' => 42, 'nome' => 'Irani']);
		DB::table('cidades')->insert(['id' => 4207858, 'estado_id' => 42, 'nome' => 'Irati']);
		DB::table('cidades')->insert(['id' => 4207908, 'estado_id' => 42, 'nome' => 'Irineópolis']);
		DB::table('cidades')->insert(['id' => 4208005, 'estado_id' => 42, 'nome' => 'Itá']);
		DB::table('cidades')->insert(['id' => 4208104, 'estado_id' => 42, 'nome' => 'Itaiópolis']);
		DB::table('cidades')->insert(['id' => 4208203, 'estado_id' => 42, 'nome' => 'Itajaí']);
		DB::table('cidades')->insert(['id' => 4208302, 'estado_id' => 42, 'nome' => 'Itapema']);
		DB::table('cidades')->insert(['id' => 4208401, 'estado_id' => 42, 'nome' => 'Itapiranga']);
		DB::table('cidades')->insert(['id' => 4208450, 'estado_id' => 42, 'nome' => 'Itapoá']);
		DB::table('cidades')->insert(['id' => 4208500, 'estado_id' => 42, 'nome' => 'Ituporanga']);
		DB::table('cidades')->insert(['id' => 4208609, 'estado_id' => 42, 'nome' => 'Jaborá']);
		DB::table('cidades')->insert(['id' => 4208708, 'estado_id' => 42, 'nome' => 'Jacinto Machado']);
		DB::table('cidades')->insert(['id' => 4208807, 'estado_id' => 42, 'nome' => 'Jaguaruna']);
		DB::table('cidades')->insert(['id' => 4208906, 'estado_id' => 42, 'nome' => 'Jaraguá do Sul']);
		DB::table('cidades')->insert(['id' => 4208955, 'estado_id' => 42, 'nome' => 'Jardinópolis']);
		DB::table('cidades')->insert(['id' => 4209003, 'estado_id' => 42, 'nome' => 'Joaçaba']);
		DB::table('cidades')->insert(['id' => 4209102, 'estado_id' => 42, 'nome' => 'Joinville']);
		DB::table('cidades')->insert(['id' => 4209151, 'estado_id' => 42, 'nome' => 'José Boiteux']);
		DB::table('cidades')->insert(['id' => 4209177, 'estado_id' => 42, 'nome' => 'Jupiá']);
		DB::table('cidades')->insert(['id' => 4209201, 'estado_id' => 42, 'nome' => 'Lacerdópolis']);
		DB::table('cidades')->insert(['id' => 4209300, 'estado_id' => 42, 'nome' => 'Lages']);
		DB::table('cidades')->insert(['id' => 4209409, 'estado_id' => 42, 'nome' => 'Laguna']);
		DB::table('cidades')->insert(['id' => 4209458, 'estado_id' => 42, 'nome' => 'Lajeado Grande']);
		DB::table('cidades')->insert(['id' => 4209508, 'estado_id' => 42, 'nome' => 'Laurentino']);
		DB::table('cidades')->insert(['id' => 4209607, 'estado_id' => 42, 'nome' => 'Lauro Muller']);
		DB::table('cidades')->insert(['id' => 4209706, 'estado_id' => 42, 'nome' => 'Lebon Régis']);
		DB::table('cidades')->insert(['id' => 4209805, 'estado_id' => 42, 'nome' => 'Leoberto Leal']);
		DB::table('cidades')->insert(['id' => 4209854, 'estado_id' => 42, 'nome' => 'Lindóia do Sul']);
		DB::table('cidades')->insert(['id' => 4209904, 'estado_id' => 42, 'nome' => 'Lontras']);
		DB::table('cidades')->insert(['id' => 4210001, 'estado_id' => 42, 'nome' => 'Luiz Alves']);
		DB::table('cidades')->insert(['id' => 4210035, 'estado_id' => 42, 'nome' => 'Luzerna']);
		DB::table('cidades')->insert(['id' => 4210050, 'estado_id' => 42, 'nome' => 'Macieira']);
		DB::table('cidades')->insert(['id' => 4210100, 'estado_id' => 42, 'nome' => 'Mafra']);
		DB::table('cidades')->insert(['id' => 4210209, 'estado_id' => 42, 'nome' => 'Major Gercino']);
		DB::table('cidades')->insert(['id' => 4210308, 'estado_id' => 42, 'nome' => 'Major Vieira']);
		DB::table('cidades')->insert(['id' => 4210407, 'estado_id' => 42, 'nome' => 'Maracajá']);
		DB::table('cidades')->insert(['id' => 4210506, 'estado_id' => 42, 'nome' => 'Maravilha']);
		DB::table('cidades')->insert(['id' => 4210555, 'estado_id' => 42, 'nome' => 'Marema']);
		DB::table('cidades')->insert(['id' => 4210605, 'estado_id' => 42, 'nome' => 'Massaranduba']);
		DB::table('cidades')->insert(['id' => 4210704, 'estado_id' => 42, 'nome' => 'Matos Costa']);
		DB::table('cidades')->insert(['id' => 4210803, 'estado_id' => 42, 'nome' => 'Meleiro']);
		DB::table('cidades')->insert(['id' => 4210852, 'estado_id' => 42, 'nome' => 'Mirim Doce']);
		DB::table('cidades')->insert(['id' => 4210902, 'estado_id' => 42, 'nome' => 'Modelo']);
		DB::table('cidades')->insert(['id' => 4211009, 'estado_id' => 42, 'nome' => 'Mondaí']);
		DB::table('cidades')->insert(['id' => 4211058, 'estado_id' => 42, 'nome' => 'Monte Carlo']);
		DB::table('cidades')->insert(['id' => 4211108, 'estado_id' => 42, 'nome' => 'Monte Castelo']);
		DB::table('cidades')->insert(['id' => 4211207, 'estado_id' => 42, 'nome' => 'Morro da Fumaça']);
		DB::table('cidades')->insert(['id' => 4211256, 'estado_id' => 42, 'nome' => 'Morro Grande']);
		DB::table('cidades')->insert(['id' => 4211306, 'estado_id' => 42, 'nome' => 'Navegantes']);
		DB::table('cidades')->insert(['id' => 4211405, 'estado_id' => 42, 'nome' => 'Nova Erechim']);
		DB::table('cidades')->insert(['id' => 4211454, 'estado_id' => 42, 'nome' => 'Nova Itaberaba']);
		DB::table('cidades')->insert(['id' => 4211504, 'estado_id' => 42, 'nome' => 'Nova Trento']);
		DB::table('cidades')->insert(['id' => 4211603, 'estado_id' => 42, 'nome' => 'Nova Veneza']);
		DB::table('cidades')->insert(['id' => 4211652, 'estado_id' => 42, 'nome' => 'Novo Horizonte']);
		DB::table('cidades')->insert(['id' => 4211702, 'estado_id' => 42, 'nome' => 'Orleans']);
		DB::table('cidades')->insert(['id' => 4211751, 'estado_id' => 42, 'nome' => 'Otacílio Costa']);
		DB::table('cidades')->insert(['id' => 4211801, 'estado_id' => 42, 'nome' => 'Ouro']);
		DB::table('cidades')->insert(['id' => 4211850, 'estado_id' => 42, 'nome' => 'Ouro Verde']);
		DB::table('cidades')->insert(['id' => 4211876, 'estado_id' => 42, 'nome' => 'Paial']);
		DB::table('cidades')->insert(['id' => 4211892, 'estado_id' => 42, 'nome' => 'Painel']);
		DB::table('cidades')->insert(['id' => 4211900, 'estado_id' => 42, 'nome' => 'Palhoça']);
		DB::table('cidades')->insert(['id' => 4212007, 'estado_id' => 42, 'nome' => 'Palma Sola']);
		DB::table('cidades')->insert(['id' => 4212056, 'estado_id' => 42, 'nome' => 'Palmeira']);
		DB::table('cidades')->insert(['id' => 4212106, 'estado_id' => 42, 'nome' => 'Palmitos']);
		DB::table('cidades')->insert(['id' => 4212205, 'estado_id' => 42, 'nome' => 'Papanduva']);
		DB::table('cidades')->insert(['id' => 4212239, 'estado_id' => 42, 'nome' => 'Paraíso']);
		DB::table('cidades')->insert(['id' => 4212254, 'estado_id' => 42, 'nome' => 'Passo de Torres']);
		DB::table('cidades')->insert(['id' => 4212270, 'estado_id' => 42, 'nome' => 'Passos Maia']);
		DB::table('cidades')->insert(['id' => 4212304, 'estado_id' => 42, 'nome' => 'Paulo Lopes']);
		DB::table('cidades')->insert(['id' => 4212403, 'estado_id' => 42, 'nome' => 'Pedras Grandes']);
		DB::table('cidades')->insert(['id' => 4212502, 'estado_id' => 42, 'nome' => 'Penha']);
		DB::table('cidades')->insert(['id' => 4212601, 'estado_id' => 42, 'nome' => 'Peritiba']);
		DB::table('cidades')->insert(['id' => 4212700, 'estado_id' => 42, 'nome' => 'Petrolândia']);
		DB::table('cidades')->insert(['id' => 4212809, 'estado_id' => 42, 'nome' => 'Balneário Piçarras']);
		DB::table('cidades')->insert(['id' => 4212908, 'estado_id' => 42, 'nome' => 'Pinhalzinho']);
		DB::table('cidades')->insert(['id' => 4213005, 'estado_id' => 42, 'nome' => 'Pinheiro Preto']);
		DB::table('cidades')->insert(['id' => 4213104, 'estado_id' => 42, 'nome' => 'Piratuba']);
		DB::table('cidades')->insert(['id' => 4213153, 'estado_id' => 42, 'nome' => 'Planalto Alegre']);
		DB::table('cidades')->insert(['id' => 4213203, 'estado_id' => 42, 'nome' => 'Pomerode']);
		DB::table('cidades')->insert(['id' => 4213302, 'estado_id' => 42, 'nome' => 'Ponte Alta']);
		DB::table('cidades')->insert(['id' => 4213351, 'estado_id' => 42, 'nome' => 'Ponte Alta do Norte']);
		DB::table('cidades')->insert(['id' => 4213401, 'estado_id' => 42, 'nome' => 'Ponte Serrada']);
		DB::table('cidades')->insert(['id' => 4213500, 'estado_id' => 42, 'nome' => 'Porto Belo']);
		DB::table('cidades')->insert(['id' => 4213609, 'estado_id' => 42, 'nome' => 'Porto União']);
		DB::table('cidades')->insert(['id' => 4213708, 'estado_id' => 42, 'nome' => 'Pouso Redondo']);
		DB::table('cidades')->insert(['id' => 4213807, 'estado_id' => 42, 'nome' => 'Praia Grande']);
		DB::table('cidades')->insert(['id' => 4213906, 'estado_id' => 42, 'nome' => 'Presidente Castello Branco']);
		DB::table('cidades')->insert(['id' => 4214003, 'estado_id' => 42, 'nome' => 'Presidente Getúlio']);
		DB::table('cidades')->insert(['id' => 4214102, 'estado_id' => 42, 'nome' => 'Presidente Nereu']);
		DB::table('cidades')->insert(['id' => 4214151, 'estado_id' => 42, 'nome' => 'Princesa']);
		DB::table('cidades')->insert(['id' => 4214201, 'estado_id' => 42, 'nome' => 'Quilombo']);
		DB::table('cidades')->insert(['id' => 4214300, 'estado_id' => 42, 'nome' => 'Rancho Queimado']);
		DB::table('cidades')->insert(['id' => 4214409, 'estado_id' => 42, 'nome' => 'Rio das Antas']);
		DB::table('cidades')->insert(['id' => 4214508, 'estado_id' => 42, 'nome' => 'Rio do Campo']);
		DB::table('cidades')->insert(['id' => 4214607, 'estado_id' => 42, 'nome' => 'Rio do Oeste']);
		DB::table('cidades')->insert(['id' => 4214706, 'estado_id' => 42, 'nome' => 'Rio dos Cedros']);
		DB::table('cidades')->insert(['id' => 4214805, 'estado_id' => 42, 'nome' => 'Rio do Sul']);
		DB::table('cidades')->insert(['id' => 4214904, 'estado_id' => 42, 'nome' => 'Rio Fortuna']);
		DB::table('cidades')->insert(['id' => 4215000, 'estado_id' => 42, 'nome' => 'Rio Negrinho']);
		DB::table('cidades')->insert(['id' => 4215059, 'estado_id' => 42, 'nome' => 'Rio Rufino']);
		DB::table('cidades')->insert(['id' => 4215075, 'estado_id' => 42, 'nome' => 'Riqueza']);
		DB::table('cidades')->insert(['id' => 4215109, 'estado_id' => 42, 'nome' => 'Rodeio']);
		DB::table('cidades')->insert(['id' => 4215208, 'estado_id' => 42, 'nome' => 'Romelândia']);
		DB::table('cidades')->insert(['id' => 4215307, 'estado_id' => 42, 'nome' => 'Salete']);
		DB::table('cidades')->insert(['id' => 4215356, 'estado_id' => 42, 'nome' => 'Saltinho']);
		DB::table('cidades')->insert(['id' => 4215406, 'estado_id' => 42, 'nome' => 'Salto Veloso']);
		DB::table('cidades')->insert(['id' => 4215455, 'estado_id' => 42, 'nome' => 'Sangão']);
		DB::table('cidades')->insert(['id' => 4215505, 'estado_id' => 42, 'nome' => 'Santa Cecília']);
		DB::table('cidades')->insert(['id' => 4215554, 'estado_id' => 42, 'nome' => 'Santa Helena']);
		DB::table('cidades')->insert(['id' => 4215604, 'estado_id' => 42, 'nome' => 'Santa Rosa de Lima']);
		DB::table('cidades')->insert(['id' => 4215653, 'estado_id' => 42, 'nome' => 'Santa Rosa do Sul']);
		DB::table('cidades')->insert(['id' => 4215679, 'estado_id' => 42, 'nome' => 'Santa Terezinha']);
		DB::table('cidades')->insert(['id' => 4215687, 'estado_id' => 42, 'nome' => 'Santa Terezinha do Progresso']);
		DB::table('cidades')->insert(['id' => 4215695, 'estado_id' => 42, 'nome' => 'Santiago do Sul']);
		DB::table('cidades')->insert(['id' => 4215703, 'estado_id' => 42, 'nome' => 'Santo Amaro da Imperatriz']);
		DB::table('cidades')->insert(['id' => 4215752, 'estado_id' => 42, 'nome' => 'São Bernardino']);
		DB::table('cidades')->insert(['id' => 4215802, 'estado_id' => 42, 'nome' => 'São Bento do Sul']);
		DB::table('cidades')->insert(['id' => 4215901, 'estado_id' => 42, 'nome' => 'São Bonifácio']);
		DB::table('cidades')->insert(['id' => 4216008, 'estado_id' => 42, 'nome' => 'São Carlos']);
		DB::table('cidades')->insert(['id' => 4216057, 'estado_id' => 42, 'nome' => 'São Cristovão do Sul']);
		DB::table('cidades')->insert(['id' => 4216107, 'estado_id' => 42, 'nome' => 'São Domingos']);
		DB::table('cidades')->insert(['id' => 4216206, 'estado_id' => 42, 'nome' => 'São Francisco do Sul']);
		DB::table('cidades')->insert(['id' => 4216255, 'estado_id' => 42, 'nome' => 'São João do Oeste']);
		DB::table('cidades')->insert(['id' => 4216305, 'estado_id' => 42, 'nome' => 'São João Batista']);
		DB::table('cidades')->insert(['id' => 4216354, 'estado_id' => 42, 'nome' => 'São João do Itaperiú']);
		DB::table('cidades')->insert(['id' => 4216404, 'estado_id' => 42, 'nome' => 'São João do Sul']);
		DB::table('cidades')->insert(['id' => 4216503, 'estado_id' => 42, 'nome' => 'São Joaquim']);
		DB::table('cidades')->insert(['id' => 4216602, 'estado_id' => 42, 'nome' => 'São José']);
		DB::table('cidades')->insert(['id' => 4216701, 'estado_id' => 42, 'nome' => 'São José do Cedro']);
		DB::table('cidades')->insert(['id' => 4216800, 'estado_id' => 42, 'nome' => 'São José do Cerrito']);
		DB::table('cidades')->insert(['id' => 4216909, 'estado_id' => 42, 'nome' => 'São Lourenço do Oeste']);
		DB::table('cidades')->insert(['id' => 4217006, 'estado_id' => 42, 'nome' => 'São Ludgero']);
		DB::table('cidades')->insert(['id' => 4217105, 'estado_id' => 42, 'nome' => 'São Martinho']);
		DB::table('cidades')->insert(['id' => 4217154, 'estado_id' => 42, 'nome' => 'São Miguel da Boa Vista']);
		DB::table('cidades')->insert(['id' => 4217204, 'estado_id' => 42, 'nome' => 'São Miguel do Oeste']);
		DB::table('cidades')->insert(['id' => 4217253, 'estado_id' => 42, 'nome' => 'São Pedro de Alcântara']);
		DB::table('cidades')->insert(['id' => 4217303, 'estado_id' => 42, 'nome' => 'Saudades']);
		DB::table('cidades')->insert(['id' => 4217402, 'estado_id' => 42, 'nome' => 'Schroeder']);
		DB::table('cidades')->insert(['id' => 4217501, 'estado_id' => 42, 'nome' => 'Seara']);
		DB::table('cidades')->insert(['id' => 4217550, 'estado_id' => 42, 'nome' => 'Serra Alta']);
		DB::table('cidades')->insert(['id' => 4217600, 'estado_id' => 42, 'nome' => 'Siderópolis']);
		DB::table('cidades')->insert(['id' => 4217709, 'estado_id' => 42, 'nome' => 'Sombrio']);
		DB::table('cidades')->insert(['id' => 4217758, 'estado_id' => 42, 'nome' => 'Sul Brasil']);
		DB::table('cidades')->insert(['id' => 4217808, 'estado_id' => 42, 'nome' => 'Taió']);
		DB::table('cidades')->insert(['id' => 4217907, 'estado_id' => 42, 'nome' => 'Tangará']);
		DB::table('cidades')->insert(['id' => 4217956, 'estado_id' => 42, 'nome' => 'Tigrinhos']);
		DB::table('cidades')->insert(['id' => 4218004, 'estado_id' => 42, 'nome' => 'Tijucas']);
		DB::table('cidades')->insert(['id' => 4218103, 'estado_id' => 42, 'nome' => 'Timbé do Sul']);
		DB::table('cidades')->insert(['id' => 4218202, 'estado_id' => 42, 'nome' => 'Timbó']);
		DB::table('cidades')->insert(['id' => 4218251, 'estado_id' => 42, 'nome' => 'Timbó Grande']);
		DB::table('cidades')->insert(['id' => 4218301, 'estado_id' => 42, 'nome' => 'Três Barras']);
		DB::table('cidades')->insert(['id' => 4218350, 'estado_id' => 42, 'nome' => 'Treviso']);
		DB::table('cidades')->insert(['id' => 4218400, 'estado_id' => 42, 'nome' => 'Treze de Maio']);
		DB::table('cidades')->insert(['id' => 4218509, 'estado_id' => 42, 'nome' => 'Treze Tílias']);
		DB::table('cidades')->insert(['id' => 4218608, 'estado_id' => 42, 'nome' => 'Trombudo Central']);
		DB::table('cidades')->insert(['id' => 4218707, 'estado_id' => 42, 'nome' => 'Tubarão']);
		DB::table('cidades')->insert(['id' => 4218756, 'estado_id' => 42, 'nome' => 'Tunápolis']);
		DB::table('cidades')->insert(['id' => 4218806, 'estado_id' => 42, 'nome' => 'Turvo']);
		DB::table('cidades')->insert(['id' => 4218855, 'estado_id' => 42, 'nome' => 'União do Oeste']);
		DB::table('cidades')->insert(['id' => 4218905, 'estado_id' => 42, 'nome' => 'Urubici']);
		DB::table('cidades')->insert(['id' => 4218954, 'estado_id' => 42, 'nome' => 'Urupema']);
		DB::table('cidades')->insert(['id' => 4219002, 'estado_id' => 42, 'nome' => 'Urussanga']);
		DB::table('cidades')->insert(['id' => 4219101, 'estado_id' => 42, 'nome' => 'Vargeão']);
		DB::table('cidades')->insert(['id' => 4219150, 'estado_id' => 42, 'nome' => 'Vargem']);
		DB::table('cidades')->insert(['id' => 4219176, 'estado_id' => 42, 'nome' => 'Vargem Bonita']);
		DB::table('cidades')->insert(['id' => 4219200, 'estado_id' => 42, 'nome' => 'Vidal Ramos']);
		DB::table('cidades')->insert(['id' => 4219309, 'estado_id' => 42, 'nome' => 'Videira']);
		DB::table('cidades')->insert(['id' => 4219358, 'estado_id' => 42, 'nome' => 'Vitor Meireles']);
		DB::table('cidades')->insert(['id' => 4219408, 'estado_id' => 42, 'nome' => 'Witmarsum']);
		DB::table('cidades')->insert(['id' => 4219507, 'estado_id' => 42, 'nome' => 'Xanxerê']);
		DB::table('cidades')->insert(['id' => 4219606, 'estado_id' => 42, 'nome' => 'Xavantina']);
		DB::table('cidades')->insert(['id' => 4219705, 'estado_id' => 42, 'nome' => 'Xaxim']);
		DB::table('cidades')->insert(['id' => 4219853, 'estado_id' => 42, 'nome' => 'Zortéa']);
    }
}
