<?php

use Illuminate\Database\Seeder;

class CidadesTableMGSeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades de Minas Gerais
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 3100104, 'estado_id' => 31, 'nome' => 'Abadia dos Dourados']);
		DB::table('cidades')->insert(['id' => 3100203, 'estado_id' => 31, 'nome' => 'Abaeté']);
		DB::table('cidades')->insert(['id' => 3100302, 'estado_id' => 31, 'nome' => 'Abre Campo']);
		DB::table('cidades')->insert(['id' => 3100401, 'estado_id' => 31, 'nome' => 'Acaiaca']);
		DB::table('cidades')->insert(['id' => 3100500, 'estado_id' => 31, 'nome' => 'Açucena']);
		DB::table('cidades')->insert(['id' => 3100609, 'estado_id' => 31, 'nome' => 'Água Boa']);
		DB::table('cidades')->insert(['id' => 3100708, 'estado_id' => 31, 'nome' => 'Água Comprida']);
		DB::table('cidades')->insert(['id' => 3100807, 'estado_id' => 31, 'nome' => 'Aguanil']);
		DB::table('cidades')->insert(['id' => 3100906, 'estado_id' => 31, 'nome' => 'Águas Formosas']);
		DB::table('cidades')->insert(['id' => 3101003, 'estado_id' => 31, 'nome' => 'Águas Vermelhas']);
		DB::table('cidades')->insert(['id' => 3101102, 'estado_id' => 31, 'nome' => 'Aimorés']);
		DB::table('cidades')->insert(['id' => 3101201, 'estado_id' => 31, 'nome' => 'Aiuruoca']);
		DB::table('cidades')->insert(['id' => 3101300, 'estado_id' => 31, 'nome' => 'Alagoa']);
		DB::table('cidades')->insert(['id' => 3101409, 'estado_id' => 31, 'nome' => 'Albertina']);
		DB::table('cidades')->insert(['id' => 3101508, 'estado_id' => 31, 'nome' => 'Além Paraíba']);
		DB::table('cidades')->insert(['id' => 3101607, 'estado_id' => 31, 'nome' => 'Alfenas']);
		DB::table('cidades')->insert(['id' => 3101631, 'estado_id' => 31, 'nome' => 'Alfredo Vasconcelos']);
		DB::table('cidades')->insert(['id' => 3101706, 'estado_id' => 31, 'nome' => 'Almenara']);
		DB::table('cidades')->insert(['id' => 3101805, 'estado_id' => 31, 'nome' => 'Alpercata']);
		DB::table('cidades')->insert(['id' => 3101904, 'estado_id' => 31, 'nome' => 'Alpinópolis']);
		DB::table('cidades')->insert(['id' => 3102001, 'estado_id' => 31, 'nome' => 'Alterosa']);
		DB::table('cidades')->insert(['id' => 3102050, 'estado_id' => 31, 'nome' => 'Alto Caparaó']);
		DB::table('cidades')->insert(['id' => 3102100, 'estado_id' => 31, 'nome' => 'Alto Rio Doce']);
		DB::table('cidades')->insert(['id' => 3102209, 'estado_id' => 31, 'nome' => 'Alvarenga']);
		DB::table('cidades')->insert(['id' => 3102308, 'estado_id' => 31, 'nome' => 'Alvinópolis']);
		DB::table('cidades')->insert(['id' => 3102407, 'estado_id' => 31, 'nome' => 'Alvorada de Minas']);
		DB::table('cidades')->insert(['id' => 3102506, 'estado_id' => 31, 'nome' => 'Amparo do Serra']);
		DB::table('cidades')->insert(['id' => 3102605, 'estado_id' => 31, 'nome' => 'Andradas']);
		DB::table('cidades')->insert(['id' => 3102704, 'estado_id' => 31, 'nome' => 'Cachoeira de Pajeú']);
		DB::table('cidades')->insert(['id' => 3102803, 'estado_id' => 31, 'nome' => 'Andrelândia']);
		DB::table('cidades')->insert(['id' => 3102852, 'estado_id' => 31, 'nome' => 'Angelândia']);
		DB::table('cidades')->insert(['id' => 3102902, 'estado_id' => 31, 'nome' => 'Antônio Carlos']);
		DB::table('cidades')->insert(['id' => 3103009, 'estado_id' => 31, 'nome' => 'Antônio Dias']);
		DB::table('cidades')->insert(['id' => 3103108, 'estado_id' => 31, 'nome' => 'Antônio Prado de Minas']);
		DB::table('cidades')->insert(['id' => 3103207, 'estado_id' => 31, 'nome' => 'Araçaí']);
		DB::table('cidades')->insert(['id' => 3103306, 'estado_id' => 31, 'nome' => 'Aracitaba']);
		DB::table('cidades')->insert(['id' => 3103405, 'estado_id' => 31, 'nome' => 'Araçuaí']);
		DB::table('cidades')->insert(['id' => 3103504, 'estado_id' => 31, 'nome' => 'Araguari']);
		DB::table('cidades')->insert(['id' => 3103603, 'estado_id' => 31, 'nome' => 'Arantina']);
		DB::table('cidades')->insert(['id' => 3103702, 'estado_id' => 31, 'nome' => 'Araponga']);
		DB::table('cidades')->insert(['id' => 3103751, 'estado_id' => 31, 'nome' => 'Araporã']);
		DB::table('cidades')->insert(['id' => 3103801, 'estado_id' => 31, 'nome' => 'Arapuá']);
		DB::table('cidades')->insert(['id' => 3103900, 'estado_id' => 31, 'nome' => 'Araújos']);
		DB::table('cidades')->insert(['id' => 3104007, 'estado_id' => 31, 'nome' => 'Araxá']);
		DB::table('cidades')->insert(['id' => 3104106, 'estado_id' => 31, 'nome' => 'Arceburgo']);
		DB::table('cidades')->insert(['id' => 3104205, 'estado_id' => 31, 'nome' => 'Arcos']);
		DB::table('cidades')->insert(['id' => 3104304, 'estado_id' => 31, 'nome' => 'Areado']);
		DB::table('cidades')->insert(['id' => 3104403, 'estado_id' => 31, 'nome' => 'Argirita']);
		DB::table('cidades')->insert(['id' => 3104452, 'estado_id' => 31, 'nome' => 'Aricanduva']);
		DB::table('cidades')->insert(['id' => 3104502, 'estado_id' => 31, 'nome' => 'Arinos']);
		DB::table('cidades')->insert(['id' => 3104601, 'estado_id' => 31, 'nome' => 'Astolfo Dutra']);
		DB::table('cidades')->insert(['id' => 3104700, 'estado_id' => 31, 'nome' => 'Ataléia']);
		DB::table('cidades')->insert(['id' => 3104809, 'estado_id' => 31, 'nome' => 'Augusto de Lima']);
		DB::table('cidades')->insert(['id' => 3104908, 'estado_id' => 31, 'nome' => 'Baependi']);
		DB::table('cidades')->insert(['id' => 3105004, 'estado_id' => 31, 'nome' => 'Baldim']);
		DB::table('cidades')->insert(['id' => 3105103, 'estado_id' => 31, 'nome' => 'Bambuí']);
		DB::table('cidades')->insert(['id' => 3105202, 'estado_id' => 31, 'nome' => 'Bandeira']);
		DB::table('cidades')->insert(['id' => 3105301, 'estado_id' => 31, 'nome' => 'Bandeira do Sul']);
		DB::table('cidades')->insert(['id' => 3105400, 'estado_id' => 31, 'nome' => 'Barão de Cocais']);
		DB::table('cidades')->insert(['id' => 3105509, 'estado_id' => 31, 'nome' => 'Barão de Monte Alto']);
		DB::table('cidades')->insert(['id' => 3105608, 'estado_id' => 31, 'nome' => 'Barbacena']);
		DB::table('cidades')->insert(['id' => 3105707, 'estado_id' => 31, 'nome' => 'Barra Longa']);
		DB::table('cidades')->insert(['id' => 3105905, 'estado_id' => 31, 'nome' => 'Barroso']);
		DB::table('cidades')->insert(['id' => 3106002, 'estado_id' => 31, 'nome' => 'Bela Vista de Minas']);
		DB::table('cidades')->insert(['id' => 3106101, 'estado_id' => 31, 'nome' => 'Belmiro Braga']);
		DB::table('cidades')->insert(['id' => 3106200, 'estado_id' => 31, 'nome' => 'Belo Horizonte']);
		DB::table('cidades')->insert(['id' => 3106309, 'estado_id' => 31, 'nome' => 'Belo Oriente']);
		DB::table('cidades')->insert(['id' => 3106408, 'estado_id' => 31, 'nome' => 'Belo Vale']);
		DB::table('cidades')->insert(['id' => 3106507, 'estado_id' => 31, 'nome' => 'Berilo']);
		DB::table('cidades')->insert(['id' => 3106606, 'estado_id' => 31, 'nome' => 'Bertópolis']);
		DB::table('cidades')->insert(['id' => 3106655, 'estado_id' => 31, 'nome' => 'Berizal']);
		DB::table('cidades')->insert(['id' => 3106705, 'estado_id' => 31, 'nome' => 'Betim']);
		DB::table('cidades')->insert(['id' => 3106804, 'estado_id' => 31, 'nome' => 'Bias Fortes']);
		DB::table('cidades')->insert(['id' => 3106903, 'estado_id' => 31, 'nome' => 'Bicas']);
		DB::table('cidades')->insert(['id' => 3107000, 'estado_id' => 31, 'nome' => 'Biquinhas']);
		DB::table('cidades')->insert(['id' => 3107109, 'estado_id' => 31, 'nome' => 'Boa Esperança']);
		DB::table('cidades')->insert(['id' => 3107208, 'estado_id' => 31, 'nome' => 'Bocaina de Minas']);
		DB::table('cidades')->insert(['id' => 3107307, 'estado_id' => 31, 'nome' => 'Bocaiúva']);
		DB::table('cidades')->insert(['id' => 3107406, 'estado_id' => 31, 'nome' => 'Bom Despacho']);
		DB::table('cidades')->insert(['id' => 3107505, 'estado_id' => 31, 'nome' => 'Bom Jardim de Minas']);
		DB::table('cidades')->insert(['id' => 3107604, 'estado_id' => 31, 'nome' => 'Bom Jesus da Penha']);
		DB::table('cidades')->insert(['id' => 3107703, 'estado_id' => 31, 'nome' => 'Bom Jesus do Amparo']);
		DB::table('cidades')->insert(['id' => 3107802, 'estado_id' => 31, 'nome' => 'Bom Jesus do Galho']);
		DB::table('cidades')->insert(['id' => 3107901, 'estado_id' => 31, 'nome' => 'Bom Repouso']);
		DB::table('cidades')->insert(['id' => 3108008, 'estado_id' => 31, 'nome' => 'Bom Sucesso']);
		DB::table('cidades')->insert(['id' => 3108107, 'estado_id' => 31, 'nome' => 'Bonfim']);
		DB::table('cidades')->insert(['id' => 3108206, 'estado_id' => 31, 'nome' => 'Bonfinópolis de Minas']);
		DB::table('cidades')->insert(['id' => 3108255, 'estado_id' => 31, 'nome' => 'Bonito de Minas']);
		DB::table('cidades')->insert(['id' => 3108305, 'estado_id' => 31, 'nome' => 'Borda da Mata']);
		DB::table('cidades')->insert(['id' => 3108404, 'estado_id' => 31, 'nome' => 'Botelhos']);
		DB::table('cidades')->insert(['id' => 3108503, 'estado_id' => 31, 'nome' => 'Botumirim']);
		DB::table('cidades')->insert(['id' => 3108552, 'estado_id' => 31, 'nome' => 'Brasilândia de Minas']);
		DB::table('cidades')->insert(['id' => 3108602, 'estado_id' => 31, 'nome' => 'Brasília de Minas']);
		DB::table('cidades')->insert(['id' => 3108701, 'estado_id' => 31, 'nome' => 'Brás Pires']);
		DB::table('cidades')->insert(['id' => 3108800, 'estado_id' => 31, 'nome' => 'Braúnas']);
		DB::table('cidades')->insert(['id' => 3108909, 'estado_id' => 31, 'nome' => 'Brasópolis']);
		DB::table('cidades')->insert(['id' => 3109006, 'estado_id' => 31, 'nome' => 'Brumadinho']);
		DB::table('cidades')->insert(['id' => 3109105, 'estado_id' => 31, 'nome' => 'Bueno Brandão']);
		DB::table('cidades')->insert(['id' => 3109204, 'estado_id' => 31, 'nome' => 'Buenópolis']);
		DB::table('cidades')->insert(['id' => 3109253, 'estado_id' => 31, 'nome' => 'Bugre']);
		DB::table('cidades')->insert(['id' => 3109303, 'estado_id' => 31, 'nome' => 'Buritis']);
		DB::table('cidades')->insert(['id' => 3109402, 'estado_id' => 31, 'nome' => 'Buritizeiro']);
		DB::table('cidades')->insert(['id' => 3109451, 'estado_id' => 31, 'nome' => 'Cabeceira Grande']);
		DB::table('cidades')->insert(['id' => 3109501, 'estado_id' => 31, 'nome' => 'Cabo Verde']);
		DB::table('cidades')->insert(['id' => 3109600, 'estado_id' => 31, 'nome' => 'Cachoeira da Prata']);
		DB::table('cidades')->insert(['id' => 3109709, 'estado_id' => 31, 'nome' => 'Cachoeira de Minas']);
		DB::table('cidades')->insert(['id' => 3109808, 'estado_id' => 31, 'nome' => 'Cachoeira Dourada']);
		DB::table('cidades')->insert(['id' => 3109907, 'estado_id' => 31, 'nome' => 'Caetanópolis']);
		DB::table('cidades')->insert(['id' => 3110004, 'estado_id' => 31, 'nome' => 'Caeté']);
		DB::table('cidades')->insert(['id' => 3110103, 'estado_id' => 31, 'nome' => 'Caiana']);
		DB::table('cidades')->insert(['id' => 3110202, 'estado_id' => 31, 'nome' => 'Cajuri']);
		DB::table('cidades')->insert(['id' => 3110301, 'estado_id' => 31, 'nome' => 'Caldas']);
		DB::table('cidades')->insert(['id' => 3110400, 'estado_id' => 31, 'nome' => 'Camacho']);
		DB::table('cidades')->insert(['id' => 3110509, 'estado_id' => 31, 'nome' => 'Camanducaia']);
		DB::table('cidades')->insert(['id' => 3110608, 'estado_id' => 31, 'nome' => 'Cambuí']);
		DB::table('cidades')->insert(['id' => 3110707, 'estado_id' => 31, 'nome' => 'Cambuquira']);
		DB::table('cidades')->insert(['id' => 3110806, 'estado_id' => 31, 'nome' => 'Campanário']);
		DB::table('cidades')->insert(['id' => 3110905, 'estado_id' => 31, 'nome' => 'Campanha']);
		DB::table('cidades')->insert(['id' => 3111002, 'estado_id' => 31, 'nome' => 'Campestre']);
		DB::table('cidades')->insert(['id' => 3111101, 'estado_id' => 31, 'nome' => 'Campina Verde']);
		DB::table('cidades')->insert(['id' => 3111150, 'estado_id' => 31, 'nome' => 'Campo Azul']);
		DB::table('cidades')->insert(['id' => 3111200, 'estado_id' => 31, 'nome' => 'Campo Belo']);
		DB::table('cidades')->insert(['id' => 3111309, 'estado_id' => 31, 'nome' => 'Campo do Meio']);
		DB::table('cidades')->insert(['id' => 3111408, 'estado_id' => 31, 'nome' => 'Campo Florido']);
		DB::table('cidades')->insert(['id' => 3111507, 'estado_id' => 31, 'nome' => 'Campos Altos']);
		DB::table('cidades')->insert(['id' => 3111606, 'estado_id' => 31, 'nome' => 'Campos Gerais']);
		DB::table('cidades')->insert(['id' => 3111705, 'estado_id' => 31, 'nome' => 'Canaã']);
		DB::table('cidades')->insert(['id' => 3111804, 'estado_id' => 31, 'nome' => 'Canápolis']);
		DB::table('cidades')->insert(['id' => 3111903, 'estado_id' => 31, 'nome' => 'Cana Verde']);
		DB::table('cidades')->insert(['id' => 3112000, 'estado_id' => 31, 'nome' => 'Candeias']);
		DB::table('cidades')->insert(['id' => 3112059, 'estado_id' => 31, 'nome' => 'Cantagalo']);
		DB::table('cidades')->insert(['id' => 3112109, 'estado_id' => 31, 'nome' => 'Caparaó']);
		DB::table('cidades')->insert(['id' => 3112208, 'estado_id' => 31, 'nome' => 'Capela Nova']);
		DB::table('cidades')->insert(['id' => 3112307, 'estado_id' => 31, 'nome' => 'Capelinha']);
		DB::table('cidades')->insert(['id' => 3112406, 'estado_id' => 31, 'nome' => 'Capetinga']);
		DB::table('cidades')->insert(['id' => 3112505, 'estado_id' => 31, 'nome' => 'Capim Branco']);
		DB::table('cidades')->insert(['id' => 3112604, 'estado_id' => 31, 'nome' => 'Capinópolis']);
		DB::table('cidades')->insert(['id' => 3112653, 'estado_id' => 31, 'nome' => 'Capitão Andrade']);
		DB::table('cidades')->insert(['id' => 3112703, 'estado_id' => 31, 'nome' => 'Capitão Enéas']);
		DB::table('cidades')->insert(['id' => 3112802, 'estado_id' => 31, 'nome' => 'Capitólio']);
		DB::table('cidades')->insert(['id' => 3112901, 'estado_id' => 31, 'nome' => 'Caputira']);
		DB::table('cidades')->insert(['id' => 3113008, 'estado_id' => 31, 'nome' => 'Caraí']);
		DB::table('cidades')->insert(['id' => 3113107, 'estado_id' => 31, 'nome' => 'Caranaíba']);
		DB::table('cidades')->insert(['id' => 3113206, 'estado_id' => 31, 'nome' => 'Carandaí']);
		DB::table('cidades')->insert(['id' => 3113305, 'estado_id' => 31, 'nome' => 'Carangola']);
		DB::table('cidades')->insert(['id' => 3113404, 'estado_id' => 31, 'nome' => 'Caratinga']);
		DB::table('cidades')->insert(['id' => 3113503, 'estado_id' => 31, 'nome' => 'Carbonita']);
		DB::table('cidades')->insert(['id' => 3113602, 'estado_id' => 31, 'nome' => 'Careaçu']);
		DB::table('cidades')->insert(['id' => 3113701, 'estado_id' => 31, 'nome' => 'Carlos Chagas']);
		DB::table('cidades')->insert(['id' => 3113800, 'estado_id' => 31, 'nome' => 'Carmésia']);
		DB::table('cidades')->insert(['id' => 3113909, 'estado_id' => 31, 'nome' => 'Carmo da Cachoeira']);
		DB::table('cidades')->insert(['id' => 3114006, 'estado_id' => 31, 'nome' => 'Carmo da Mata']);
		DB::table('cidades')->insert(['id' => 3114105, 'estado_id' => 31, 'nome' => 'Carmo de Minas']);
		DB::table('cidades')->insert(['id' => 3114204, 'estado_id' => 31, 'nome' => 'Carmo do Cajuru']);
		DB::table('cidades')->insert(['id' => 3114303, 'estado_id' => 31, 'nome' => 'Carmo do Paranaíba']);
		DB::table('cidades')->insert(['id' => 3114402, 'estado_id' => 31, 'nome' => 'Carmo do Rio Claro']);
		DB::table('cidades')->insert(['id' => 3114501, 'estado_id' => 31, 'nome' => 'Carmópolis de Minas']);
		DB::table('cidades')->insert(['id' => 3114550, 'estado_id' => 31, 'nome' => 'Carneirinho']);
		DB::table('cidades')->insert(['id' => 3114600, 'estado_id' => 31, 'nome' => 'Carrancas']);
		DB::table('cidades')->insert(['id' => 3114709, 'estado_id' => 31, 'nome' => 'Carvalhópolis']);
		DB::table('cidades')->insert(['id' => 3114808, 'estado_id' => 31, 'nome' => 'Carvalhos']);
		DB::table('cidades')->insert(['id' => 3114907, 'estado_id' => 31, 'nome' => 'Casa Grande']);
		DB::table('cidades')->insert(['id' => 3115003, 'estado_id' => 31, 'nome' => 'Cascalho Rico']);
		DB::table('cidades')->insert(['id' => 3115102, 'estado_id' => 31, 'nome' => 'Cássia']);
		DB::table('cidades')->insert(['id' => 3115201, 'estado_id' => 31, 'nome' => 'Conceição da Barra de Minas']);
		DB::table('cidades')->insert(['id' => 3115300, 'estado_id' => 31, 'nome' => 'Cataguases']);
		DB::table('cidades')->insert(['id' => 3115359, 'estado_id' => 31, 'nome' => 'Catas Altas']);
		DB::table('cidades')->insert(['id' => 3115409, 'estado_id' => 31, 'nome' => 'Catas Altas da Noruega']);
		DB::table('cidades')->insert(['id' => 3115458, 'estado_id' => 31, 'nome' => 'Catuji']);
		DB::table('cidades')->insert(['id' => 3115474, 'estado_id' => 31, 'nome' => 'Catuti']);
		DB::table('cidades')->insert(['id' => 3115508, 'estado_id' => 31, 'nome' => 'Caxambu']);
		DB::table('cidades')->insert(['id' => 3115607, 'estado_id' => 31, 'nome' => 'Cedro do Abaeté']);
		DB::table('cidades')->insert(['id' => 3115706, 'estado_id' => 31, 'nome' => 'Central de Minas']);
		DB::table('cidades')->insert(['id' => 3115805, 'estado_id' => 31, 'nome' => 'Centralina']);
		DB::table('cidades')->insert(['id' => 3115904, 'estado_id' => 31, 'nome' => 'Chácara']);
		DB::table('cidades')->insert(['id' => 3116001, 'estado_id' => 31, 'nome' => 'Chalé']);
		DB::table('cidades')->insert(['id' => 3116100, 'estado_id' => 31, 'nome' => 'Chapada do Norte']);
		DB::table('cidades')->insert(['id' => 3116159, 'estado_id' => 31, 'nome' => 'Chapada Gaúcha']);
		DB::table('cidades')->insert(['id' => 3116209, 'estado_id' => 31, 'nome' => 'Chiador']);
		DB::table('cidades')->insert(['id' => 3116308, 'estado_id' => 31, 'nome' => 'Cipotânea']);
		DB::table('cidades')->insert(['id' => 3116407, 'estado_id' => 31, 'nome' => 'Claraval']);
		DB::table('cidades')->insert(['id' => 3116506, 'estado_id' => 31, 'nome' => 'Claro dos Poções']);
		DB::table('cidades')->insert(['id' => 3116605, 'estado_id' => 31, 'nome' => 'Cláudio']);
		DB::table('cidades')->insert(['id' => 3116704, 'estado_id' => 31, 'nome' => 'Coimbra']);
		DB::table('cidades')->insert(['id' => 3116803, 'estado_id' => 31, 'nome' => 'Coluna']);
		DB::table('cidades')->insert(['id' => 3116902, 'estado_id' => 31, 'nome' => 'Comendador Gomes']);
		DB::table('cidades')->insert(['id' => 3117009, 'estado_id' => 31, 'nome' => 'Comercinho']);
		DB::table('cidades')->insert(['id' => 3117108, 'estado_id' => 31, 'nome' => 'Conceição da Aparecida']);
		DB::table('cidades')->insert(['id' => 3117207, 'estado_id' => 31, 'nome' => 'Conceição das Pedras']);
		DB::table('cidades')->insert(['id' => 3117306, 'estado_id' => 31, 'nome' => 'Conceição das Alagoas']);
		DB::table('cidades')->insert(['id' => 3117405, 'estado_id' => 31, 'nome' => 'Conceição de Ipanema']);
		DB::table('cidades')->insert(['id' => 3117504, 'estado_id' => 31, 'nome' => 'Conceição do Mato Dentro']);
		DB::table('cidades')->insert(['id' => 3117603, 'estado_id' => 31, 'nome' => 'Conceição do Pará']);
		DB::table('cidades')->insert(['id' => 3117702, 'estado_id' => 31, 'nome' => 'Conceição do Rio Verde']);
		DB::table('cidades')->insert(['id' => 3117801, 'estado_id' => 31, 'nome' => 'Conceição dos Ouros']);
		DB::table('cidades')->insert(['id' => 3117836, 'estado_id' => 31, 'nome' => 'Cônego Marinho']);
		DB::table('cidades')->insert(['id' => 3117876, 'estado_id' => 31, 'nome' => 'Confins']);
		DB::table('cidades')->insert(['id' => 3117900, 'estado_id' => 31, 'nome' => 'Congonhal']);
		DB::table('cidades')->insert(['id' => 3118007, 'estado_id' => 31, 'nome' => 'Congonhas']);
		DB::table('cidades')->insert(['id' => 3118106, 'estado_id' => 31, 'nome' => 'Congonhas do Norte']);
		DB::table('cidades')->insert(['id' => 3118205, 'estado_id' => 31, 'nome' => 'Conquista']);
		DB::table('cidades')->insert(['id' => 3118304, 'estado_id' => 31, 'nome' => 'Conselheiro Lafaiete']);
		DB::table('cidades')->insert(['id' => 3118403, 'estado_id' => 31, 'nome' => 'Conselheiro Pena']);
		DB::table('cidades')->insert(['id' => 3118502, 'estado_id' => 31, 'nome' => 'Consolação']);
		DB::table('cidades')->insert(['id' => 3118601, 'estado_id' => 31, 'nome' => 'Contagem']);
		DB::table('cidades')->insert(['id' => 3118700, 'estado_id' => 31, 'nome' => 'Coqueiral']);
		DB::table('cidades')->insert(['id' => 3118809, 'estado_id' => 31, 'nome' => 'Coração de Jesus']);
		DB::table('cidades')->insert(['id' => 3118908, 'estado_id' => 31, 'nome' => 'Cordisburgo']);
		DB::table('cidades')->insert(['id' => 3119005, 'estado_id' => 31, 'nome' => 'Cordislândia']);
		DB::table('cidades')->insert(['id' => 3119104, 'estado_id' => 31, 'nome' => 'Corinto']);
		DB::table('cidades')->insert(['id' => 3119203, 'estado_id' => 31, 'nome' => 'Coroaci']);
		DB::table('cidades')->insert(['id' => 3119302, 'estado_id' => 31, 'nome' => 'Coromandel']);
		DB::table('cidades')->insert(['id' => 3119401, 'estado_id' => 31, 'nome' => 'Coronel Fabriciano']);
		DB::table('cidades')->insert(['id' => 3119500, 'estado_id' => 31, 'nome' => 'Coronel Murta']);
		DB::table('cidades')->insert(['id' => 3119609, 'estado_id' => 31, 'nome' => 'Coronel Pacheco']);
		DB::table('cidades')->insert(['id' => 3119708, 'estado_id' => 31, 'nome' => 'Coronel Xavier Chaves']);
		DB::table('cidades')->insert(['id' => 3119807, 'estado_id' => 31, 'nome' => 'Córrego Danta']);
		DB::table('cidades')->insert(['id' => 3119906, 'estado_id' => 31, 'nome' => 'Córrego do Bom Jesus']);
		DB::table('cidades')->insert(['id' => 3119955, 'estado_id' => 31, 'nome' => 'Córrego Fundo']);
		DB::table('cidades')->insert(['id' => 3120003, 'estado_id' => 31, 'nome' => 'Córrego Novo']);
		DB::table('cidades')->insert(['id' => 3120102, 'estado_id' => 31, 'nome' => 'Couto de Magalhães de Minas']);
		DB::table('cidades')->insert(['id' => 3120151, 'estado_id' => 31, 'nome' => 'Crisólita']);
		DB::table('cidades')->insert(['id' => 3120201, 'estado_id' => 31, 'nome' => 'Cristais']);
		DB::table('cidades')->insert(['id' => 3120300, 'estado_id' => 31, 'nome' => 'Cristália']);
		DB::table('cidades')->insert(['id' => 3120409, 'estado_id' => 31, 'nome' => 'Cristiano Otoni']);
		DB::table('cidades')->insert(['id' => 3120508, 'estado_id' => 31, 'nome' => 'Cristina']);
		DB::table('cidades')->insert(['id' => 3120607, 'estado_id' => 31, 'nome' => 'Crucilândia']);
		DB::table('cidades')->insert(['id' => 3120706, 'estado_id' => 31, 'nome' => 'Cruzeiro da Fortaleza']);
		DB::table('cidades')->insert(['id' => 3120805, 'estado_id' => 31, 'nome' => 'Cruzília']);
		DB::table('cidades')->insert(['id' => 3120839, 'estado_id' => 31, 'nome' => 'Cuparaque']);
		DB::table('cidades')->insert(['id' => 3120870, 'estado_id' => 31, 'nome' => 'Curral de Dentro']);
		DB::table('cidades')->insert(['id' => 3120904, 'estado_id' => 31, 'nome' => 'Curvelo']);
		DB::table('cidades')->insert(['id' => 3121001, 'estado_id' => 31, 'nome' => 'Datas']);
		DB::table('cidades')->insert(['id' => 3121100, 'estado_id' => 31, 'nome' => 'Delfim Moreira']);
		DB::table('cidades')->insert(['id' => 3121209, 'estado_id' => 31, 'nome' => 'Delfinópolis']);
		DB::table('cidades')->insert(['id' => 3121258, 'estado_id' => 31, 'nome' => 'Delta']);
		DB::table('cidades')->insert(['id' => 3121308, 'estado_id' => 31, 'nome' => 'Descoberto']);
		DB::table('cidades')->insert(['id' => 3121407, 'estado_id' => 31, 'nome' => 'Desterro de Entre Rios']);
		DB::table('cidades')->insert(['id' => 3121506, 'estado_id' => 31, 'nome' => 'Desterro do Melo']);
		DB::table('cidades')->insert(['id' => 3121605, 'estado_id' => 31, 'nome' => 'Diamantina']);
		DB::table('cidades')->insert(['id' => 3121704, 'estado_id' => 31, 'nome' => 'Diogo de Vasconcelos']);
		DB::table('cidades')->insert(['id' => 3121803, 'estado_id' => 31, 'nome' => 'Dionísio']);
		DB::table('cidades')->insert(['id' => 3121902, 'estado_id' => 31, 'nome' => 'Divinésia']);
		DB::table('cidades')->insert(['id' => 3122009, 'estado_id' => 31, 'nome' => 'Divino']);
		DB::table('cidades')->insert(['id' => 3122108, 'estado_id' => 31, 'nome' => 'Divino das Laranjeiras']);
		DB::table('cidades')->insert(['id' => 3122207, 'estado_id' => 31, 'nome' => 'Divinolândia de Minas']);
		DB::table('cidades')->insert(['id' => 3122306, 'estado_id' => 31, 'nome' => 'Divinópolis']);
		DB::table('cidades')->insert(['id' => 3122355, 'estado_id' => 31, 'nome' => 'Divisa Alegre']);
		DB::table('cidades')->insert(['id' => 3122405, 'estado_id' => 31, 'nome' => 'Divisa Nova']);
		DB::table('cidades')->insert(['id' => 3122454, 'estado_id' => 31, 'nome' => 'Divisópolis']);
		DB::table('cidades')->insert(['id' => 3122470, 'estado_id' => 31, 'nome' => 'Dom Bosco']);
		DB::table('cidades')->insert(['id' => 3122504, 'estado_id' => 31, 'nome' => 'Dom Cavati']);
		DB::table('cidades')->insert(['id' => 3122603, 'estado_id' => 31, 'nome' => 'Dom Joaquim']);
		DB::table('cidades')->insert(['id' => 3122702, 'estado_id' => 31, 'nome' => 'Dom Silvério']);
		DB::table('cidades')->insert(['id' => 3122801, 'estado_id' => 31, 'nome' => 'Dom Viçoso']);
		DB::table('cidades')->insert(['id' => 3122900, 'estado_id' => 31, 'nome' => 'Dona Eusébia']);
		DB::table('cidades')->insert(['id' => 3123007, 'estado_id' => 31, 'nome' => 'Dores de Campos']);
		DB::table('cidades')->insert(['id' => 3123106, 'estado_id' => 31, 'nome' => 'Dores de Guanhães']);
		DB::table('cidades')->insert(['id' => 3123205, 'estado_id' => 31, 'nome' => 'Dores do Indaiá']);
		DB::table('cidades')->insert(['id' => 3123304, 'estado_id' => 31, 'nome' => 'Dores do Turvo']);
		DB::table('cidades')->insert(['id' => 3123403, 'estado_id' => 31, 'nome' => 'Doresópolis']);
		DB::table('cidades')->insert(['id' => 3123502, 'estado_id' => 31, 'nome' => 'Douradoquara']);
		DB::table('cidades')->insert(['id' => 3123528, 'estado_id' => 31, 'nome' => 'Durandé']);
		DB::table('cidades')->insert(['id' => 3123601, 'estado_id' => 31, 'nome' => 'Elói Mendes']);
		DB::table('cidades')->insert(['id' => 3123700, 'estado_id' => 31, 'nome' => 'Engenheiro Caldas']);
		DB::table('cidades')->insert(['id' => 3123809, 'estado_id' => 31, 'nome' => 'Engenheiro Navarro']);
		DB::table('cidades')->insert(['id' => 3123858, 'estado_id' => 31, 'nome' => 'Entre Folhas']);
		DB::table('cidades')->insert(['id' => 3123908, 'estado_id' => 31, 'nome' => 'Entre Rios de Minas']);
		DB::table('cidades')->insert(['id' => 3124005, 'estado_id' => 31, 'nome' => 'Ervália']);
		DB::table('cidades')->insert(['id' => 3124104, 'estado_id' => 31, 'nome' => 'Esmeraldas']);
		DB::table('cidades')->insert(['id' => 3124203, 'estado_id' => 31, 'nome' => 'Espera Feliz']);
		DB::table('cidades')->insert(['id' => 3124302, 'estado_id' => 31, 'nome' => 'Espinosa']);
		DB::table('cidades')->insert(['id' => 3124401, 'estado_id' => 31, 'nome' => 'Espírito Santo do Dourado']);
		DB::table('cidades')->insert(['id' => 3124500, 'estado_id' => 31, 'nome' => 'Estiva']);
		DB::table('cidades')->insert(['id' => 3124609, 'estado_id' => 31, 'nome' => 'Estrela Dalva']);
		DB::table('cidades')->insert(['id' => 3124708, 'estado_id' => 31, 'nome' => 'Estrela do Indaiá']);
		DB::table('cidades')->insert(['id' => 3124807, 'estado_id' => 31, 'nome' => 'Estrela do Sul']);
		DB::table('cidades')->insert(['id' => 3124906, 'estado_id' => 31, 'nome' => 'Eugenópolis']);
		DB::table('cidades')->insert(['id' => 3125002, 'estado_id' => 31, 'nome' => 'Ewbank da Câmara']);
		DB::table('cidades')->insert(['id' => 3125101, 'estado_id' => 31, 'nome' => 'Extrema']);
		DB::table('cidades')->insert(['id' => 3125200, 'estado_id' => 31, 'nome' => 'Fama']);
		DB::table('cidades')->insert(['id' => 3125309, 'estado_id' => 31, 'nome' => 'Faria Lemos']);
		DB::table('cidades')->insert(['id' => 3125408, 'estado_id' => 31, 'nome' => 'Felício dos Santos']);
		DB::table('cidades')->insert(['id' => 3125507, 'estado_id' => 31, 'nome' => 'São Gonçalo do Rio Preto']);
		DB::table('cidades')->insert(['id' => 3125606, 'estado_id' => 31, 'nome' => 'Felisburgo']);
		DB::table('cidades')->insert(['id' => 3125705, 'estado_id' => 31, 'nome' => 'Felixlândia']);
		DB::table('cidades')->insert(['id' => 3125804, 'estado_id' => 31, 'nome' => 'Fernandes Tourinho']);
		DB::table('cidades')->insert(['id' => 3125903, 'estado_id' => 31, 'nome' => 'Ferros']);
		DB::table('cidades')->insert(['id' => 3125952, 'estado_id' => 31, 'nome' => 'Fervedouro']);
		DB::table('cidades')->insert(['id' => 3126000, 'estado_id' => 31, 'nome' => 'Florestal']);
		DB::table('cidades')->insert(['id' => 3126109, 'estado_id' => 31, 'nome' => 'Formiga']);
		DB::table('cidades')->insert(['id' => 3126208, 'estado_id' => 31, 'nome' => 'Formoso']);
		DB::table('cidades')->insert(['id' => 3126307, 'estado_id' => 31, 'nome' => 'Fortaleza de Minas']);
		DB::table('cidades')->insert(['id' => 3126406, 'estado_id' => 31, 'nome' => 'Fortuna de Minas']);
		DB::table('cidades')->insert(['id' => 3126505, 'estado_id' => 31, 'nome' => 'Francisco Badaró']);
		DB::table('cidades')->insert(['id' => 3126604, 'estado_id' => 31, 'nome' => 'Francisco Dumont']);
		DB::table('cidades')->insert(['id' => 3126703, 'estado_id' => 31, 'nome' => 'Francisco Sá']);
		DB::table('cidades')->insert(['id' => 3126752, 'estado_id' => 31, 'nome' => 'Franciscópolis']);
		DB::table('cidades')->insert(['id' => 3126802, 'estado_id' => 31, 'nome' => 'Frei Gaspar']);
		DB::table('cidades')->insert(['id' => 3126901, 'estado_id' => 31, 'nome' => 'Frei Inocêncio']);
		DB::table('cidades')->insert(['id' => 3126950, 'estado_id' => 31, 'nome' => 'Frei Lagonegro']);
		DB::table('cidades')->insert(['id' => 3127008, 'estado_id' => 31, 'nome' => 'Fronteira']);
		DB::table('cidades')->insert(['id' => 3127057, 'estado_id' => 31, 'nome' => 'Fronteira dos Vales']);
		DB::table('cidades')->insert(['id' => 3127073, 'estado_id' => 31, 'nome' => 'Fruta de Leite']);
		DB::table('cidades')->insert(['id' => 3127107, 'estado_id' => 31, 'nome' => 'Frutal']);
		DB::table('cidades')->insert(['id' => 3127206, 'estado_id' => 31, 'nome' => 'Funilândia']);
		DB::table('cidades')->insert(['id' => 3127305, 'estado_id' => 31, 'nome' => 'Galiléia']);
		DB::table('cidades')->insert(['id' => 3127339, 'estado_id' => 31, 'nome' => 'Gameleiras']);
		DB::table('cidades')->insert(['id' => 3127354, 'estado_id' => 31, 'nome' => 'Glaucilândia']);
		DB::table('cidades')->insert(['id' => 3127370, 'estado_id' => 31, 'nome' => 'Goiabeira']);
		DB::table('cidades')->insert(['id' => 3127388, 'estado_id' => 31, 'nome' => 'Goianá']);
		DB::table('cidades')->insert(['id' => 3127404, 'estado_id' => 31, 'nome' => 'Gonçalves']);
		DB::table('cidades')->insert(['id' => 3127503, 'estado_id' => 31, 'nome' => 'Gonzaga']);
		DB::table('cidades')->insert(['id' => 3127602, 'estado_id' => 31, 'nome' => 'Gouveia']);
		DB::table('cidades')->insert(['id' => 3127701, 'estado_id' => 31, 'nome' => 'Governador Valadares']);
		DB::table('cidades')->insert(['id' => 3127800, 'estado_id' => 31, 'nome' => 'Grão Mogol']);
		DB::table('cidades')->insert(['id' => 3127909, 'estado_id' => 31, 'nome' => 'Grupiara']);
		DB::table('cidades')->insert(['id' => 3128006, 'estado_id' => 31, 'nome' => 'Guanhães']);
		DB::table('cidades')->insert(['id' => 3128105, 'estado_id' => 31, 'nome' => 'Guapé']);
		DB::table('cidades')->insert(['id' => 3128204, 'estado_id' => 31, 'nome' => 'Guaraciaba']);
		DB::table('cidades')->insert(['id' => 3128253, 'estado_id' => 31, 'nome' => 'Guaraciama']);
		DB::table('cidades')->insert(['id' => 3128303, 'estado_id' => 31, 'nome' => 'Guaranésia']);
		DB::table('cidades')->insert(['id' => 3128402, 'estado_id' => 31, 'nome' => 'Guarani']);
		DB::table('cidades')->insert(['id' => 3128501, 'estado_id' => 31, 'nome' => 'Guarará']);
		DB::table('cidades')->insert(['id' => 3128600, 'estado_id' => 31, 'nome' => 'Guarda-Mor']);
		DB::table('cidades')->insert(['id' => 3128709, 'estado_id' => 31, 'nome' => 'Guaxupé']);
		DB::table('cidades')->insert(['id' => 3128808, 'estado_id' => 31, 'nome' => 'Guidoval']);
		DB::table('cidades')->insert(['id' => 3128907, 'estado_id' => 31, 'nome' => 'Guimarânia']);
		DB::table('cidades')->insert(['id' => 3129004, 'estado_id' => 31, 'nome' => 'Guiricema']);
		DB::table('cidades')->insert(['id' => 3129103, 'estado_id' => 31, 'nome' => 'Gurinhatã']);
		DB::table('cidades')->insert(['id' => 3129202, 'estado_id' => 31, 'nome' => 'Heliodora']);
		DB::table('cidades')->insert(['id' => 3129301, 'estado_id' => 31, 'nome' => 'Iapu']);
		DB::table('cidades')->insert(['id' => 3129400, 'estado_id' => 31, 'nome' => 'Ibertioga']);
		DB::table('cidades')->insert(['id' => 3129509, 'estado_id' => 31, 'nome' => 'Ibiá']);
		DB::table('cidades')->insert(['id' => 3129608, 'estado_id' => 31, 'nome' => 'Ibiaí']);
		DB::table('cidades')->insert(['id' => 3129657, 'estado_id' => 31, 'nome' => 'Ibiracatu']);
		DB::table('cidades')->insert(['id' => 3129707, 'estado_id' => 31, 'nome' => 'Ibiraci']);
		DB::table('cidades')->insert(['id' => 3129806, 'estado_id' => 31, 'nome' => 'Ibirité']);
		DB::table('cidades')->insert(['id' => 3129905, 'estado_id' => 31, 'nome' => 'Ibitiúra de Minas']);
		DB::table('cidades')->insert(['id' => 3130002, 'estado_id' => 31, 'nome' => 'Ibituruna']);
		DB::table('cidades')->insert(['id' => 3130051, 'estado_id' => 31, 'nome' => 'Icaraí de Minas']);
		DB::table('cidades')->insert(['id' => 3130101, 'estado_id' => 31, 'nome' => 'Igarapé']);
		DB::table('cidades')->insert(['id' => 3130200, 'estado_id' => 31, 'nome' => 'Igaratinga']);
		DB::table('cidades')->insert(['id' => 3130309, 'estado_id' => 31, 'nome' => 'Iguatama']);
		DB::table('cidades')->insert(['id' => 3130408, 'estado_id' => 31, 'nome' => 'Ijaci']);
		DB::table('cidades')->insert(['id' => 3130507, 'estado_id' => 31, 'nome' => 'Ilicínea']);
		DB::table('cidades')->insert(['id' => 3130556, 'estado_id' => 31, 'nome' => 'Imbé de Minas']);
		DB::table('cidades')->insert(['id' => 3130606, 'estado_id' => 31, 'nome' => 'Inconfidentes']);
		DB::table('cidades')->insert(['id' => 3130655, 'estado_id' => 31, 'nome' => 'Indaiabira']);
		DB::table('cidades')->insert(['id' => 3130705, 'estado_id' => 31, 'nome' => 'Indianópolis']);
		DB::table('cidades')->insert(['id' => 3130804, 'estado_id' => 31, 'nome' => 'Ingaí']);
		DB::table('cidades')->insert(['id' => 3130903, 'estado_id' => 31, 'nome' => 'Inhapim']);
		DB::table('cidades')->insert(['id' => 3131000, 'estado_id' => 31, 'nome' => 'Inhaúma']);
		DB::table('cidades')->insert(['id' => 3131109, 'estado_id' => 31, 'nome' => 'Inimutaba']);
		DB::table('cidades')->insert(['id' => 3131158, 'estado_id' => 31, 'nome' => 'Ipaba']);
		DB::table('cidades')->insert(['id' => 3131208, 'estado_id' => 31, 'nome' => 'Ipanema']);
		DB::table('cidades')->insert(['id' => 3131307, 'estado_id' => 31, 'nome' => 'Ipatinga']);
		DB::table('cidades')->insert(['id' => 3131406, 'estado_id' => 31, 'nome' => 'Ipiaçu']);
		DB::table('cidades')->insert(['id' => 3131505, 'estado_id' => 31, 'nome' => 'Ipuiúna']);
		DB::table('cidades')->insert(['id' => 3131604, 'estado_id' => 31, 'nome' => 'Iraí de Minas']);
		DB::table('cidades')->insert(['id' => 3131703, 'estado_id' => 31, 'nome' => 'Itabira']);
		DB::table('cidades')->insert(['id' => 3131802, 'estado_id' => 31, 'nome' => 'Itabirinha']);
		DB::table('cidades')->insert(['id' => 3131901, 'estado_id' => 31, 'nome' => 'Itabirito']);
		DB::table('cidades')->insert(['id' => 3132008, 'estado_id' => 31, 'nome' => 'Itacambira']);
		DB::table('cidades')->insert(['id' => 3132107, 'estado_id' => 31, 'nome' => 'Itacarambi']);
		DB::table('cidades')->insert(['id' => 3132206, 'estado_id' => 31, 'nome' => 'Itaguara']);
		DB::table('cidades')->insert(['id' => 3132305, 'estado_id' => 31, 'nome' => 'Itaipé']);
		DB::table('cidades')->insert(['id' => 3132404, 'estado_id' => 31, 'nome' => 'Itajubá']);
		DB::table('cidades')->insert(['id' => 3132503, 'estado_id' => 31, 'nome' => 'Itamarandiba']);
		DB::table('cidades')->insert(['id' => 3132602, 'estado_id' => 31, 'nome' => 'Itamarati de Minas']);
		DB::table('cidades')->insert(['id' => 3132701, 'estado_id' => 31, 'nome' => 'Itambacuri']);
		DB::table('cidades')->insert(['id' => 3132800, 'estado_id' => 31, 'nome' => 'Itambé do Mato Dentro']);
		DB::table('cidades')->insert(['id' => 3132909, 'estado_id' => 31, 'nome' => 'Itamogi']);
		DB::table('cidades')->insert(['id' => 3133006, 'estado_id' => 31, 'nome' => 'Itamonte']);
		DB::table('cidades')->insert(['id' => 3133105, 'estado_id' => 31, 'nome' => 'Itanhandu']);
		DB::table('cidades')->insert(['id' => 3133204, 'estado_id' => 31, 'nome' => 'Itanhomi']);
		DB::table('cidades')->insert(['id' => 3133303, 'estado_id' => 31, 'nome' => 'Itaobim']);
		DB::table('cidades')->insert(['id' => 3133402, 'estado_id' => 31, 'nome' => 'Itapagipe']);
		DB::table('cidades')->insert(['id' => 3133501, 'estado_id' => 31, 'nome' => 'Itapecerica']);
		DB::table('cidades')->insert(['id' => 3133600, 'estado_id' => 31, 'nome' => 'Itapeva']);
		DB::table('cidades')->insert(['id' => 3133709, 'estado_id' => 31, 'nome' => 'Itatiaiuçu']);
		DB::table('cidades')->insert(['id' => 3133758, 'estado_id' => 31, 'nome' => 'Itaú de Minas']);
		DB::table('cidades')->insert(['id' => 3133808, 'estado_id' => 31, 'nome' => 'Itaúna']);
		DB::table('cidades')->insert(['id' => 3133907, 'estado_id' => 31, 'nome' => 'Itaverava']);
		DB::table('cidades')->insert(['id' => 3134004, 'estado_id' => 31, 'nome' => 'Itinga']);
		DB::table('cidades')->insert(['id' => 3134103, 'estado_id' => 31, 'nome' => 'Itueta']);
		DB::table('cidades')->insert(['id' => 3134202, 'estado_id' => 31, 'nome' => 'Ituiutaba']);
		DB::table('cidades')->insert(['id' => 3134301, 'estado_id' => 31, 'nome' => 'Itumirim']);
		DB::table('cidades')->insert(['id' => 3134400, 'estado_id' => 31, 'nome' => 'Iturama']);
		DB::table('cidades')->insert(['id' => 3134509, 'estado_id' => 31, 'nome' => 'Itutinga']);
		DB::table('cidades')->insert(['id' => 3134608, 'estado_id' => 31, 'nome' => 'Jaboticatubas']);
		DB::table('cidades')->insert(['id' => 3134707, 'estado_id' => 31, 'nome' => 'Jacinto']);
		DB::table('cidades')->insert(['id' => 3134806, 'estado_id' => 31, 'nome' => 'Jacuí']);
		DB::table('cidades')->insert(['id' => 3134905, 'estado_id' => 31, 'nome' => 'Jacutinga']);
		DB::table('cidades')->insert(['id' => 3135001, 'estado_id' => 31, 'nome' => 'Jaguaraçu']);
		DB::table('cidades')->insert(['id' => 3135050, 'estado_id' => 31, 'nome' => 'Jaíba']);
		DB::table('cidades')->insert(['id' => 3135076, 'estado_id' => 31, 'nome' => 'Jampruca']);
		DB::table('cidades')->insert(['id' => 3135100, 'estado_id' => 31, 'nome' => 'Janaúba']);
		DB::table('cidades')->insert(['id' => 3135209, 'estado_id' => 31, 'nome' => 'Januária']);
		DB::table('cidades')->insert(['id' => 3135308, 'estado_id' => 31, 'nome' => 'Japaraíba']);
		DB::table('cidades')->insert(['id' => 3135357, 'estado_id' => 31, 'nome' => 'Japonvar']);
		DB::table('cidades')->insert(['id' => 3135407, 'estado_id' => 31, 'nome' => 'Jeceaba']);
		DB::table('cidades')->insert(['id' => 3135456, 'estado_id' => 31, 'nome' => 'Jenipapo de Minas']);
		DB::table('cidades')->insert(['id' => 3135506, 'estado_id' => 31, 'nome' => 'Jequeri']);
		DB::table('cidades')->insert(['id' => 3135605, 'estado_id' => 31, 'nome' => 'Jequitaí']);
		DB::table('cidades')->insert(['id' => 3135704, 'estado_id' => 31, 'nome' => 'Jequitibá']);
		DB::table('cidades')->insert(['id' => 3135803, 'estado_id' => 31, 'nome' => 'Jequitinhonha']);
		DB::table('cidades')->insert(['id' => 3135902, 'estado_id' => 31, 'nome' => 'Jesuânia']);
		DB::table('cidades')->insert(['id' => 3136009, 'estado_id' => 31, 'nome' => 'Joaíma']);
		DB::table('cidades')->insert(['id' => 3136108, 'estado_id' => 31, 'nome' => 'Joanésia']);
		DB::table('cidades')->insert(['id' => 3136207, 'estado_id' => 31, 'nome' => 'João Monlevade']);
		DB::table('cidades')->insert(['id' => 3136306, 'estado_id' => 31, 'nome' => 'João Pinheiro']);
		DB::table('cidades')->insert(['id' => 3136405, 'estado_id' => 31, 'nome' => 'Joaquim Felício']);
		DB::table('cidades')->insert(['id' => 3136504, 'estado_id' => 31, 'nome' => 'Jordânia']);
		DB::table('cidades')->insert(['id' => 3136520, 'estado_id' => 31, 'nome' => 'José Gonçalves de Minas']);
		DB::table('cidades')->insert(['id' => 3136553, 'estado_id' => 31, 'nome' => 'José Raydan']);
		DB::table('cidades')->insert(['id' => 3136579, 'estado_id' => 31, 'nome' => 'Josenópolis']);
		DB::table('cidades')->insert(['id' => 3136603, 'estado_id' => 31, 'nome' => 'Nova União']);
		DB::table('cidades')->insert(['id' => 3136652, 'estado_id' => 31, 'nome' => 'Juatuba']);
		DB::table('cidades')->insert(['id' => 3136702, 'estado_id' => 31, 'nome' => 'Juiz de Fora']);
		DB::table('cidades')->insert(['id' => 3136801, 'estado_id' => 31, 'nome' => 'Juramento']);
		DB::table('cidades')->insert(['id' => 3136900, 'estado_id' => 31, 'nome' => 'Juruaia']);
		DB::table('cidades')->insert(['id' => 3136959, 'estado_id' => 31, 'nome' => 'Juvenília']);
		DB::table('cidades')->insert(['id' => 3137007, 'estado_id' => 31, 'nome' => 'Ladainha']);
		DB::table('cidades')->insert(['id' => 3137106, 'estado_id' => 31, 'nome' => 'Lagamar']);
		DB::table('cidades')->insert(['id' => 3137205, 'estado_id' => 31, 'nome' => 'Lagoa da Prata']);
		DB::table('cidades')->insert(['id' => 3137304, 'estado_id' => 31, 'nome' => 'Lagoa dos Patos']);
		DB::table('cidades')->insert(['id' => 3137403, 'estado_id' => 31, 'nome' => 'Lagoa Dourada']);
		DB::table('cidades')->insert(['id' => 3137502, 'estado_id' => 31, 'nome' => 'Lagoa Formosa']);
		DB::table('cidades')->insert(['id' => 3137536, 'estado_id' => 31, 'nome' => 'Lagoa Grande']);
		DB::table('cidades')->insert(['id' => 3137601, 'estado_id' => 31, 'nome' => 'Lagoa Santa']);
		DB::table('cidades')->insert(['id' => 3137700, 'estado_id' => 31, 'nome' => 'Lajinha']);
		DB::table('cidades')->insert(['id' => 3137809, 'estado_id' => 31, 'nome' => 'Lambari']);
		DB::table('cidades')->insert(['id' => 3137908, 'estado_id' => 31, 'nome' => 'Lamim']);
		DB::table('cidades')->insert(['id' => 3138005, 'estado_id' => 31, 'nome' => 'Laranjal']);
		DB::table('cidades')->insert(['id' => 3138104, 'estado_id' => 31, 'nome' => 'Lassance']);
		DB::table('cidades')->insert(['id' => 3138203, 'estado_id' => 31, 'nome' => 'Lavras']);
		DB::table('cidades')->insert(['id' => 3138302, 'estado_id' => 31, 'nome' => 'Leandro Ferreira']);
		DB::table('cidades')->insert(['id' => 3138351, 'estado_id' => 31, 'nome' => 'Leme do Prado']);
		DB::table('cidades')->insert(['id' => 3138401, 'estado_id' => 31, 'nome' => 'Leopoldina']);
		DB::table('cidades')->insert(['id' => 3138500, 'estado_id' => 31, 'nome' => 'Liberdade']);
		DB::table('cidades')->insert(['id' => 3138609, 'estado_id' => 31, 'nome' => 'Lima Duarte']);
		DB::table('cidades')->insert(['id' => 3138625, 'estado_id' => 31, 'nome' => 'Limeira do Oeste']);
		DB::table('cidades')->insert(['id' => 3138658, 'estado_id' => 31, 'nome' => 'Lontra']);
		DB::table('cidades')->insert(['id' => 3138674, 'estado_id' => 31, 'nome' => 'Luisburgo']);
		DB::table('cidades')->insert(['id' => 3138682, 'estado_id' => 31, 'nome' => 'Luislândia']);
		DB::table('cidades')->insert(['id' => 3138708, 'estado_id' => 31, 'nome' => 'Luminárias']);
		DB::table('cidades')->insert(['id' => 3138807, 'estado_id' => 31, 'nome' => 'Luz']);
		DB::table('cidades')->insert(['id' => 3138906, 'estado_id' => 31, 'nome' => 'Machacalis']);
		DB::table('cidades')->insert(['id' => 3139003, 'estado_id' => 31, 'nome' => 'Machado']);
		DB::table('cidades')->insert(['id' => 3139102, 'estado_id' => 31, 'nome' => 'Madre de Deus de Minas']);
		DB::table('cidades')->insert(['id' => 3139201, 'estado_id' => 31, 'nome' => 'Malacacheta']);
		DB::table('cidades')->insert(['id' => 3139250, 'estado_id' => 31, 'nome' => 'Mamonas']);
		DB::table('cidades')->insert(['id' => 3139300, 'estado_id' => 31, 'nome' => 'Manga']);
		DB::table('cidades')->insert(['id' => 3139409, 'estado_id' => 31, 'nome' => 'Manhuaçu']);
		DB::table('cidades')->insert(['id' => 3139508, 'estado_id' => 31, 'nome' => 'Manhumirim']);
		DB::table('cidades')->insert(['id' => 3139607, 'estado_id' => 31, 'nome' => 'Mantena']);
		DB::table('cidades')->insert(['id' => 3139706, 'estado_id' => 31, 'nome' => 'Maravilhas']);
		DB::table('cidades')->insert(['id' => 3139805, 'estado_id' => 31, 'nome' => 'Mar de Espanha']);
		DB::table('cidades')->insert(['id' => 3139904, 'estado_id' => 31, 'nome' => 'Maria da Fé']);
		DB::table('cidades')->insert(['id' => 3140001, 'estado_id' => 31, 'nome' => 'Mariana']);
		DB::table('cidades')->insert(['id' => 3140100, 'estado_id' => 31, 'nome' => 'Marilac']);
		DB::table('cidades')->insert(['id' => 3140159, 'estado_id' => 31, 'nome' => 'Mário Campos']);
		DB::table('cidades')->insert(['id' => 3140209, 'estado_id' => 31, 'nome' => 'Maripá de Minas']);
		DB::table('cidades')->insert(['id' => 3140308, 'estado_id' => 31, 'nome' => 'Marliéria']);
		DB::table('cidades')->insert(['id' => 3140407, 'estado_id' => 31, 'nome' => 'Marmelópolis']);
		DB::table('cidades')->insert(['id' => 3140506, 'estado_id' => 31, 'nome' => 'Martinho Campos']);
		DB::table('cidades')->insert(['id' => 3140530, 'estado_id' => 31, 'nome' => 'Martins Soares']);
		DB::table('cidades')->insert(['id' => 3140555, 'estado_id' => 31, 'nome' => 'Mata Verde']);
		DB::table('cidades')->insert(['id' => 3140605, 'estado_id' => 31, 'nome' => 'Materlândia']);
		DB::table('cidades')->insert(['id' => 3140704, 'estado_id' => 31, 'nome' => 'Mateus Leme']);
		DB::table('cidades')->insert(['id' => 3140803, 'estado_id' => 31, 'nome' => 'Matias Barbosa']);
		DB::table('cidades')->insert(['id' => 3140852, 'estado_id' => 31, 'nome' => 'Matias Cardoso']);
		DB::table('cidades')->insert(['id' => 3140902, 'estado_id' => 31, 'nome' => 'Matipó']);
		DB::table('cidades')->insert(['id' => 3141009, 'estado_id' => 31, 'nome' => 'Mato Verde']);
		DB::table('cidades')->insert(['id' => 3141108, 'estado_id' => 31, 'nome' => 'Matozinhos']);
		DB::table('cidades')->insert(['id' => 3141207, 'estado_id' => 31, 'nome' => 'Matutina']);
		DB::table('cidades')->insert(['id' => 3141306, 'estado_id' => 31, 'nome' => 'Medeiros']);
		DB::table('cidades')->insert(['id' => 3141405, 'estado_id' => 31, 'nome' => 'Medina']);
		DB::table('cidades')->insert(['id' => 3141504, 'estado_id' => 31, 'nome' => 'Mendes Pimentel']);
		DB::table('cidades')->insert(['id' => 3141603, 'estado_id' => 31, 'nome' => 'Mercês']);
		DB::table('cidades')->insert(['id' => 3141702, 'estado_id' => 31, 'nome' => 'Mesquita']);
		DB::table('cidades')->insert(['id' => 3141801, 'estado_id' => 31, 'nome' => 'Minas Novas']);
		DB::table('cidades')->insert(['id' => 3141900, 'estado_id' => 31, 'nome' => 'Minduri']);
		DB::table('cidades')->insert(['id' => 3142007, 'estado_id' => 31, 'nome' => 'Mirabela']);
		DB::table('cidades')->insert(['id' => 3142106, 'estado_id' => 31, 'nome' => 'Miradouro']);
		DB::table('cidades')->insert(['id' => 3142205, 'estado_id' => 31, 'nome' => 'Miraí']);
		DB::table('cidades')->insert(['id' => 3142254, 'estado_id' => 31, 'nome' => 'Miravânia']);
		DB::table('cidades')->insert(['id' => 3142304, 'estado_id' => 31, 'nome' => 'Moeda']);
		DB::table('cidades')->insert(['id' => 3142403, 'estado_id' => 31, 'nome' => 'Moema']);
		DB::table('cidades')->insert(['id' => 3142502, 'estado_id' => 31, 'nome' => 'Monjolos']);
		DB::table('cidades')->insert(['id' => 3142601, 'estado_id' => 31, 'nome' => 'Monsenhor Paulo']);
		DB::table('cidades')->insert(['id' => 3142700, 'estado_id' => 31, 'nome' => 'Montalvânia']);
		DB::table('cidades')->insert(['id' => 3142809, 'estado_id' => 31, 'nome' => 'Monte Alegre de Minas']);
		DB::table('cidades')->insert(['id' => 3142908, 'estado_id' => 31, 'nome' => 'Monte Azul']);
		DB::table('cidades')->insert(['id' => 3143005, 'estado_id' => 31, 'nome' => 'Monte Belo']);
		DB::table('cidades')->insert(['id' => 3143104, 'estado_id' => 31, 'nome' => 'Monte Carmelo']);
		DB::table('cidades')->insert(['id' => 3143153, 'estado_id' => 31, 'nome' => 'Monte Formoso']);
		DB::table('cidades')->insert(['id' => 3143203, 'estado_id' => 31, 'nome' => 'Monte Santo de Minas']);
		DB::table('cidades')->insert(['id' => 3143302, 'estado_id' => 31, 'nome' => 'Montes Claros']);
		DB::table('cidades')->insert(['id' => 3143401, 'estado_id' => 31, 'nome' => 'Monte Sião']);
		DB::table('cidades')->insert(['id' => 3143450, 'estado_id' => 31, 'nome' => 'Montezuma']);
		DB::table('cidades')->insert(['id' => 3143500, 'estado_id' => 31, 'nome' => 'Morada Nova de Minas']);
		DB::table('cidades')->insert(['id' => 3143609, 'estado_id' => 31, 'nome' => 'Morro da Garça']);
		DB::table('cidades')->insert(['id' => 3143708, 'estado_id' => 31, 'nome' => 'Morro do Pilar']);
		DB::table('cidades')->insert(['id' => 3143807, 'estado_id' => 31, 'nome' => 'Munhoz']);
		DB::table('cidades')->insert(['id' => 3143906, 'estado_id' => 31, 'nome' => 'Muriaé']);
		DB::table('cidades')->insert(['id' => 3144003, 'estado_id' => 31, 'nome' => 'Mutum']);
		DB::table('cidades')->insert(['id' => 3144102, 'estado_id' => 31, 'nome' => 'Muzambinho']);
		DB::table('cidades')->insert(['id' => 3144201, 'estado_id' => 31, 'nome' => 'Nacip Raydan']);
		DB::table('cidades')->insert(['id' => 3144300, 'estado_id' => 31, 'nome' => 'Nanuque']);
		DB::table('cidades')->insert(['id' => 3144359, 'estado_id' => 31, 'nome' => 'Naque']);
		DB::table('cidades')->insert(['id' => 3144375, 'estado_id' => 31, 'nome' => 'Natalândia']);
		DB::table('cidades')->insert(['id' => 3144409, 'estado_id' => 31, 'nome' => 'Natércia']);
		DB::table('cidades')->insert(['id' => 3144508, 'estado_id' => 31, 'nome' => 'Nazareno']);
		DB::table('cidades')->insert(['id' => 3144607, 'estado_id' => 31, 'nome' => 'Nepomuceno']);
		DB::table('cidades')->insert(['id' => 3144656, 'estado_id' => 31, 'nome' => 'Ninheira']);
		DB::table('cidades')->insert(['id' => 3144672, 'estado_id' => 31, 'nome' => 'Nova Belém']);
		DB::table('cidades')->insert(['id' => 3144706, 'estado_id' => 31, 'nome' => 'Nova Era']);
		DB::table('cidades')->insert(['id' => 3144805, 'estado_id' => 31, 'nome' => 'Nova Lima']);
		DB::table('cidades')->insert(['id' => 3144904, 'estado_id' => 31, 'nome' => 'Nova Módica']);
		DB::table('cidades')->insert(['id' => 3145000, 'estado_id' => 31, 'nome' => 'Nova Ponte']);
		DB::table('cidades')->insert(['id' => 3145059, 'estado_id' => 31, 'nome' => 'Nova Porteirinha']);
		DB::table('cidades')->insert(['id' => 3145109, 'estado_id' => 31, 'nome' => 'Nova Resende']);
		DB::table('cidades')->insert(['id' => 3145208, 'estado_id' => 31, 'nome' => 'Nova Serrana']);
		DB::table('cidades')->insert(['id' => 3145307, 'estado_id' => 31, 'nome' => 'Novo Cruzeiro']);
		DB::table('cidades')->insert(['id' => 3145356, 'estado_id' => 31, 'nome' => 'Novo Oriente de Minas']);
		DB::table('cidades')->insert(['id' => 3145372, 'estado_id' => 31, 'nome' => 'Novorizonte']);
		DB::table('cidades')->insert(['id' => 3145406, 'estado_id' => 31, 'nome' => 'Olaria']);
		DB::table('cidades')->insert(['id' => 3145455, 'estado_id' => 31, 'nome' => 'Olhos-d\'Água']);
		DB::table('cidades')->insert(['id' => 3145505, 'estado_id' => 31, 'nome' => 'Olímpio Noronha']);
		DB::table('cidades')->insert(['id' => 3145604, 'estado_id' => 31, 'nome' => 'Oliveira']);
		DB::table('cidades')->insert(['id' => 3145703, 'estado_id' => 31, 'nome' => 'Oliveira Fortes']);
		DB::table('cidades')->insert(['id' => 3145802, 'estado_id' => 31, 'nome' => 'Onça de Pitangui']);
		DB::table('cidades')->insert(['id' => 3145851, 'estado_id' => 31, 'nome' => 'Oratórios']);
		DB::table('cidades')->insert(['id' => 3145877, 'estado_id' => 31, 'nome' => 'Orizânia']);
		DB::table('cidades')->insert(['id' => 3145901, 'estado_id' => 31, 'nome' => 'Ouro Branco']);
		DB::table('cidades')->insert(['id' => 3146008, 'estado_id' => 31, 'nome' => 'Ouro Fino']);
		DB::table('cidades')->insert(['id' => 3146107, 'estado_id' => 31, 'nome' => 'Ouro Preto']);
		DB::table('cidades')->insert(['id' => 3146206, 'estado_id' => 31, 'nome' => 'Ouro Verde de Minas']);
		DB::table('cidades')->insert(['id' => 3146255, 'estado_id' => 31, 'nome' => 'Padre Carvalho']);
		DB::table('cidades')->insert(['id' => 3146305, 'estado_id' => 31, 'nome' => 'Padre Paraíso']);
		DB::table('cidades')->insert(['id' => 3146404, 'estado_id' => 31, 'nome' => 'Paineiras']);
		DB::table('cidades')->insert(['id' => 3146503, 'estado_id' => 31, 'nome' => 'Pains']);
		DB::table('cidades')->insert(['id' => 3146552, 'estado_id' => 31, 'nome' => 'Pai Pedro']);
		DB::table('cidades')->insert(['id' => 3146602, 'estado_id' => 31, 'nome' => 'Paiva']);
		DB::table('cidades')->insert(['id' => 3146701, 'estado_id' => 31, 'nome' => 'Palma']);
		DB::table('cidades')->insert(['id' => 3146750, 'estado_id' => 31, 'nome' => 'Palmópolis']);
		DB::table('cidades')->insert(['id' => 3146909, 'estado_id' => 31, 'nome' => 'Papagaios']);
		DB::table('cidades')->insert(['id' => 3147006, 'estado_id' => 31, 'nome' => 'Paracatu']);
		DB::table('cidades')->insert(['id' => 3147105, 'estado_id' => 31, 'nome' => 'Pará de Minas']);
		DB::table('cidades')->insert(['id' => 3147204, 'estado_id' => 31, 'nome' => 'Paraguaçu']);
		DB::table('cidades')->insert(['id' => 3147303, 'estado_id' => 31, 'nome' => 'Paraisópolis']);
		DB::table('cidades')->insert(['id' => 3147402, 'estado_id' => 31, 'nome' => 'Paraopeba']);
		DB::table('cidades')->insert(['id' => 3147501, 'estado_id' => 31, 'nome' => 'Passabém']);
		DB::table('cidades')->insert(['id' => 3147600, 'estado_id' => 31, 'nome' => 'Passa Quatro']);
		DB::table('cidades')->insert(['id' => 3147709, 'estado_id' => 31, 'nome' => 'Passa Tempo']);
		DB::table('cidades')->insert(['id' => 3147808, 'estado_id' => 31, 'nome' => 'Passa-Vinte']);
		DB::table('cidades')->insert(['id' => 3147907, 'estado_id' => 31, 'nome' => 'Passos']);
		DB::table('cidades')->insert(['id' => 3147956, 'estado_id' => 31, 'nome' => 'Patis']);
		DB::table('cidades')->insert(['id' => 3148004, 'estado_id' => 31, 'nome' => 'Patos de Minas']);
		DB::table('cidades')->insert(['id' => 3148103, 'estado_id' => 31, 'nome' => 'Patrocínio']);
		DB::table('cidades')->insert(['id' => 3148202, 'estado_id' => 31, 'nome' => 'Patrocínio do Muriaé']);
		DB::table('cidades')->insert(['id' => 3148301, 'estado_id' => 31, 'nome' => 'Paula Cândido']);
		DB::table('cidades')->insert(['id' => 3148400, 'estado_id' => 31, 'nome' => 'Paulistas']);
		DB::table('cidades')->insert(['id' => 3148509, 'estado_id' => 31, 'nome' => 'Pavão']);
		DB::table('cidades')->insert(['id' => 3148608, 'estado_id' => 31, 'nome' => 'Peçanha']);
		DB::table('cidades')->insert(['id' => 3148707, 'estado_id' => 31, 'nome' => 'Pedra Azul']);
		DB::table('cidades')->insert(['id' => 3148756, 'estado_id' => 31, 'nome' => 'Pedra Bonita']);
		DB::table('cidades')->insert(['id' => 3148806, 'estado_id' => 31, 'nome' => 'Pedra do Anta']);
		DB::table('cidades')->insert(['id' => 3148905, 'estado_id' => 31, 'nome' => 'Pedra do Indaiá']);
		DB::table('cidades')->insert(['id' => 3149002, 'estado_id' => 31, 'nome' => 'Pedra Dourada']);
		DB::table('cidades')->insert(['id' => 3149101, 'estado_id' => 31, 'nome' => 'Pedralva']);
		DB::table('cidades')->insert(['id' => 3149150, 'estado_id' => 31, 'nome' => 'Pedras de Maria da Cruz']);
		DB::table('cidades')->insert(['id' => 3149200, 'estado_id' => 31, 'nome' => 'Pedrinópolis']);
		DB::table('cidades')->insert(['id' => 3149309, 'estado_id' => 31, 'nome' => 'Pedro Leopoldo']);
		DB::table('cidades')->insert(['id' => 3149408, 'estado_id' => 31, 'nome' => 'Pedro Teixeira']);
		DB::table('cidades')->insert(['id' => 3149507, 'estado_id' => 31, 'nome' => 'Pequeri']);
		DB::table('cidades')->insert(['id' => 3149606, 'estado_id' => 31, 'nome' => 'Pequi']);
		DB::table('cidades')->insert(['id' => 3149705, 'estado_id' => 31, 'nome' => 'Perdigão']);
		DB::table('cidades')->insert(['id' => 3149804, 'estado_id' => 31, 'nome' => 'Perdizes']);
		DB::table('cidades')->insert(['id' => 3149903, 'estado_id' => 31, 'nome' => 'Perdões']);
		DB::table('cidades')->insert(['id' => 3149952, 'estado_id' => 31, 'nome' => 'Periquito']);
		DB::table('cidades')->insert(['id' => 3150000, 'estado_id' => 31, 'nome' => 'Pescador']);
		DB::table('cidades')->insert(['id' => 3150109, 'estado_id' => 31, 'nome' => 'Piau']);
		DB::table('cidades')->insert(['id' => 3150158, 'estado_id' => 31, 'nome' => 'Piedade de Caratinga']);
		DB::table('cidades')->insert(['id' => 3150208, 'estado_id' => 31, 'nome' => 'Piedade de Ponte Nova']);
		DB::table('cidades')->insert(['id' => 3150307, 'estado_id' => 31, 'nome' => 'Piedade do Rio Grande']);
		DB::table('cidades')->insert(['id' => 3150406, 'estado_id' => 31, 'nome' => 'Piedade dos Gerais']);
		DB::table('cidades')->insert(['id' => 3150505, 'estado_id' => 31, 'nome' => 'Pimenta']);
		DB::table('cidades')->insert(['id' => 3150539, 'estado_id' => 31, 'nome' => 'Pingo-d\'Água']);
		DB::table('cidades')->insert(['id' => 3150570, 'estado_id' => 31, 'nome' => 'Pintópolis']);
		DB::table('cidades')->insert(['id' => 3150604, 'estado_id' => 31, 'nome' => 'Piracema']);
		DB::table('cidades')->insert(['id' => 3150703, 'estado_id' => 31, 'nome' => 'Pirajuba']);
		DB::table('cidades')->insert(['id' => 3150802, 'estado_id' => 31, 'nome' => 'Piranga']);
		DB::table('cidades')->insert(['id' => 3150901, 'estado_id' => 31, 'nome' => 'Piranguçu']);
		DB::table('cidades')->insert(['id' => 3151008, 'estado_id' => 31, 'nome' => 'Piranguinho']);
		DB::table('cidades')->insert(['id' => 3151107, 'estado_id' => 31, 'nome' => 'Pirapetinga']);
		DB::table('cidades')->insert(['id' => 3151206, 'estado_id' => 31, 'nome' => 'Pirapora']);
		DB::table('cidades')->insert(['id' => 3151305, 'estado_id' => 31, 'nome' => 'Piraúba']);
		DB::table('cidades')->insert(['id' => 3151404, 'estado_id' => 31, 'nome' => 'Pitangui']);
		DB::table('cidades')->insert(['id' => 3151503, 'estado_id' => 31, 'nome' => 'Piumhi']);
		DB::table('cidades')->insert(['id' => 3151602, 'estado_id' => 31, 'nome' => 'Planura']);
		DB::table('cidades')->insert(['id' => 3151701, 'estado_id' => 31, 'nome' => 'Poço Fundo']);
		DB::table('cidades')->insert(['id' => 3151800, 'estado_id' => 31, 'nome' => 'Poços de Caldas']);
		DB::table('cidades')->insert(['id' => 3151909, 'estado_id' => 31, 'nome' => 'Pocrane']);
		DB::table('cidades')->insert(['id' => 3152006, 'estado_id' => 31, 'nome' => 'Pompéu']);
		DB::table('cidades')->insert(['id' => 3152105, 'estado_id' => 31, 'nome' => 'Ponte Nova']);
		DB::table('cidades')->insert(['id' => 3152131, 'estado_id' => 31, 'nome' => 'Ponto Chique']);
		DB::table('cidades')->insert(['id' => 3152170, 'estado_id' => 31, 'nome' => 'Ponto dos Volantes']);
		DB::table('cidades')->insert(['id' => 3152204, 'estado_id' => 31, 'nome' => 'Porteirinha']);
		DB::table('cidades')->insert(['id' => 3152303, 'estado_id' => 31, 'nome' => 'Porto Firme']);
		DB::table('cidades')->insert(['id' => 3152402, 'estado_id' => 31, 'nome' => 'Poté']);
		DB::table('cidades')->insert(['id' => 3152501, 'estado_id' => 31, 'nome' => 'Pouso Alegre']);
		DB::table('cidades')->insert(['id' => 3152600, 'estado_id' => 31, 'nome' => 'Pouso Alto']);
		DB::table('cidades')->insert(['id' => 3152709, 'estado_id' => 31, 'nome' => 'Prados']);
		DB::table('cidades')->insert(['id' => 3152808, 'estado_id' => 31, 'nome' => 'Prata']);
		DB::table('cidades')->insert(['id' => 3152907, 'estado_id' => 31, 'nome' => 'Pratápolis']);
		DB::table('cidades')->insert(['id' => 3153004, 'estado_id' => 31, 'nome' => 'Pratinha']);
		DB::table('cidades')->insert(['id' => 3153103, 'estado_id' => 31, 'nome' => 'Presidente Bernardes']);
		DB::table('cidades')->insert(['id' => 3153202, 'estado_id' => 31, 'nome' => 'Presidente Juscelino']);
		DB::table('cidades')->insert(['id' => 3153301, 'estado_id' => 31, 'nome' => 'Presidente Kubitschek']);
		DB::table('cidades')->insert(['id' => 3153400, 'estado_id' => 31, 'nome' => 'Presidente Olegário']);
		DB::table('cidades')->insert(['id' => 3153509, 'estado_id' => 31, 'nome' => 'Alto Jequitibá']);
		DB::table('cidades')->insert(['id' => 3153608, 'estado_id' => 31, 'nome' => 'Prudente de Morais']);
		DB::table('cidades')->insert(['id' => 3153707, 'estado_id' => 31, 'nome' => 'Quartel Geral']);
		DB::table('cidades')->insert(['id' => 3153806, 'estado_id' => 31, 'nome' => 'Queluzito']);
		DB::table('cidades')->insert(['id' => 3153905, 'estado_id' => 31, 'nome' => 'Raposos']);
		DB::table('cidades')->insert(['id' => 3154002, 'estado_id' => 31, 'nome' => 'Raul Soares']);
		DB::table('cidades')->insert(['id' => 3154101, 'estado_id' => 31, 'nome' => 'Recreio']);
		DB::table('cidades')->insert(['id' => 3154150, 'estado_id' => 31, 'nome' => 'Reduto']);
		DB::table('cidades')->insert(['id' => 3154200, 'estado_id' => 31, 'nome' => 'Resende Costa']);
		DB::table('cidades')->insert(['id' => 3154309, 'estado_id' => 31, 'nome' => 'Resplendor']);
		DB::table('cidades')->insert(['id' => 3154408, 'estado_id' => 31, 'nome' => 'Ressaquinha']);
		DB::table('cidades')->insert(['id' => 3154457, 'estado_id' => 31, 'nome' => 'Riachinho']);
		DB::table('cidades')->insert(['id' => 3154507, 'estado_id' => 31, 'nome' => 'Riacho dos Machados']);
		DB::table('cidades')->insert(['id' => 3154606, 'estado_id' => 31, 'nome' => 'Ribeirão das Neves']);
		DB::table('cidades')->insert(['id' => 3154705, 'estado_id' => 31, 'nome' => 'Ribeirão Vermelho']);
		DB::table('cidades')->insert(['id' => 3154804, 'estado_id' => 31, 'nome' => 'Rio Acima']);
		DB::table('cidades')->insert(['id' => 3154903, 'estado_id' => 31, 'nome' => 'Rio Casca']);
		DB::table('cidades')->insert(['id' => 3155009, 'estado_id' => 31, 'nome' => 'Rio Doce']);
		DB::table('cidades')->insert(['id' => 3155108, 'estado_id' => 31, 'nome' => 'Rio do Prado']);
		DB::table('cidades')->insert(['id' => 3155207, 'estado_id' => 31, 'nome' => 'Rio Espera']);
		DB::table('cidades')->insert(['id' => 3155306, 'estado_id' => 31, 'nome' => 'Rio Manso']);
		DB::table('cidades')->insert(['id' => 3155405, 'estado_id' => 31, 'nome' => 'Rio Novo']);
		DB::table('cidades')->insert(['id' => 3155504, 'estado_id' => 31, 'nome' => 'Rio Paranaíba']);
		DB::table('cidades')->insert(['id' => 3155603, 'estado_id' => 31, 'nome' => 'Rio Pardo de Minas']);
		DB::table('cidades')->insert(['id' => 3155702, 'estado_id' => 31, 'nome' => 'Rio Piracicaba']);
		DB::table('cidades')->insert(['id' => 3155801, 'estado_id' => 31, 'nome' => 'Rio Pomba']);
		DB::table('cidades')->insert(['id' => 3155900, 'estado_id' => 31, 'nome' => 'Rio Preto']);
		DB::table('cidades')->insert(['id' => 3156007, 'estado_id' => 31, 'nome' => 'Rio Vermelho']);
		DB::table('cidades')->insert(['id' => 3156106, 'estado_id' => 31, 'nome' => 'Ritápolis']);
		DB::table('cidades')->insert(['id' => 3156205, 'estado_id' => 31, 'nome' => 'Rochedo de Minas']);
		DB::table('cidades')->insert(['id' => 3156304, 'estado_id' => 31, 'nome' => 'Rodeiro']);
		DB::table('cidades')->insert(['id' => 3156403, 'estado_id' => 31, 'nome' => 'Romaria']);
		DB::table('cidades')->insert(['id' => 3156452, 'estado_id' => 31, 'nome' => 'Rosário da Limeira']);
		DB::table('cidades')->insert(['id' => 3156502, 'estado_id' => 31, 'nome' => 'Rubelita']);
		DB::table('cidades')->insert(['id' => 3156601, 'estado_id' => 31, 'nome' => 'Rubim']);
		DB::table('cidades')->insert(['id' => 3156700, 'estado_id' => 31, 'nome' => 'Sabará']);
		DB::table('cidades')->insert(['id' => 3156809, 'estado_id' => 31, 'nome' => 'Sabinópolis']);
		DB::table('cidades')->insert(['id' => 3156908, 'estado_id' => 31, 'nome' => 'Sacramento']);
		DB::table('cidades')->insert(['id' => 3157005, 'estado_id' => 31, 'nome' => 'Salinas']);
		DB::table('cidades')->insert(['id' => 3157104, 'estado_id' => 31, 'nome' => 'Salto da Divisa']);
		DB::table('cidades')->insert(['id' => 3157203, 'estado_id' => 31, 'nome' => 'Santa Bárbara']);
		DB::table('cidades')->insert(['id' => 3157252, 'estado_id' => 31, 'nome' => 'Santa Bárbara do Leste']);
		DB::table('cidades')->insert(['id' => 3157278, 'estado_id' => 31, 'nome' => 'Santa Bárbara do Monte Verde']);
		DB::table('cidades')->insert(['id' => 3157302, 'estado_id' => 31, 'nome' => 'Santa Bárbara do Tugúrio']);
		DB::table('cidades')->insert(['id' => 3157336, 'estado_id' => 31, 'nome' => 'Santa Cruz de Minas']);
		DB::table('cidades')->insert(['id' => 3157377, 'estado_id' => 31, 'nome' => 'Santa Cruz de Salinas']);
		DB::table('cidades')->insert(['id' => 3157401, 'estado_id' => 31, 'nome' => 'Santa Cruz do Escalvado']);
		DB::table('cidades')->insert(['id' => 3157500, 'estado_id' => 31, 'nome' => 'Santa Efigênia de Minas']);
		DB::table('cidades')->insert(['id' => 3157609, 'estado_id' => 31, 'nome' => 'Santa Fé de Minas']);
		DB::table('cidades')->insert(['id' => 3157658, 'estado_id' => 31, 'nome' => 'Santa Helena de Minas']);
		DB::table('cidades')->insert(['id' => 3157708, 'estado_id' => 31, 'nome' => 'Santa Juliana']);
		DB::table('cidades')->insert(['id' => 3157807, 'estado_id' => 31, 'nome' => 'Santa Luzia']);
		DB::table('cidades')->insert(['id' => 3157906, 'estado_id' => 31, 'nome' => 'Santa Margarida']);
		DB::table('cidades')->insert(['id' => 3158003, 'estado_id' => 31, 'nome' => 'Santa Maria de Itabira']);
		DB::table('cidades')->insert(['id' => 3158102, 'estado_id' => 31, 'nome' => 'Santa Maria do Salto']);
		DB::table('cidades')->insert(['id' => 3158201, 'estado_id' => 31, 'nome' => 'Santa Maria do Suaçuí']);
		DB::table('cidades')->insert(['id' => 3158300, 'estado_id' => 31, 'nome' => 'Santana da Vargem']);
		DB::table('cidades')->insert(['id' => 3158409, 'estado_id' => 31, 'nome' => 'Santana de Cataguases']);
		DB::table('cidades')->insert(['id' => 3158508, 'estado_id' => 31, 'nome' => 'Santana de Pirapama']);
		DB::table('cidades')->insert(['id' => 3158607, 'estado_id' => 31, 'nome' => 'Santana do Deserto']);
		DB::table('cidades')->insert(['id' => 3158706, 'estado_id' => 31, 'nome' => 'Santana do Garambéu']);
		DB::table('cidades')->insert(['id' => 3158805, 'estado_id' => 31, 'nome' => 'Santana do Jacaré']);
		DB::table('cidades')->insert(['id' => 3158904, 'estado_id' => 31, 'nome' => 'Santana do Manhuaçu']);
		DB::table('cidades')->insert(['id' => 3158953, 'estado_id' => 31, 'nome' => 'Santana do Paraíso']);
		DB::table('cidades')->insert(['id' => 3159001, 'estado_id' => 31, 'nome' => 'Santana do Riacho']);
		DB::table('cidades')->insert(['id' => 3159100, 'estado_id' => 31, 'nome' => 'Santana dos Montes']);
		DB::table('cidades')->insert(['id' => 3159209, 'estado_id' => 31, 'nome' => 'Santa Rita de Caldas']);
		DB::table('cidades')->insert(['id' => 3159308, 'estado_id' => 31, 'nome' => 'Santa Rita de Jacutinga']);
		DB::table('cidades')->insert(['id' => 3159357, 'estado_id' => 31, 'nome' => 'Santa Rita de Minas']);
		DB::table('cidades')->insert(['id' => 3159407, 'estado_id' => 31, 'nome' => 'Santa Rita de Ibitipoca']);
		DB::table('cidades')->insert(['id' => 3159506, 'estado_id' => 31, 'nome' => 'Santa Rita do Itueto']);
		DB::table('cidades')->insert(['id' => 3159605, 'estado_id' => 31, 'nome' => 'Santa Rita do Sapucaí']);
		DB::table('cidades')->insert(['id' => 3159704, 'estado_id' => 31, 'nome' => 'Santa Rosa da Serra']);
		DB::table('cidades')->insert(['id' => 3159803, 'estado_id' => 31, 'nome' => 'Santa Vitória']);
		DB::table('cidades')->insert(['id' => 3159902, 'estado_id' => 31, 'nome' => 'Santo Antônio do Amparo']);
		DB::table('cidades')->insert(['id' => 3160009, 'estado_id' => 31, 'nome' => 'Santo Antônio do Aventureiro']);
		DB::table('cidades')->insert(['id' => 3160108, 'estado_id' => 31, 'nome' => 'Santo Antônio do Grama']);
		DB::table('cidades')->insert(['id' => 3160207, 'estado_id' => 31, 'nome' => 'Santo Antônio do Itambé']);
		DB::table('cidades')->insert(['id' => 3160306, 'estado_id' => 31, 'nome' => 'Santo Antônio do Jacinto']);
		DB::table('cidades')->insert(['id' => 3160405, 'estado_id' => 31, 'nome' => 'Santo Antônio do Monte']);
		DB::table('cidades')->insert(['id' => 3160454, 'estado_id' => 31, 'nome' => 'Santo Antônio do Retiro']);
		DB::table('cidades')->insert(['id' => 3160504, 'estado_id' => 31, 'nome' => 'Santo Antônio do Rio Abaixo']);
		DB::table('cidades')->insert(['id' => 3160603, 'estado_id' => 31, 'nome' => 'Santo Hipólito']);
		DB::table('cidades')->insert(['id' => 3160702, 'estado_id' => 31, 'nome' => 'Santos Dumont']);
		DB::table('cidades')->insert(['id' => 3160801, 'estado_id' => 31, 'nome' => 'São Bento Abade']);
		DB::table('cidades')->insert(['id' => 3160900, 'estado_id' => 31, 'nome' => 'São Brás do Suaçuí']);
		DB::table('cidades')->insert(['id' => 3160959, 'estado_id' => 31, 'nome' => 'São Domingos das Dores']);
		DB::table('cidades')->insert(['id' => 3161007, 'estado_id' => 31, 'nome' => 'São Domingos do Prata']);
		DB::table('cidades')->insert(['id' => 3161056, 'estado_id' => 31, 'nome' => 'São Félix de Minas']);
		DB::table('cidades')->insert(['id' => 3161106, 'estado_id' => 31, 'nome' => 'São Francisco']);
		DB::table('cidades')->insert(['id' => 3161205, 'estado_id' => 31, 'nome' => 'São Francisco de Paula']);
		DB::table('cidades')->insert(['id' => 3161304, 'estado_id' => 31, 'nome' => 'São Francisco de Sales']);
		DB::table('cidades')->insert(['id' => 3161403, 'estado_id' => 31, 'nome' => 'São Francisco do Glória']);
		DB::table('cidades')->insert(['id' => 3161502, 'estado_id' => 31, 'nome' => 'São Geraldo']);
		DB::table('cidades')->insert(['id' => 3161601, 'estado_id' => 31, 'nome' => 'São Geraldo da Piedade']);
		DB::table('cidades')->insert(['id' => 3161650, 'estado_id' => 31, 'nome' => 'São Geraldo do Baixio']);
		DB::table('cidades')->insert(['id' => 3161700, 'estado_id' => 31, 'nome' => 'São Gonçalo do Abaeté']);
		DB::table('cidades')->insert(['id' => 3161809, 'estado_id' => 31, 'nome' => 'São Gonçalo do Pará']);
		DB::table('cidades')->insert(['id' => 3161908, 'estado_id' => 31, 'nome' => 'São Gonçalo do Rio Abaixo']);
		DB::table('cidades')->insert(['id' => 3162005, 'estado_id' => 31, 'nome' => 'São Gonçalo do Sapucaí']);
		DB::table('cidades')->insert(['id' => 3162104, 'estado_id' => 31, 'nome' => 'São Gotardo']);
		DB::table('cidades')->insert(['id' => 3162203, 'estado_id' => 31, 'nome' => 'São João Batista do Glória']);
		DB::table('cidades')->insert(['id' => 3162252, 'estado_id' => 31, 'nome' => 'São João da Lagoa']);
		DB::table('cidades')->insert(['id' => 3162302, 'estado_id' => 31, 'nome' => 'São João da Mata']);
		DB::table('cidades')->insert(['id' => 3162401, 'estado_id' => 31, 'nome' => 'São João da Ponte']);
		DB::table('cidades')->insert(['id' => 3162450, 'estado_id' => 31, 'nome' => 'São João das Missões']);
		DB::table('cidades')->insert(['id' => 3162500, 'estado_id' => 31, 'nome' => 'São João del Rei']);
		DB::table('cidades')->insert(['id' => 3162559, 'estado_id' => 31, 'nome' => 'São João do Manhuaçu']);
		DB::table('cidades')->insert(['id' => 3162575, 'estado_id' => 31, 'nome' => 'São João do Manteninha']);
		DB::table('cidades')->insert(['id' => 3162609, 'estado_id' => 31, 'nome' => 'São João do Oriente']);
		DB::table('cidades')->insert(['id' => 3162658, 'estado_id' => 31, 'nome' => 'São João do Pacuí']);
		DB::table('cidades')->insert(['id' => 3162708, 'estado_id' => 31, 'nome' => 'São João do Paraíso']);
		DB::table('cidades')->insert(['id' => 3162807, 'estado_id' => 31, 'nome' => 'São João Evangelista']);
		DB::table('cidades')->insert(['id' => 3162906, 'estado_id' => 31, 'nome' => 'São João Nepomuceno']);
		DB::table('cidades')->insert(['id' => 3162922, 'estado_id' => 31, 'nome' => 'São Joaquim de Bicas']);
		DB::table('cidades')->insert(['id' => 3162948, 'estado_id' => 31, 'nome' => 'São José da Barra']);
		DB::table('cidades')->insert(['id' => 3162955, 'estado_id' => 31, 'nome' => 'São José da Lapa']);
		DB::table('cidades')->insert(['id' => 3163003, 'estado_id' => 31, 'nome' => 'São José da Safira']);
		DB::table('cidades')->insert(['id' => 3163102, 'estado_id' => 31, 'nome' => 'São José da Varginha']);
		DB::table('cidades')->insert(['id' => 3163201, 'estado_id' => 31, 'nome' => 'São José do Alegre']);
		DB::table('cidades')->insert(['id' => 3163300, 'estado_id' => 31, 'nome' => 'São José do Divino']);
		DB::table('cidades')->insert(['id' => 3163409, 'estado_id' => 31, 'nome' => 'São José do Goiabal']);
		DB::table('cidades')->insert(['id' => 3163508, 'estado_id' => 31, 'nome' => 'São José do Jacuri']);
		DB::table('cidades')->insert(['id' => 3163607, 'estado_id' => 31, 'nome' => 'São José do Mantimento']);
		DB::table('cidades')->insert(['id' => 3163706, 'estado_id' => 31, 'nome' => 'São Lourenço']);
		DB::table('cidades')->insert(['id' => 3163805, 'estado_id' => 31, 'nome' => 'São Miguel do Anta']);
		DB::table('cidades')->insert(['id' => 3163904, 'estado_id' => 31, 'nome' => 'São Pedro da União']);
		DB::table('cidades')->insert(['id' => 3164001, 'estado_id' => 31, 'nome' => 'São Pedro dos Ferros']);
		DB::table('cidades')->insert(['id' => 3164100, 'estado_id' => 31, 'nome' => 'São Pedro do Suaçuí']);
		DB::table('cidades')->insert(['id' => 3164209, 'estado_id' => 31, 'nome' => 'São Romão']);
		DB::table('cidades')->insert(['id' => 3164308, 'estado_id' => 31, 'nome' => 'São Roque de Minas']);
		DB::table('cidades')->insert(['id' => 3164407, 'estado_id' => 31, 'nome' => 'São Sebastião da Bela Vista']);
		DB::table('cidades')->insert(['id' => 3164431, 'estado_id' => 31, 'nome' => 'São Sebastião da Vargem Alegre']);
		DB::table('cidades')->insert(['id' => 3164472, 'estado_id' => 31, 'nome' => 'São Sebastião do Anta']);
		DB::table('cidades')->insert(['id' => 3164506, 'estado_id' => 31, 'nome' => 'São Sebastião do Maranhão']);
		DB::table('cidades')->insert(['id' => 3164605, 'estado_id' => 31, 'nome' => 'São Sebastião do Oeste']);
		DB::table('cidades')->insert(['id' => 3164704, 'estado_id' => 31, 'nome' => 'São Sebastião do Paraíso']);
		DB::table('cidades')->insert(['id' => 3164803, 'estado_id' => 31, 'nome' => 'São Sebastião do Rio Preto']);
		DB::table('cidades')->insert(['id' => 3164902, 'estado_id' => 31, 'nome' => 'São Sebastião do Rio Verde']);
		DB::table('cidades')->insert(['id' => 3165008, 'estado_id' => 31, 'nome' => 'São Tiago']);
		DB::table('cidades')->insert(['id' => 3165107, 'estado_id' => 31, 'nome' => 'São Tomás de Aquino']);
		DB::table('cidades')->insert(['id' => 3165206, 'estado_id' => 31, 'nome' => 'São Thomé das Letras']);
		DB::table('cidades')->insert(['id' => 3165305, 'estado_id' => 31, 'nome' => 'São Vicente de Minas']);
		DB::table('cidades')->insert(['id' => 3165404, 'estado_id' => 31, 'nome' => 'Sapucaí-Mirim']);
		DB::table('cidades')->insert(['id' => 3165503, 'estado_id' => 31, 'nome' => 'Sardoá']);
		DB::table('cidades')->insert(['id' => 3165537, 'estado_id' => 31, 'nome' => 'Sarzedo']);
		DB::table('cidades')->insert(['id' => 3165552, 'estado_id' => 31, 'nome' => 'Setubinha']);
		DB::table('cidades')->insert(['id' => 3165560, 'estado_id' => 31, 'nome' => 'Sem-Peixe']);
		DB::table('cidades')->insert(['id' => 3165578, 'estado_id' => 31, 'nome' => 'Senador Amaral']);
		DB::table('cidades')->insert(['id' => 3165602, 'estado_id' => 31, 'nome' => 'Senador Cortes']);
		DB::table('cidades')->insert(['id' => 3165701, 'estado_id' => 31, 'nome' => 'Senador Firmino']);
		DB::table('cidades')->insert(['id' => 3165800, 'estado_id' => 31, 'nome' => 'Senador José Bento']);
		DB::table('cidades')->insert(['id' => 3165909, 'estado_id' => 31, 'nome' => 'Senador Modestino Gonçalves']);
		DB::table('cidades')->insert(['id' => 3166006, 'estado_id' => 31, 'nome' => 'Senhora de Oliveira']);
		DB::table('cidades')->insert(['id' => 3166105, 'estado_id' => 31, 'nome' => 'Senhora do Porto']);
		DB::table('cidades')->insert(['id' => 3166204, 'estado_id' => 31, 'nome' => 'Senhora dos Remédios']);
		DB::table('cidades')->insert(['id' => 3166303, 'estado_id' => 31, 'nome' => 'Sericita']);
		DB::table('cidades')->insert(['id' => 3166402, 'estado_id' => 31, 'nome' => 'Seritinga']);
		DB::table('cidades')->insert(['id' => 3166501, 'estado_id' => 31, 'nome' => 'Serra Azul de Minas']);
		DB::table('cidades')->insert(['id' => 3166600, 'estado_id' => 31, 'nome' => 'Serra da Saudade']);
		DB::table('cidades')->insert(['id' => 3166709, 'estado_id' => 31, 'nome' => 'Serra dos Aimorés']);
		DB::table('cidades')->insert(['id' => 3166808, 'estado_id' => 31, 'nome' => 'Serra do Salitre']);
		DB::table('cidades')->insert(['id' => 3166907, 'estado_id' => 31, 'nome' => 'Serrania']);
		DB::table('cidades')->insert(['id' => 3166956, 'estado_id' => 31, 'nome' => 'Serranópolis de Minas']);
		DB::table('cidades')->insert(['id' => 3167004, 'estado_id' => 31, 'nome' => 'Serranos']);
		DB::table('cidades')->insert(['id' => 3167103, 'estado_id' => 31, 'nome' => 'Serro']);
		DB::table('cidades')->insert(['id' => 3167202, 'estado_id' => 31, 'nome' => 'Sete Lagoas']);
		DB::table('cidades')->insert(['id' => 3167301, 'estado_id' => 31, 'nome' => 'Silveirânia']);
		DB::table('cidades')->insert(['id' => 3167400, 'estado_id' => 31, 'nome' => 'Silvianópolis']);
		DB::table('cidades')->insert(['id' => 3167509, 'estado_id' => 31, 'nome' => 'Simão Pereira']);
		DB::table('cidades')->insert(['id' => 3167608, 'estado_id' => 31, 'nome' => 'Simonésia']);
		DB::table('cidades')->insert(['id' => 3167707, 'estado_id' => 31, 'nome' => 'Sobrália']);
		DB::table('cidades')->insert(['id' => 3167806, 'estado_id' => 31, 'nome' => 'Soledade de Minas']);
		DB::table('cidades')->insert(['id' => 3167905, 'estado_id' => 31, 'nome' => 'Tabuleiro']);
		DB::table('cidades')->insert(['id' => 3168002, 'estado_id' => 31, 'nome' => 'Taiobeiras']);
		DB::table('cidades')->insert(['id' => 3168051, 'estado_id' => 31, 'nome' => 'Taparuba']);
		DB::table('cidades')->insert(['id' => 3168101, 'estado_id' => 31, 'nome' => 'Tapira']);
		DB::table('cidades')->insert(['id' => 3168200, 'estado_id' => 31, 'nome' => 'Tapiraí']);
		DB::table('cidades')->insert(['id' => 3168309, 'estado_id' => 31, 'nome' => 'Taquaraçu de Minas']);
		DB::table('cidades')->insert(['id' => 3168408, 'estado_id' => 31, 'nome' => 'Tarumirim']);
		DB::table('cidades')->insert(['id' => 3168507, 'estado_id' => 31, 'nome' => 'Teixeiras']);
		DB::table('cidades')->insert(['id' => 3168606, 'estado_id' => 31, 'nome' => 'Teófilo Otoni']);
		DB::table('cidades')->insert(['id' => 3168705, 'estado_id' => 31, 'nome' => 'Timóteo']);
		DB::table('cidades')->insert(['id' => 3168804, 'estado_id' => 31, 'nome' => 'Tiradentes']);
		DB::table('cidades')->insert(['id' => 3168903, 'estado_id' => 31, 'nome' => 'Tiros']);
		DB::table('cidades')->insert(['id' => 3169000, 'estado_id' => 31, 'nome' => 'Tocantins']);
		DB::table('cidades')->insert(['id' => 3169059, 'estado_id' => 31, 'nome' => 'Tocos do Moji']);
		DB::table('cidades')->insert(['id' => 3169109, 'estado_id' => 31, 'nome' => 'Toledo']);
		DB::table('cidades')->insert(['id' => 3169208, 'estado_id' => 31, 'nome' => 'Tombos']);
		DB::table('cidades')->insert(['id' => 3169307, 'estado_id' => 31, 'nome' => 'Três Corações']);
		DB::table('cidades')->insert(['id' => 3169356, 'estado_id' => 31, 'nome' => 'Três Marias']);
		DB::table('cidades')->insert(['id' => 3169406, 'estado_id' => 31, 'nome' => 'Três Pontas']);
		DB::table('cidades')->insert(['id' => 3169505, 'estado_id' => 31, 'nome' => 'Tumiritinga']);
		DB::table('cidades')->insert(['id' => 3169604, 'estado_id' => 31, 'nome' => 'Tupaciguara']);
		DB::table('cidades')->insert(['id' => 3169703, 'estado_id' => 31, 'nome' => 'Turmalina']);
		DB::table('cidades')->insert(['id' => 3169802, 'estado_id' => 31, 'nome' => 'Turvolândia']);
		DB::table('cidades')->insert(['id' => 3169901, 'estado_id' => 31, 'nome' => 'Ubá']);
		DB::table('cidades')->insert(['id' => 3170008, 'estado_id' => 31, 'nome' => 'Ubaí']);
		DB::table('cidades')->insert(['id' => 3170057, 'estado_id' => 31, 'nome' => 'Ubaporanga']);
		DB::table('cidades')->insert(['id' => 3170107, 'estado_id' => 31, 'nome' => 'Uberaba']);
		DB::table('cidades')->insert(['id' => 3170206, 'estado_id' => 31, 'nome' => 'Uberlândia']);
		DB::table('cidades')->insert(['id' => 3170305, 'estado_id' => 31, 'nome' => 'Umburatiba']);
		DB::table('cidades')->insert(['id' => 3170404, 'estado_id' => 31, 'nome' => 'Unaí']);
		DB::table('cidades')->insert(['id' => 3170438, 'estado_id' => 31, 'nome' => 'União de Minas']);
		DB::table('cidades')->insert(['id' => 3170479, 'estado_id' => 31, 'nome' => 'Uruana de Minas']);
		DB::table('cidades')->insert(['id' => 3170503, 'estado_id' => 31, 'nome' => 'Urucânia']);
		DB::table('cidades')->insert(['id' => 3170529, 'estado_id' => 31, 'nome' => 'Urucuia']);
		DB::table('cidades')->insert(['id' => 3170578, 'estado_id' => 31, 'nome' => 'Vargem Alegre']);
		DB::table('cidades')->insert(['id' => 3170602, 'estado_id' => 31, 'nome' => 'Vargem Bonita']);
		DB::table('cidades')->insert(['id' => 3170651, 'estado_id' => 31, 'nome' => 'Vargem Grande do Rio Pardo']);
		DB::table('cidades')->insert(['id' => 3170701, 'estado_id' => 31, 'nome' => 'Varginha']);
		DB::table('cidades')->insert(['id' => 3170750, 'estado_id' => 31, 'nome' => 'Varjão de Minas']);
		DB::table('cidades')->insert(['id' => 3170800, 'estado_id' => 31, 'nome' => 'Várzea da Palma']);
		DB::table('cidades')->insert(['id' => 3170909, 'estado_id' => 31, 'nome' => 'Varzelândia']);
		DB::table('cidades')->insert(['id' => 3171006, 'estado_id' => 31, 'nome' => 'Vazante']);
		DB::table('cidades')->insert(['id' => 3171030, 'estado_id' => 31, 'nome' => 'Verdelândia']);
		DB::table('cidades')->insert(['id' => 3171071, 'estado_id' => 31, 'nome' => 'Veredinha']);
		DB::table('cidades')->insert(['id' => 3171105, 'estado_id' => 31, 'nome' => 'Veríssimo']);
		DB::table('cidades')->insert(['id' => 3171154, 'estado_id' => 31, 'nome' => 'Vermelho Novo']);
		DB::table('cidades')->insert(['id' => 3171204, 'estado_id' => 31, 'nome' => 'Vespasiano']);
		DB::table('cidades')->insert(['id' => 3171303, 'estado_id' => 31, 'nome' => 'Viçosa']);
		DB::table('cidades')->insert(['id' => 3171402, 'estado_id' => 31, 'nome' => 'Vieiras']);
		DB::table('cidades')->insert(['id' => 3171501, 'estado_id' => 31, 'nome' => 'Mathias Lobato']);
		DB::table('cidades')->insert(['id' => 3171600, 'estado_id' => 31, 'nome' => 'Virgem da Lapa']);
		DB::table('cidades')->insert(['id' => 3171709, 'estado_id' => 31, 'nome' => 'Virgínia']);
		DB::table('cidades')->insert(['id' => 3171808, 'estado_id' => 31, 'nome' => 'Virginópolis']);
		DB::table('cidades')->insert(['id' => 3171907, 'estado_id' => 31, 'nome' => 'Virgolândia']);
		DB::table('cidades')->insert(['id' => 3172004, 'estado_id' => 31, 'nome' => 'Visconde do Rio Branco']);
		DB::table('cidades')->insert(['id' => 3172103, 'estado_id' => 31, 'nome' => 'Volta Grande']);
		DB::table('cidades')->insert(['id' => 3172202, 'estado_id' => 31, 'nome' => 'Wenceslau Braz',]);
    }
}
